### ISSUE TITLE
Why after Logout, coontinue to pass the Authorize attribute?

### ISSUE THREAD

**Issue by joaomello** [IdentityServer/IdentityServer4.Samples#10]
Hi, I'm logged at Mvc Implicit and after log out. Ok home screen show that I'm not logged in but the secure route can be access yet, is that right?

Update: App logs in me again.

**Comment by tessierp** [comment]
I have the same issue. I logout, the system confirms I am logged out, then when I pressure SECURE again, it logs me back with the user I previously logged in with.

**Comment by ircnelson** [comment]
Because the logout did not occur in identityserver, only on the client. The authentication cookie is still alive in the domain of identityserver. While this cookie stay the client will understand that the user is authenticated.

This behavior is not an issue.

**Comment by joaomello** [comment]
Yes yes, you are right @ircnelson. I add an update and because saw that I was redirect to idsrv and after to app authenticated. Thanks :)
