### ISSUE TITLE
Xamarin sample

### ISSUE THREAD

**Issue by Kasparus** [IdentityServer/IdentityServer4.Samples#103]
Hi.

I'm using identity server 4 for managing users for two client applications with underlying api's/microservices but I'm having problems implementing identity server with my xamarin.forms clients. Is there any future plan to make any xamarin samples and/or documentation.

What I'm most confused about at this moment is whether or not it is acceptable or even possible to implement native account management controls in xamarin and if identity server can be used as any other identity provider as in this example: https://developer.xamarin.com/guides/xamarin-forms/web-services/authentication/oauth/

Cheers!

**Comment by brockallen** [comment]
There are some here: https://github.com/IdentityModel/IdentityModel.OidcClient.Samples

**Comment by Kasparus** [comment]
@brockallen Thanks! About using native forms/controls, do you have a good answer for that or any blog posts maybe that can point me in the right direction?

**Comment by brockallen** [comment]
No idea
