### ISSUE TITLE
Redirect after log out doesn't work anymore

### ISSUE THREAD

**Issue by VladDragnea** [IdentityServer/IdentityServer4.Samples#104]
I'm trying to use IdentityServer4 in a project much like the Quickstart6_AspNetIdentity sample. I've just updated the version of "Microsoft.AspNetCore.Authentication.OpenIdConnect" from "1.0.0" to "1.1.0" in the MvcClient and now after logout the redirect to the MvcClient doesn't work anymore. As far as I can tell, the "logoutId" parameter of AccountController's Logout method is null (and is missing in the query string).

**Comment by brockallen** [comment]
That was  a change in 1.1 of the OIDC MW from Microsoft. You must now use ~/signout-callback-oidc as the post logout redirect URI.

**Comment by VladDragnea** [comment]
Thanks! It works.
