### ISSUE TITLE
Ensuring that the version numbers stay current

### ISSUE THREAD

**Issue by adriatic** [IdentityServer/IdentityServer4.Samples#106]
Watching Identity Server grow from its early day to what is available today feels like time travel story (meaning that a lot of good stuff was continuously created in relatively short time and by very few contributors. Using Identity Server 4 finally reached the level where I am quite anxious to use without having to sweat for weeks. The remaining problem is really the need to constantly update various version numbers in order to ensure that once can clone the samples collection and run them without having to fix things up. 

Here is what happens when loading **`Quickstart2_ResourceOwnerPasswords`** sample

![image](https://cloud.githubusercontent.com/assets/2712405/22179853/e31c9eda-e02c-11e6-8712-7ec833485b04.png)

#### My questions:
1. Do you care to have these samples current with MS component s changes?
2. Do you have some "preferred contributors" that take care of that - or any random folks like me should provide you with PRs?

**Comment by leastprivilege** [comment]
Maybe Microsoft should hire people to update all the OSS projects whenever they release another beta version of something ;)

That said - our readme says:

> IdentityServer is built against ASP.NET Core 1.1.0 using the 1.0.0-preview2-003131 SDK. This is the only configuration we gonna support on the issue tracker.

We gonna stay on that configuration until the final tooling is available (with Visual Studio 2017).

**Comment by adriatic** [comment]
Makes sense (assuming that this specific version remains available until the final tooling becomes available). Thank you @leastprivilege 😄

**Comment by brockallen** [comment]
We're just as affected by Microsoft's churn as everyone else. We picked a version that's working for us, and we documented it.
