### ISSUE TITLE
Are you interested in suggestion for improving the documentation

### ISSUE THREAD

**Issue by adriatic** [IdentityServer/IdentityServer4.Samples#107]
There is hardly better source of feedback that someone working through your application with the determination to succeed. While I can say that using the IdentityServer4 has become a ton easier, I would like to point out the "discontinuities" in the online documentation - areas where I get lost, despite having a pretty good overall picture of the landscape.

As an example, I will use **[Protecting an API using Client Credentials](https://identityserver4.readthedocs.io/en/dev/quickstarts/1_client_credentials.html)**, - section **[Adding an API](https://identityserver4.readthedocs.io/en/dev/quickstarts/1_client_credentials.html#adding-an-api)**:

> You can use the ASP.NET Core Web API template for that. Again, we recommend you take control over the ports and use the same technique as you used to configure Kestrel and the launch profile as before. This walkthrough assumes you have configured your API to run on http://localhost:5001.

I got stumped by `You can use the ASP.NET Core Web API template` looking at my current code that was a solution with a single project. I had to dig around a bit and would rewrite this section as:

_You can use the ASP.NET Core Web API template for that (use **[this tutorial](https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-web-api)** as a guidance and note that it requires adding this functionality as a new project to your solution). Again, we recommend you take control over the ports and use the same technique as you used to configure Kestrel and the launch profile as before. This walkthrough assumes you have configured your API to run on http://localhost:5001._

_See all three projects (Api, Client, QuickstartIdentityServer) for this tutorial **[here](https://github.com/IdentityServer/IdentityServer4.Samples/tree/dev/Quickstarts/1_ClientCredentials/src)**_

**Comment by adriatic** [comment]
Similarly, in the care of a bit more involved example ([ResourceOwnerPasswords](https://github.com/IdentityServer/IdentityServer4.Samples/tree/dev/Quickstarts/2_ResourceOwnerPasswords)), I would use the opportunity to match the (very nice) **[picture](https://identityserver4.readthedocs.io/en/dev/intro/big_picture.html#the-big-picture)** with the four "main programs":

- **[Api](https://github.com/IdentityServer/IdentityServer4.Samples/blob/dev/Quickstarts/2_ResourceOwnerPasswords/src/Api/Program.cs)**
- **[Client](https://github.com/IdentityServer/IdentityServer4.Samples/blob/dev/Quickstarts/2_ResourceOwnerPasswords/src/Client/Program.cs)**
- **[IdentityServer](https://github.com/IdentityServer/IdentityServer4.Samples/blob/dev/Quickstarts/2_ResourceOwnerPasswords/src/QuickstartIdentityServer/Program.cs)**
- **[ResourceOwnerClient](https://github.com/IdentityServer/IdentityServer4.Samples/blob/dev/Quickstarts/2_ResourceOwnerPasswords/src/ResourceOwnerClient/Program.cs)**

**Comment by adriatic** [comment]
Probably the last comment related to **[ResourceOwnerPasswords](https://github.com/IdentityServer/IdentityServer4.Samples/tree/dev/Quickstarts/2_ResourceOwnerPasswords)**: 

The completed solution:

![image](https://cloud.githubusercontent.com/assets/2712405/22183743/beeaf2ee-e092-11e6-89b4-847bde091b28.png)

is configured to have the QuickstartIdentityServer project set up as the `StartUp` project - but this is insufficient to use Visual Studio`s `Ctrl F5` run command. 

What is the proper way to run and play this distributed system of apps?

**Comment by leastprivilege** [comment]
Feel free to PR the shit out of it ;)

---
cheers
Dominick Baier




On Sun, Jan 22, 2017 at 5:10 PM +0100, "Nikolaj Ivancic" <notifications@github.com> wrote:












Probably the last comment related to ResourceOwnerPasswords:


The completed solution:





is configured to have the QuickstartIdentityServer project set up as the StartUp project - but this is insufficient to use Visual StudiosCtrl F5` run command.


What is the proper way to run and play this distributed system of apps?

**Comment by adriatic** [comment]
With pleasure - but before I can cover all aspects I want to add to, I need your answer to the above posted question:

### What is the proper way to run and play with this distributed system of apps?

**Comment by leastprivilege** [comment]
No - just as usual - either set multiple startup projects - or "current selection" - that a solution setting.

**Comment by adriatic** [comment]
### Would you agree to add this as a common "prelude" for all samples:

Use **[How to: Set Multiple Startup Projects](https://msdn.microsoft.com/en-us/library/ms165413.aspx)** to ensure that all (console hosted) processes in all subsequent samples can run together

![image](https://cloud.githubusercontent.com/assets/2712405/22186178/7389c47e-e0bf-11e6-9032-4739aa98cad0.png)

I also set all dependencies (although I believe that these are used in build stage - not run)

![image](https://cloud.githubusercontent.com/assets/2712405/22186203/d404c0e2-e0bf-11e6-8638-1f6faf0cecea.png)

Finally here are the configuration settings (not sure whether that is relevant to my problem)

![image](https://cloud.githubusercontent.com/assets/2712405/22186222/334c895e-e0c0-11e6-9c05-f97e1a39c464.png)

One **has** to use the F5 (start debugging) for this to work, however the console hosted apps exit before one can see anything.

**Note**: add the instruction **`Console.ReadKey();`** in all instances of the **`Program.cs`** to prevent these apps to exit prematurely.

**Comment by leastprivilege** [comment]
That's now how I run the samples. I will add something to the intro section. thanks.

**Comment by leastprivilege** [comment]
I added a comment to

http://docs.identityserver.io/en/release/quickstarts/0_overview.html

feel free to PR if you want to add more info to it.
