### ISSUE TITLE
Kestrel fails to bind to address http://localhost:5000

### ISSUE THREAD

**Issue by adriatic** [IdentityServer/IdentityServer4.Samples#109]
Setting the Launch settings to be:

![image](https://cloud.githubusercontent.com/assets/2712405/22270900/d7940ca8-e25f-11e6-8626-330e94e96e95.png)

crashes Kestrel as shown below

![image](https://cloud.githubusercontent.com/assets/2712405/22271007/735c1bee-e260-11e6-8ca3-2eedd4e207d9.png)

That same sample works fine if you **do not follow** the advice shown below:

![image](https://cloud.githubusercontent.com/assets/2712405/22271091/e17135ec-e260-11e6-9ddb-6c8365ee49eb.png)

**Comment by adriatic** [comment]
#### I do not believe that this is just the documentation error, which is why I am supplying this as an error report - not a PR.

**Comment by leastprivilege** [comment]
Maybe your IIS Express is still running...

I always use the project properties to set the IIS Express port.
