### ISSUE TITLE
Endpoint is on a different host than authority

### ISSUE THREAD

**Issue by ivanoxq** [IdentityServer/IdentityServer4.Samples#111]
Hi Guys,

I get an error when I am creating the console client from the samples: Endpoint is on a different host than authority: http://localhost:5000/.well-known/openid-configuration/jwks

Does anyone know what this means?

**Comment by leastprivilege** [comment]
What's your authority?

**Comment by leastprivilege** [comment]
Are you on the latest samples? What's your version of IdentityModel you are using?

**Comment by ivanoxq** [comment]
Hi Dominick,

I corrected the issue by updating from version 2.2 to version 2.5. It was
an issue in the logic of the DiscoveryResponse Object ValidateEndpoint
function.
