### ISSUE TITLE
Multiple external id providers

### ISSUE THREAD

**Issue by simonjonesy** [IdentityServer/IdentityServer4.Samples#112]
Login information is from many different id servers ADFS, Azure identity etc. Some of our customers have their own id servers and would like to connect these servers to our Saas application. Using idserver4 could we accomplish this.

**Comment by brockallen** [comment]
Yes. See the sample code: https://github.com/IdentityServer/IdentityServer4.Samples/tree/dev/Quickstarts/4_ImplicitFlowAuthenticationWithExternal
