### ISSUE TITLE
docker-compose client asking for access the api

### ISSUE THREAD

**Issue by eld1887** [IdentityServer/IdentityServer4.Samples#114]
I hope someone can help me. I tried to build the quickstart examples with docker-compose.
So i look at the docker folder and created the docker-compose.yml and the dockerfiles. 
After that i created the project, how it was discribed at the quickstarter: http://docs.identityserver.io/en/release/quickstarts/1_client_credentials.html

but if i try to run this example, my output look like that:

```
{
client            |   "access_token": "eyJhbGciOiJSUzI1NiIsImtpZCI6Ijg4M2YxYTJlOThjODA2MDc2YTYyY2Q1ZmIzYmMwOTE4IiwidHlwIjoiSldUIn0.eyJuYmYiOjE0ODYxMzU3MzQsImV4cCI6MTQ4NjEzOTMzNCwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjpbImh0dHA6Ly9sb2NhbGhvc3Q6NTAwMC9yZXNvdXJjZXMiLCJhcGkxIl0sImNsaWVudF9pZCI6ImNsaWVudCIsInNjb3BlIjpbImFwaTEiXX0.Jk0MqKwvTimM9Yp27SXhymlK-MvBPV8KmZMVskF9HB-ISJBoTTp83-76G2BsxMv4E0u-Z3cYdG76tHHHCGsalQLM3zj366xwPXXu_XDCntjCYeMd0g0HJoeKXQTJTjYvRjNRzeo5yqDfLrzHUMxtqkauOKtAK4eqOU4zQ4eE5bRsIz6uT_-aAPVjWVBAFRfdFWidrtNevG9K-TzjhPsXExXheUpOt_c0JQ1Iyq0UtE6h08K210zPPiDKKQcqn-9Z1RkqyricZsklrvtkdnlszP1sG7D1Gp7vYj38Cum-IS-9xg1uKGkvILg1rL7g-z-zMcnElECfv3R18VfFvR2Nkg",
client            |   "expires_in": 3600,
client            |   "token_type": "Bearer"
client            | }
client            | Unhandled Exception: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.Http.CurlException: Couldn't connect to server

```
the client aasking the idserver for access token and getting it. after that the client asking the api for access but the server is not there.....and i don´t know why.

without docker it working well. i attached my project. Hopefully someone can help me.

[id4.zip](https://github.com/IdentityServer/IdentityServer4.Samples/files/750912/id4.zip)

**Comment by eld1887** [comment]
hi,
i solved the problem by myself.
greetings

**Comment by brockallen** [comment]
What was the fix?

**Comment by eld1887** [comment]
i have to change the line : var response = await client.GetAsync("http://localhost:1773/identity"); into var response = await client.GetAsync("http://api:1773/identity"); at the program.cs in the client project folder.
thats adresse that was declared at the docker-compose.yml, but everywherer, was to read that it works with localhost too.

greetings
