### ISSUE TITLE
6_AspNetIdentity Content-Security-Policy errors

### ISSUE THREAD

**Issue by JoeyHerrington** [IdentityServer/IdentityServer4.Samples#115]
Browser error: `Resource violated directive 'default-src 'self'' in Content-Security-Policy` in Edge.
Similar errors occur in Chrome and Firefox.  I did not see this error in I.E.

I only see the error when I run **quickstart/6_AspNetIdentity**.  None of the other quickstarts appear to have the problem.  I tested it using the freshest copy downloaded this morning, and none of the source was modified as I was testing it.

I also only see the error whether I run the solution in Visual Studio, VS Code, or directly from the command-line.

The problem seems to be isolated to localhost:5000.  None of the clients appear to have this issue.

To ensure the problem is not with my desktop, I downloaded and ran the code from another machine and I got the same error.

Thanks

**Comment by JoeyHerrington** [comment]
Note: Not setting `Content-Security-Policy` in `SecurityHeadersAttribute` seemed to clear this up...

**Comment by leastprivilege** [comment]
@brockallen ?

**Comment by brockallen** [comment]
Ah, yes. I see the error. It's from this line:

```
<div asp-validation-summary="All" class="text-danger"></div>
```

Which is from the ASP.NET Identity templates. It doesn't seem to prevent anything from working, it's just an error in the console window.  This is unfortunate because the inline style is coming from the tag helper from ASP.NET Core. I'm inclined to ignore it, or perhaps even open an issue with them since that's a bad idea to emit inline styles.

**Comment by brockallen** [comment]
Turns out there was already an open issue for it: https://github.com/aspnet/Mvc/issues/4300#issuecomment-282844964

**Comment by brockallen** [comment]
I'm inclined to close this since it's something you can fix if you need/want to via the code that's in the sample.

**Comment by armitagemderivitec** [comment]
Hi,

Just to be clear what is the solution here? 

Thanks 

Mike
