### ISSUE TITLE
8_EntityFrameworkStorage unauthorized_client Error

### ISSUE THREAD

**Issue by mikicaradojcic** [IdentityServer/IdentityServer4.Samples#116]
Hi guys great work since version 2. 

Took your Quick Start number 8 and just changed client address port on 
server on those lines:
                    RedirectUris = { "http://localhost:5010/signin-oidc" },
                    PostLogoutRedirectUris = { "http://localhost:5010" },
and on client in this line
.UseUrls("http://localhost:5010")

Now I'm getting unauthorized_client but I cannot find what else should I configure.

Thanks

**Comment by leastprivilege** [comment]
check the logs
