### ISSUE TITLE
3_ImplicitFlowAuthentication With OpenIdConnect 1.1.0 fails to redirect back to login

### ISSUE THREAD

**Issue by blackram** [IdentityServer/IdentityServer4.Samples#117]
Hi,

I was following the tutorial for 3_ImplicitFlowAuthentication from http://docs.identityserver.io/en/release/quickstarts/3_interactive_login.html using .**net core 1.1.**

I noticed that the post logout redirect uri was null and that the logoutId was also null. This means that after logout the user is left on the identity server logout page with the message "You are now logged out" with no link back to the application and automatic redirect via the AccountOptions certainly will not then work.

I have reproduced this issue using the QuickStarts (3_ImplicitFlowAuthentication) by cloning the quick start, editing the package.json for the mvc project and to set the OpenIdConnect version to 1.1.0.

I realise that the MVC sample is 1.0 and the identity server is on 1.1.

Is this expected behaviour that I should wait to be fixed or something that I have missed?

Thanks

**Comment by leastprivilege** [comment]
Yes - there is a breaking change between 1.0 and 1.1 in the open id connect middleware from Microsoft. You need to set the post logout uri to `http://mypp/signout-oidc` (IIRC)

**Comment by blackram** [comment]
Thanks for getting back to me.

I've now gone looking in [OpenIdConnectOptions](https://github.com/aspnet/Security/blob/0c815da523fcf8435bb46105c43e21ab1123bfef/src/Microsoft.AspNetCore.Authentication.OpenIdConnect/OpenIdConnectOptions.cs) and the path is **/signout-callback-oidc** so the Post Logout Redirect Uris setting is now:

 PostLogoutRedirectUris = { "http://localhost:5002/**signout-callback-oidc**" }.
