### ISSUE TITLE
Return Url

### ISSUE THREAD

**Issue by rh78** [IdentityServer/IdentityServer4.Samples#119]
Hello a question: why in the MVC IdSrv4 examples there is dedicated return URL handling? Will the return/redirect URL not be set in the Identity Login context and accessible there anyways? I do not see the reason why it is passed around "manually". Thanks for any clarification or help!

**Comment by brockallen** [comment]
> Hello a question: why in the MVC IdSrv4 examples there is dedicated return URL handling

Can you elaborate on what you mean?

**Comment by rh78** [comment]
Hi e.g. in the Account Controller the returnUrl gets passed in via Login method. It is then forwarded to the IdSrv interaction service, and then - whenever I want to get e.g. the login view model - i need that return URl again. now if the user navigates to some other page e.g. email confirmation, password reset, I need to handle that URL and send it in order not to lose it. I could store it in a cookie (because session is not possible on largely scaled system) but first I want to know why it is there in the first place. Thanks!

**Comment by leastprivilege** [comment]
Because we need to keep state. The "return URL parameter" pattern is pretty common, even in traditional login pages.

Cookies are troublesome for many scenarios. That's why we decided to do it via the URL.

**Comment by rh78** [comment]
Ok thanks for the help!
