### ISSUE TITLE
PostLogoutRedirectUri

### ISSUE THREAD

**Issue by daver77** [IdentityServer/IdentityServer4.Samples#121]
Hi,

Are there any examples showing how to redirect straight back to PostLogoutRedirectUri from /account/logout ?

I see if referenced here but the link is dead
https://github.com/IdentityServer/IdentityServer4/issues/481#issuecomment-261166362

**Comment by daver77** [comment]
is this correct?

```
        [AllowAnonymous]
        [HttpGet]
        public async Task<IActionResult> Logout(string logoutId)
        {
            await _signInManager.SignOutAsync();

            var context = await _interaction.GetLogoutContextAsync(logoutId);
            
            return Redirect(context.PostLogoutRedirectUri);
        }
```

**Comment by brockallen** [comment]
You don't want to do that, as you will prevent the SLO (single logout) from working.

**Comment by daver77** [comment]
Yeah, we're not implementing SLO just yet as we only have 1 relying party

Do you have an example showing SLO for future use?

**Comment by brockallen** [comment]
our samples already have SLO
