### ISSUE TITLE
Using IProfileService when sign-in by Google OAuth

### ISSUE THREAD

**Issue by mrtaikandi** [IdentityServer/IdentityServer4.Samples#122]
I'm trying to change the IdentityServer4 AspNetIdentity sample to be able to login from both local created users and Google. 

I was able to do this by adding Google authentication: 

            app.UseIdentity();
            app.UseIdentityServer();
           
            var cookieScheme = app.ApplicationServices.GetRequiredService<IOptions<IdentityOptions>>().Value.Cookies.ExternalCookieAuthenticationScheme;

            // Add external authentication middleware below. To configure them please see http://go.microsoft.com/fwlink/?LinkID=532715
            app.UseGoogleAuthentication(new GoogleOptions
            {
                AuthenticationScheme = "Google",
                SignInScheme = cookieScheme,
                ClientId = "client_id",
                ClientSecret = "client_secret"
            });

As expected the Home view shows correct user claims: 

sub
c51da331-0348-45dd-352f-08d4526f6266
name
EMAIL@gmail.com
AspNet.Identity.SecurityStamp
568a167f-a431-4f70-ba66-918f99e95eef
idp
Google
amr
external
auth_time
1486815555

When user signs in for the first time using Google account I add some information to the database and I thought I can add them to the user claims by using a custom IProfileService implementation and configuring IdentityServer to use my custom IProfileService:

             var builder = services.AddIdentityServer();
             builder.AddTemporarySigningCredential();

            builder.AddConfigurationStore(b => b.UseSqlServer(connectionString, options => options.MigrationsAssembly(migrationAssembly)));
            builder.AddOperationalStore(b => b.UseSqlServer(connectionString, options => options.MigrationsAssembly(migrationAssembly)));
            builder.AddAspNetIdentity<MyUser>();
            builder.AddProfileService<MyCustomProfileService>();

But now when I navigate to Home page the user claims remain the same and even GetProfileDataAsync method will not hit. 

I appreciate if anyone can tell me what is it like this.

**Comment by brockallen** [comment]
When you use our ASP.NET Identity library, it will register a profile service: https://github.com/IdentityServer/IdentityServer4.AspNetIdentity/blob/dev/src/IdentityServer4.AspNetIdentity/IdentityServerBuilderExtensions.cs#L42

So I'm wondering if you're getting into some DI mixup between our registration and yours?

Also, given that you're using ASP.NET Identity, our design approach here was for you to use the ASP.NET Identity mechanism for creating the claims from the ASP.NET Identity user by registering a `IUserClaimsPrincipalFactory`.

**Comment by mrtaikandi** [comment]
In this case, don't you agree that I should add every additional claims I want to the database (using UserManager) during user's first login?

**Comment by brockallen** [comment]
> In this case, don't you agree that I should add every additional claims I want to the database (using UserManager) during user's first login?

If you want/trust those claims from the external provider, yes.

**Comment by mrtaikandi** [comment]
Assuming a common scenario:

There is a MVC application and a Mobile application and a Web API server that only Mobile app will use.  The users should be able to register/login both by using OAuth 2 connectors (such as Google) and local database (such as AspNetIdentity). 

My understanding is that I have to use Hybrid flow for the IdentityServer, the MVC app should use CookieAuthentication and connect to the IdentityServer using OIDC and Mobile app should use JWT. 
Upon login or registration, the MVC app should redirect the user to the IdentityServer login page (i.e. http://localhost:5000/account/login) and after a successful login the IdentityServer should redirect the user back to the page that the user came from. 

I have configured the MVC app like this: 

    app.UseCookieAuthentication(new CookieAuthenticationOptions
    {
        AuthenticationScheme = "Cookies",
        AutomaticAuthenticate = true,
        ExpireTimeSpan = TimeSpan.FromDays(10)
    });

    JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();

    app.UseOpenIdConnectAuthentication(new OpenIdConnectOptions
    {
        AuthenticationScheme = "oidc",
        SignInScheme = "Cookies",
        Authority = http://localhost:5000,
        RequireHttpsMetadata = false,

        ClientId = "mvc-app",
        ClientSecret = "MVC-APP-SECRET",
                
        // Indicates to use hybrid flow.
        ResponseType = "code id_token",
        Scope =
            {
                OpenId,
                Profile                        
            },

        GetClaimsFromUserInfoEndpoint = true,
        SaveTokens = true,
        TokenValidationParameters = new Microsoft.IdentityModel.Tokens.TokenValidationParameters
        {
            NameClaimType = JwtClaimTypes.Name,
            RoleClaimType = JwtClaimTypes.Role,
        }
    });

This is the code I wrote for Login action in the IdentityServer AccountController:

        [AllowAnonymous]
        [HttpGet("login")]
        public async Task<IActionResult> Login(string returnUrl)
        {
            var vm = await this._accountService.BuildLoginModelAsync(returnUrl);

            if( vm.IsExternalLoginOnly )
            {
                // only one option for logging in
                return this.ExternalLogin(vm.ExternalProviders.First().AuthenticationScheme, returnUrl);
            }

            return this.View(vm);
        }

        [HttpPost("login")]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginInputModel model)
        {
            if( this.ModelState.IsValid )
            {
                var result = await this._signInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberLogin, true);
                if( result.Succeeded )
                {
                    this._logger.LogInformation("Successul login for user '{0}'", model.Email);
                    
                    // Redirect user to the MVC app i.e http://localhost:5001
                    return this.RedirectToLocal(model.ReturnUrl);
                }

                if( result.RequiresTwoFactor )
                    return this.RedirectToAction(nameof(SendCode), new { model.ReturnUrl, RememberMe = model.RememberLogin });

                if( result.IsLockedOut )
                {
                    this._logger.LogWarning("Account is locked out. User '{0}'.", model.Email);
                    return this.View("Lockout");
                }

                this.ModelState.AddModelError(string.Empty, ValidationStrings.InvalidUserNameOrPassword_Error);
                return this.View(await this._accountService.BuildLoginModelAsync(model));
            }

            // If we got this far, something failed, redisplay form
            return this.View(await this._accountService.BuildLoginModelAsync(model));
        }

The user will be redirected to the above action by clicking on a button:
`<a href="http://localhost:5000/account/login>Login</a>`

And when user wants to log out another redirect should happened to the Logout action of IdentityServer AccountController:

`<a href="http://localhost:5000/account/logout>Log Out</a>`        

        [AllowAnonymous]
        [HttpGet("logout")]
        public IActionResult Logout(string logoutId)
        {
            this.ViewData["LogoutId"] = logoutId;
            return this.View();
        }

        [AllowAnonymous]
        [HttpPost("logout")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Logout()
        {
            var model = await this._accountService.BuildLogOutModelAsync((string)this.ViewData["LogoutId"]);
            if( model.TriggerExternalSignout )
            {
                var url = this.Url.Action("Logout", new { logoutId = model.LogoutId });
                try
                {
                    // hack: try/catch NotSupportedException to handle social providers that throw
                    // try/catch InvalidOperationException to handle external providers that don't have signout
                    await this.HttpContext.Authentication.SignOutAsync(model.ExternalAuthenticationScheme, new AuthenticationProperties { RedirectUri = url });
                }
                catch( NotSupportedException ) { }
                catch( InvalidOperationException ) { }

                // this is for Windows/Negotiate
            }

            // delete authentication cookie
            await this._signInManager.SignOutAsync();

            var homeUrl = this._appSettings.HomeRedirectUrl;
            return this.Redirect(homeUrl);
        }

        public async Task<LoggedOutModel> BuildLogOutModelAsync(string logoutId)
        {
            // get context information (client name, post logout redirect URI and iframe for federated signout)
            var logout = await this._interaction.GetLogoutContextAsync(clientId);

            var vm = new LoggedOutModel
            {
                AutomaticRedirectAfterSignOut = AccountOptions.AutomaticRedirectAfterSignOut,
                PostLogoutRedirectUri = logout?.PostLogoutRedirectUri,
                ClientName = logout?.ClientId,
                SignOutIframeUrl = logout?.SignOutIFrameUrl,
                LogoutId = null
            };

            var user = await this._httpContextAccessor.HttpContext.GetIdentityServerUserAsync();
            var idp = user?.FindFirst(JwtClaimTypes.IdentityProvider)?.Value;

            if( idp != null && idp != IdentityServerConstants.LocalIdentityProvider )
            {
                if( vm.LogoutId == null )
                {
                    // if there's no current logout context, we need to create one
                    // this captures necessary info from the current logged in user
                    // before we signout and redirect away to the external IdP for signout
                    vm.LogoutId = await this._interaction.CreateLogoutContextAsync();
                }

                vm.ExternalAuthenticationScheme = idp;
            }

            return vm;
        }

Now, In the IdentityServer app users can successfully login and logout but not in the MVC app.
What did I do wrong here?

**Comment by leastprivilege** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue. 

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support options - visit
https://identityserver.io
