### ISSUE TITLE
front channel SLO

### ISSUE THREAD

**Issue by daver77** [IdentityServer/IdentityServer4.Samples#123]
Hi,

Is there an Id4 sample showing [front channel single logout as mentioned here](https://brockallen.com/2016/02/08/single-sign-out-and-identityserver3/)? 

I can see [this but I believe it's the session management approach](https://github.com/IdentityServer/IdentityServer4.Samples/blob/release/Quickstarts/6_AspNetIdentity/src/IdentityServerWithAspNetIdentity/Views/Account/LoggedOut.cshtml)

**Comment by leastprivilege** [comment]
The `LogoutUrl` client config setting is for the front-channel logout. That's the URL we call during logout.

**Comment by daver77** [comment]
Thanks. Is there a sample project showing it in use?

I presume you get all client's and loop through showing the iframe for each one

**Comment by leastprivilege** [comment]
Yes - check the Samples repo (the clients solution). The MVC clients implement SLO (it is handled by the middleware).
