### ISSUE TITLE
6_AspNetIdentity

### ISSUE THREAD

**Issue by JosefDzeranov** [IdentityServer/IdentityServer4.Samples#124]
In the console application when send login together with the already encrypted password, he can log in and can not send Access token, because it hashes it again. How, then, to send a password to it compared to the pure form.
For example, I write so: 
var disco = await DiscoveryClient.GetAsync("http://localhost:5000");
var tokenClient = new TokenClient(disco.TokenEndpoint, "ro.client", "secret");
var tokenResponse = await tokenClient.RequestResourceOwnerPasswordAsync("myLogin", "AQAAAAEAACcQAAAAEHJxIxZys7na8aPzzHNeSHYLXLUPj7HTXGEc5GNV6Uv2pXndlbCLu8p3KC3ezERsag==", "api1");

            Help me to understand, please)

**Comment by leastprivilege** [comment]
I don't follow, sorry.
