### ISSUE TITLE
Node.js sample

### ISSUE THREAD

**Issue by AlexZeitler** [IdentityServer/IdentityServer4.Samples#125]
Hi folks,
are you interested in a PR with a sample for Node.js API integration (complete setup via Docker Compose)?
It shows how to validate a token via jwks/x5c.

Maybe the validation should become a express middleware or be included / combined with `node-jsonwebtoken` from @auth0.

**Comment by leastprivilege** [comment]
as long as you maintain it - and answer all the questions. sure ;)

**Comment by AlexZeitler** [comment]
As far as I'm able to answer the questions, yes.
Maintaining it is ok for me as well.

**Comment by leastprivilege** [comment]
OK. cool. Then yes.

**Comment by leastprivilege** [comment]
Should I close this?

**Comment by AlexZeitler** [comment]
Depends on where stuff should be discussed: PR (expect it until wednesday) or here.

**Comment by AlexZeitler** [comment]
I won't make it until today evening because yesterday evening the dog ate my homework: I couldn't pull ASP.NET Core Docker images yesterday due to the S3 outages ("Increased Error Rates") - Docker registry seems to storage images on S3.
Next free time slot will be on saturday. The sample in general is up and running but the Docker automation stuff is missing ATM.

**Comment by AlexZeitler** [comment]
I guess it makes sense to upgrade the sample to `1.2.0` ?

**Comment by leastprivilege** [comment]
yes

**Comment by AlexZeitler** [comment]
It's still WIP but ATM I'm receiving a 404 when trying to login using the OIDC JS Client:

This is the logging output from IdSrv:
```
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
      Request starting HTTP/1.1 GET http://192.168.178.64:5000/account/login?returnUrl=%2Fconnect%2Fauthorize%2Flogin%3Fclient_id%3Djs_oidc%26redirect_uri%3Dhttp%253A%252F%252F192.168.178.64%253A5005%252Fcallback.html%26response_type%3Did_token%26scope%3Dopenid%26state%3De76ce18ef49b4ffe98f9f58187d118ec%26nonce%3D8b72a58633e141329301bf8356842070
dbug: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationMiddleware[9]
      AuthenticationScheme: idsrv was not authenticated.
dbug: Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware[4]
      The request path /account/login does not match a supported file type
```

**Comment by AlexZeitler** [comment]
Looks a bit like this: https://github.com/aspnet/Routing/issues/279
And I'm on Kestrel (macOS) as well.

**Comment by AlexZeitler** [comment]
Short update: stuff works now including Docker. Will upgrade to `1.3.1` before sending the PR.

**Comment by AlexZeitler** [comment]
Should I place the sample into a particular folder?

**Comment by brockallen** [comment]
Thanks!

**Comment by omerlh** [comment]
@AlexZeitler I am looking for a full NodeJS solution. So far we had no luck looking for a good OpenID support for `passport`. I take a look at your code, and it looks like it will work - but not sure something we can use in production. For example - look like it will fetch the public key only once, not every 24 hours. Are you using it in your production code?

**Comment by AlexZeitler** [comment]
@omerlh currently it does fetch and set the public key only at service startup. We're currently not using this in production but it is planned to use it (without a estimation when).

If you would like to use [express-oidc-jwks-verify](https://github.com/PDMLab/express-oidc-jwks-verify/blob/master/index.js) as a starting point for the implementation/usage, we're happy to accept pull requests like updating the public key every 24 hours.

**Comment by omerlh** [comment]
Ok, we might give it a try. Didn't noticed you're the author :)
