### ISSUE TITLE
How work with JWT in MVC application where is some javascript part

### ISSUE THREAD

**Issue by Jenan** [IdentityServer/IdentityServer4.Samples#126]
I have MVC application and inside is the React SPA application.
I would like to share the token between MVC part and SPA.

I've used the UseOpenIdConnectAuthentication middleware which store the token inside cookie probable but this cookie is not readable from javascript.

How can I pass the access token from MVC to the SPA? I want to use in SPA this token for calling and API.

Finally I want to store the token in cookie for MVC (it's okay) and for SPA part in localStorage - but I don't know how send from MVC to the SPA.

Thanks for any points.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
