### ISSUE TITLE
7_JavaScriptClient testing URL Scheme in support of iOS.

### ISSUE THREAD

**Issue by aaronralls** [IdentityServer/IdentityServer4.Samples#127]
I'm using the Java Script Client sample and I'm trying to test the use or URL Scheme that iOS requires.

The IdentityModel.OidcClient [sample](https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/blob/master/iOSClient/iOSClient/ViewController.cs) is what I'm trying to test using the oidc-client.js library.

I have my client configured on the IdentityServer4 side and I can connect and login using the oidc-client.js library. The problem I run into is after the consent processing it attempts to do a redirect and fails.

```
`public async Task<IActionResult> Index(ConsentInputModel model)
        {
            var result = await _consent.ProcessConsent(model);

            if (result.IsRedirect)
            {
                return Redirect(result.RedirectUri);
            }
            ...other code...
}`
```

The value of RedirectUri at this section is 
'"/connect/authorize/consent?client_id=MobileApp&redirect_uri=myApp%3A%2F%2Findex.htm%23survey_login_callback ...."'

In IdentityServer the client RedirectUris is
`'RedirectUris = { "myApp://index.htm#survey_login_callback" },'`

**Comment by brockallen** [comment]
Redirect URIs are not supposed to have hash fragments in them.... I don't know if that's what's causing your issue.

**Comment by aaronralls** [comment]
I removed the hash and simplified it to "myApp://index.html" and the redirect after the consent doesn't appear to now how to send back to the original requester when a URL Scheme is used.

**Comment by brockallen** [comment]
> doesn't appear to now how to send back to the original requester

I don't follow

**Comment by aaronralls** [comment]
How does IdentityServer know how to redirect back to a URL scheme like "MyApp://index.html"?

Like this client in the [IdentityModel.OidcClient](https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/blob/master/iOSClient/iOSClient/ViewController.cs)

`var options = new OidcClientOptions
			{
				Authority = "https://demo.identityserver.io",
				ClientId = "native.hybrid",
				Scope = "openid profile email api",
				RedirectUri = "io.identitymodel.native://callback",

				ResponseMode = OidcClientOptions.AuthorizeResponseMode.Redirect
			};

			_client = new OidcClient (options);`

**Comment by brockallen** [comment]
> How does IdentityServer know how to redirect back to a URL scheme like "MyApp://index.html"?

With this config you have: `RedirectUris = { "myApp://index.html" },`

I guess I'm becoming a bit confused on your setup. You have a native client on iOS, but you're using the oidc-client-js library? Sounds like you might be mixing two different tech stacks for the client.

**Comment by aaronralls** [comment]
Yes I'm using the oidc-client.js library to mimic the URL Scheme setup that iOS has to use. 

If we just look at the IdentityModel.OidcClient sample how does the IdentityServer know how to redirect after the consent to the Redirect URI of "io.identitymodel.native://callback"?

**Comment by brockallen** [comment]
> Yes I'm using the oidc-client.js library to mimic the URL Scheme setup that iOS has to use.

I'd suggest looking at the JS-focused samples then. Unless you're doing JS in cordova?

> If we just look at the IdentityModel.OidcClient sample how does the IdentityServer know how to redirect after the consent to the Redirect URI of "io.identitymodel.native://callback"?

Because it's a param in the authorization request (check teh spec for more info) and IdentityServer has a matching config entry for that client.

**Comment by aaronralls** [comment]
I get the configuration for the redirect and I have them set and the client wouldn't be able to connect if they didn't match. 

I'm using the JS in cordova and had the same issues.

IdentityServer sees the param in the authorization request but it doesn't appear to know how to communicate back the the URL Scheme when it's not using HTTP.

(Thank you for all of your time!)

**Comment by brockallen** [comment]
Ok, so now I understand better. It's JS, but cordova, so it is like a native app (and not like a SPA).

I'd suggest looking here for a cordova sample: https://github.com/IdentityModel/oidc-client-js/issues/34

I honestly don't remember if the cordova webview plugin can handle non-http URLs.

**Comment by aaronralls** [comment]
I've tested with both cordova app and SPA with the same result.

How does IdentityServer4 know how to handle a URL Scheme after the ConsentController does a redirect to this uri?
/connect/authorize/consent?...SOME STUFF...redirect_uri=myAPP://index.html&...MORE STUFF..

**Comment by brockallen** [comment]
> How does IdentityServer4 know how to handle a URL Scheme after the ConsentController does a redirect to this uri?

It doesn't -- it just sends a 302 to the URI. The browser/native thing needs to know what to do. On iOS a custom URI scheme has special handling by the OS.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.

**Comment by Neku** [comment]
I have an issue with iOS scheme urls as well: IdentityServer is redirecting with a POST instead of a GET (therefore breaking the Safari switch mechanism). Is the HTTP method configurable?

**Comment by brockallen** [comment]
response_mode
