### ISSUE TITLE
From the MVC.Implicit client, login and logout problem

### ISSUE THREAD

**Issue by tessierp** [IdentityServer/IdentityServer4.Samples#13]
Hi,

I am trying to figure out if this is an issue or not. I tried the sample where I login with bob which works fine and I am able to access the API. After that, I Logout. The SignOutAsync is called. If I try to call the API again, I would have expected the system to ask me for my login information again which it doesn't, it still thinks I am logged in with bob.

There was an issue that was recently closed regarding this. It was closed saying it wasn't an issue. If this really isn't an issue, how to I force a complete signout that enables me to choose another user?

Thanks

**Comment by leastprivilege** [comment]
As stated in a couple of other issues here - the logout endpoint is not implemented yet.

**Comment by theBlueclouds** [comment]
When will the logout feature be implemented?
