### ISSUE TITLE
Impact of ExpireTimespan when in a Hybrid flow? (question)

### ISSUE THREAD

**Issue by pollax** [IdentityServer/IdentityServer4.Samples#131]
I'm wondering about the impact of the ExpireTimespan setting in the MVC example here:
https://github.com/IdentityServer/IdentityServer4.Samples/blob/release/Clients/src/MvcHybrid/Startup.cs#L55
What does this setting actually do? 
(To be clear, the problem is not IdentityServer here but the sample could be a bit misleading.)

I think most readers expect the Cookie expire to be 60 minutes, but it actually seems to be set to session length, not 60 minutes. The result is that if I close my browser and then revisit my MVC site, I'm not cookie authenticated but instead a redirect to IdentityServer happens. 

I stumbled upon this problem with using IdentityServer3 but I think this applies to v4 as well. After some research and trying to find others with the same issue, I found this blog post that explains this in great detail (and how to fix it). http://www.jerriepelser.com/blog/managing-session-lifetime-aspnet-core-oauth-providers/

**Comment by brockallen** [comment]
>  What does this setting actually do?

It controls the cookie lifetime. There's also a sliding setting as well. This is just how the cookie middleware works. I'm missing the point of your question/comment.

**Comment by pollax** [comment]
Suppose I set ExpireTimespan to 7 days. My assumption then is that my MVC application will inspect the cookie and say "yes, you are authenticated" for the next 7 days. So it shouldn't require a round-trip to IdentityServer to authenticate the user.

But for me, my MVC application redirects me to IdentityServer every time my browser session has expired. (And IdentityServer authenticates me and redirects back to the MVC application). So it seems that the ExpireTimespan has no effect.

Am I misunderstanding what effect that setting has? The first part of the blog post I linked explains my question:

> I recently received a support request from a customer regarding the session lifetime once a user has signed in using Auth0 as they wanted the users to remain logged in across browser sessions. For our Auth0 integration with ASP.NET Core we have written no special middleware and instead rely on the standard OpenID Connect or OAuth2 middleware for authenticating users in MVC applications.  

> My initial response to the user was to simply configure the cookie middleware and specify an ExpireTimeSpan:
`app.UseCookieAuthentication(new CookieAuthenticationOptions
    {
        AutomaticAuthenticate = true,
        AutomaticChallenge = true,
        ExpireTimeSpan = TimeSpan.FromDays(7)
    });`

> **Turns out that does not do much. Even when specifying that option the cookie still only remains active for the duration for the session**

**Comment by brockallen** [comment]
> But for me, my MVC application redirects me to IdentityServer every time my browser session has expired. 

If you want a persistent cookie, then you need to set the IsPersistent on the AuthenticationProperties at login time. That's just how the cookie middleware from Microsoft works.

**Comment by pollax** [comment]
Ok, thanks for the clarification. I think I need to look into this a bit more.
To me, the result with or without the ExpireTimespan set in the sample is the same, but I'll let it go for now.
