### ISSUE TITLE
Sample for calling a downstream api

### ISSUE THREAD

**Issue by Franklin89** [IdentityServer/IdentityServer4.Samples#134]
Is there a sample for IdentityServer4 to show how to call a downstream api with user impersonation?

For example:

User signs in in Web front end which then calls Web Api 1 and then Web Api 2 and inside Web Api 2 I would like to know which user just called?

**Comment by leastprivilege** [comment]
See here:

https://identityserver4.readthedocs.io/en/release/topics/extension_grants.html

**Comment by Franklin89** [comment]
thanks for the link, really appreciate your fast response :+1:
