### ISSUE TITLE
How to change AddTestUsers to database stored users in Identity Server4

### ISSUE THREAD

**Issue by ypatil25489** [IdentityServer/IdentityServer4.Samples#135]
I am not able to find out the way change AddTestUsers (in memory users) to database stored users in Identity Server4

**Comment by leastprivilege** [comment]
see here for an example using asp.net identity

https://identityserver4.readthedocs.io/en/release/quickstarts/6_aspnet_identity.html

**Comment by ypatil25489** [comment]
Thanks !!!

I already have database with user table and want to use username and password form that database. So how should I achieve this ?

**Comment by brockallen** [comment]
Use the quickstart UI and customize it as you see fit for validating credentials against your custom DB.

**Comment by ypatil25489** [comment]
Thanks brockallen !!

I guess i need to write lots of code for validating credentials against custom DB.  Is any other solution or approach so that I can implement in one day ? I guess we can easily do it Identity Server 3. Please correct me if I am wrong ? So can switch to identity server 3 instead of 4 ?

Or if possible can you please give me a quick solution like sample code ?

**Comment by leastprivilege** [comment]
User authentication was always custom code - regardless of the IdentityServer version.

If you already have the database, then you also probably have the code to talk to it.
