### ISSUE TITLE
Update to vs 2017 and udape lib

### ISSUE THREAD

**Issue by JanickRoss** [IdentityServer/IdentityServer4.Samples#137]
Do you have a plan to update quick start to the last version of our lib and also to support vs 2017 ?

**Comment by leastprivilege** [comment]
oh yes - we have many plans ;)

**Comment by leastprivilege** [comment]
will work on it this week.

**Comment by JanickRoss** [comment]
Thanks ;)

**Comment by brockallen** [comment]
You can track progress here: https://github.com/IdentityServer/IdentityServer4/issues/916
