### ISSUE TITLE
API calls are valid with expired access token?

### ISSUE THREAD

**Issue by Cybrosys** [IdentityServer/IdentityServer4.Samples#14]
I don't know if I'm missing something but I can call the API even though the access token has expired. I've changed the access token lifetime to 4 seconds for the client I'm using (resource owner client):
AccessTokenLifetime = 4

Shouldn't I get a 401 response from the API?

**Comment by leastprivilege** [comment]
There's a 5 min clock skew tolerance - that's what you are probably seeing.

**Comment by Cybrosys** [comment]
Thank you for the information.

I've tested after waiting for more than 5 minutes. The result is a 500 Internal Server Error being passed to the client.

On the server I see that a System.IdentityModel.Tokens.SecurityTokenExpiredException exception gets thrown. Is it possible for me to hook in somewhere and return a 401 instead of a 500?

[Stack trace.txt](https://github.com/IdentityServer/IdentityServer4.Samples/files/160023/Stack.trace.txt)
