### ISSUE TITLE
Why call a custom /identity endpoint instead of well-known UserInfo?

### ISSUE THREAD

**Issue by nth-commit** [IdentityServer/IdentityServer4.Samples#140]
Hi guys,

I've done a lot of study of OpenID Connect, just starting to integrate it into my pet proj. I'm implementing password flow as a jumping off point and will implement others as necessary.

I've been looking through the samples and have a quick question,

Why is a custom identity endpoint used here?
https://github.com/IdentityServer/IdentityServer4.Samples/blob/release/Quickstarts/2_ResourceOwnerPasswords/src/ResourceOwnerClient/Program.cs

As opposed to UserInfo here?
https://github.com/IdentityServer/IdentityServer4.Samples/blob/release/Clients/src/ConsoleResourceOwnerFlowUserInfo/Program.cs

Also, what server configuration are the samples in Clients4.sln supposed to run against?

Thanks,
Michael

**Comment by brockallen** [comment]
It's a sample showing a web api call using the access token. It's not meant to be a substitute for the user info endpoint.

**Comment by leastprivilege** [comment]
The clients are meant to be run against the main IdentityServer4 repo.
