### ISSUE TITLE
MVCClient calling API returns Error 500 if token is expired

### ISSUE THREAD

**Issue by WolfspiritM** [IdentityServer/IdentityServer4.Samples#141]
I've a setup with microservices similar to the example by microsoft.

I have a MVC Application that is pretty much the same as
https://github.com/dotnet/eShopOnContainers/tree/master/src/Web/WebMVC/
which in return seems to be based on
5_HybridFlowAuthenticationWithApiAccess/src/MvcClient/

It connects to an API Service via HttpClient.

Everything works as expected but after logging in and waiting a few hours (or restarting the IdentityServer with Temporary Signing Credentials) I end up getting a 500 when accessing the Controller of the MVC App which pulls informations from the API as it returns a 401 Unauthorized cause the token is expired.
I'd expect if the token expires or can't be validated anymore that the MVC Client would redirect me back to the Auth Provider instead of allowing the token anyway until the cookie expires.

To me it seems like the MVC Client is not checking the token anymore after initial Authentication.

Any ideas?

This is also tracked here
https://github.com/dotnet/eShopOnContainers/issues/118

**Comment by leastprivilege** [comment]
Try setting a static signing key - e.g. using an x509 cert and see if this changes anything.

**Comment by WolfspiritM** [comment]
Thanks!
I did that already.
This actually fixes the restart problem as the token is still valid afterwards.
However even without static signing key I'd expect the MVC Client to not accept the "invalid" token anymore similar to the API and just redirect back to Identity Server.

The problem with the expired token remains. After the token expired the MVC frontend still accepts the user however passing the access token to the backend results in a 401 causing a 500 in the frontend.

**Comment by leastprivilege** [comment]
I think you are (or they) confusing access token lifetimes and logon sessions.

The MVC app is setting it's own logon session using the cookie. If the access tokens expires, the MVC app needs to get a new one. This would be typically done using a refresh token.

**Comment by leastprivilege** [comment]
I just skimmed the code - there are a couple of things they can improve - they are also on a really old version

<PackageReference Include="IdentityServer4.AspNetIdentity" Version="1.0.0-rc3" />

**Comment by WolfspiritM** [comment]
Thanks for your help :-)
Yes. I didn't confuse the two but I thought that the "UseOpenIdConnectAuthentication" middleware checks the token stored in the auth cookie on every request (and might even request a new access token) but it seems like it's only validating on login. The other requests seem to be handled by the Cookie Middleware which doesn't care about the token at all. Seeing that you can even choose to not store the tokens it actually makes sense now.

So I looked at:
https://github.com/IdentityServer/IdentityServer4.Samples/blob/release/Quickstarts/5_HybridFlowAuthenticationWithApiAccess/src/MvcClient/Controllers/HomeController.cs#L50
Which basicly doesn't do anything different then they do in their example.
It's also why I thought there is no further action needed and the middleware takes care of having a valid token.

So to make this work:
Would the best approach be wrapping the HttpClient into a Service Class and if any call to the API returns 401 use a TokenClient to retrieve a new access token for that user via refresh token before trying the call again and if that fails somehow (expired or invalid refresh token) logging the user out of the "cookies" AuthenticationScheme to force a new login?

Similar to:
https://github.com/IdentityServer/IdentityServer4.Samples/blob/293622b8438d27f4c9c2574e43fe92a22560ac6b/Clients/src/MvcHybrid/Controllers/HomeController.cs#L44

**Comment by leastprivilege** [comment]
Either manually - or maybe give this a try to see if it works for you

https://github.com/IdentityModel/IdentityModel2/blob/dev/src/IdentityModel/Client/RefreshTokenHandler.cs

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by WolfspiritM** [comment]
I didn't get a chance to try this out yet but I think I'm on the right track now and will get this fixed on my end easily now.
Thanks!

I think it would be nice if the MvcClient sample here
https://github.com/IdentityServer/IdentityServer4.Samples/blob/release/Quickstarts/5_HybridFlowAuthenticationWithApiAccess/src/MvcClient/Controllers/HomeController.cs#L50
would deal with expired tokens as an example. It would make it easier for people who are building an application based on that example and end up with error 500 after some time.
