### ISSUE TITLE
How the name (username) information is being passed between the server api and client api?

### ISSUE THREAD

**Issue by jlVidal** [IdentityServer/IdentityServer4.Samples#145]
Looking to the https://github.com/IdentityServer/IdentityServer4.Samples/tree/release/Quickstarts/6_AspNetIdentity example.. Using by http://localhost:5002 (clientId="mvc") perspective. If the name (username) information is not in the JWT token, how the mvc client API knows which username is authenticated to have it in its own claims?

The flow observed is the following below:
* localhost:5002/Home/Secure
* localhost:5000/connect/authorize
* localhost:5002/signin-oidc
* localhost:5002/Home/Secure

I can't see the name (username) anywhere. How that works behind the scenes? How can I added more information there? Also, where can I find the description of the post params: code, id_token, scope, state, session_state?

**Comment by leastprivilege** [comment]
Check the docs - especially on configuring clients and resources.

Also - username is just a detail how the user signed in - the really important claim is `sub` which is the unique user id.

**Comment by grahamehorner** [comment]
@leastprivilege think @jlVidal was wanting to understand how this claim was passed if not in the JWT and where/how this is configured, it is my understanding that the username is mapped by way of the registering a IdentityOptions instance via AspNetIdentity extension method. @leastprivilege can you confirm my understanding is correct?

**Comment by leastprivilege** [comment]
Here's how I would do it:

* Create an identity resource, e.g. *profile* and include the claims (e.g. *username*)
* Make the client request that scope
* Add the username claim to the token inside the profile service

**Comment by grahamehorner** [comment]
Oops forgot that the client needs to request the scope, and be authorised/grant access to the scope in identity server to get the claim 😉

**Comment by jlVidal** [comment]
Got it, I'll try to implement.  Could I add that information in the existent resource? Also can you confirm that is the flow that is happening? The whole IdentityServer seems times seems magic.
![OpenId OAuth flow](https://andrewlock.net/content/images/2016/09/flow.png)

**Comment by leastprivilege** [comment]
IdentityServer is not magic at all - it is just an implementation of the protocols that you don't understand yet ;) But as with all magic, once you know how it works - the magic goes away.

You are missing the login page (authenticate user) and the token endpoint (verify auth_code and send tokens)

**Comment by jlVidal** [comment]
I see what you mean, thanks for the help, each time is getting clear. 

The major point for me is I don't want everything hidden and automatically. A lot of customization are being made because of compatibility with old/legacy authentication systems, session mechanism to be handled, features (swagger), and general structure.  So it's import for my team that those calls and the entire communication between APIs be a little bit more explicit. 

You can close the issue, if desired 👍
