### ISSUE TITLE
/connect/revocation is giving bad request "error": "invalid_client"

### ISSUE THREAD

**Issue by abdulhameed8** [IdentityServer/IdentityServer4.Samples#146]
I getting the issue when I call endpoint /connect/revocation below is my code for client
`
 new Client
            {
                ClientId = "resourceOwner",
                ClientSecrets =
                {
                    new Secret("secret".Sha256())
                },
                AllowedGrantTypes = GrantTypes.ResourceOwnerPassword,
                AllowedScopes =
                {
                    "offline_access",
                    "api1"
                },
                AccessTokenLifetime = 300                
                
            } 
`

In my endpoint call to /connect/revocation I am passing below

Header 

**Content-Type application/x-www-form-urlencoded**
**Authorization Basic 2bb80d537b1da3e38bd30361aa855686bde0eacd7162fef6a25fe97bf527a25b**
 (above is sha256 encocded of clientsecret)

Body
**token  180702c9b8804fbf66eb1d8b629994d3604fc3e3f19e714471f7dfec431fd25a
token_type_hint refresh_token**

where token is the refresh token value which I got when I executed the api /connect/token.

Please support where I am missing anything or doing wrong.

**Comment by brockallen** [comment]
Check your logs.

**Comment by brockallen** [comment]
>  (above is sha256 encocded of clientsecret)

The client must use the plain text secret. #security

**Comment by abdulhameed8** [comment]
Thanks for your prompt reply. 
I am able to solve /connect/revocation call by checking from some sample code and passing below parameters

"token=ReferenceTokenValue&token_type_hint=access_token&client_id=resourceOwner&client_secret=secret"

so the above call is working fine. 

But now I am having issue in calling API it is giving unauthorized error if I pass Reference Token in `**Authorization** header like this "bearer " + referenceTokenValue`

so could you Please tell why I am getting unauthorized error or can you share any sample code on accessing Web API using Reference Token.

**Comment by leastprivilege** [comment]
OK. new issue then.
