### ISSUE TITLE
Calling Web API using Reference Token

### ISSUE THREAD

**Issue by abdulhameed8** [IdentityServer/IdentityServer4.Samples#147]
Can any body tell me how to call web api using Reference Token.

I am using below code if I pass access token type JWT token the below API works fine but if I pass Reference Token  it gave unauthorize 401 error

```
WebClient client = new WebClient();
                client.Headers.Add("content-type", "application/json");                
                client.Headers.Add("Authorization", "bearer " + Session["AccessToken"].ToString());
                try
                {
                    Stream data = client.OpenRead("http://localhost:5001/api/Values/GetPerson");
                    StreamReader reader = new StreamReader(data);
                    string s = reader.ReadToEnd();
                    data.Close();
                    reader.Close();
                    Label1.Text = Label1.Text + "<b>" + s + "</b>";
                }
                catch (Exception ex)
                {
                    Label1.Text = Label1.Text + "<b>" + ex.ToString() + "</b>";
                }
```

**Comment by leastprivilege** [comment]
Which middleware are you using to validate the ref token - how is that setup? What's the logging output?

**Comment by abdulhameed8** [comment]
I am simple ASP.NET Web.API and added Identity Server Relation as below code (**Code 2**), I came to know that token revocation can be done on Reference Type Token not JWT Access Token so I define Token Type as Reference Type in Client Definition but When I used that Reference Token type to Call API method it gave me unauthorized error  the sample code to call Web api is below **Code 1**

Please suggest me where I am doing wrong.

I want to make simple web api accessible web application using Token service of Identity Server and when I logout from my web application the token should not be accessible or the API should not be accessible using that revoke token. 

**Code 1**
 WebClient client = new WebClient();
                client.Headers.Add("content-type", "application/json");
                //client.Headers.Add("Authorization", "bearer " + Session["AccessToken"].ToString());
                client.Headers.Add("Authorization",  Session["AccessToken"].ToString());
                try
                {
                    Stream data = client.OpenRead("http://localhost:5001/api/Values/Get/1");
                    StreamReader reader = new StreamReader(data);
                    string s = reader.ReadToEnd();
                    data.Close();
                    reader.Close();
                    Label1.Text = Label1.Text + "<b>" + s + "</b>";
                }
                catch (Exception ex)
                {
                    Label1.Text = Label1.Text + "<b>" + ex.ToString() + "</b>";
                } 


**Code 2**
 ```
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            loggerFactory.AddConsole(Configuration.GetSection("Logging"));
            loggerFactory.AddDebug();

            app.UseApplicationInsightsRequestTelemetry();

            app.UseApplicationInsightsExceptionTelemetry();

            app.UseIdentityServerAuthentication(new IdentityServerAuthenticationOptions
            {
                Authority = "http://localhost:5000",
                ScopeName = "api1",
                RequireHttpsMetadata = false,
                ScopeSecret = "secret",
                AutomaticAuthenticate = true,
                AutomaticChallenge = true

            });

            app.UseMvc();
        }
```

**Comment by leastprivilege** [comment]
enable logging to see whats going on.

**Comment by mbarqawi** [comment]
@leastprivilege , Do you have any sample or documentation link about the middleware that validates the ref token

**Comment by leastprivilege** [comment]
Sure - it's in our docs.

https://identityserver4.readthedocs.io/en/release/topics/apis.html
