### ISSUE TITLE
Can't clone on Windows

### ISSUE THREAD

**Issue by leechen** [IdentityServer/IdentityServer4.Samples#148]
Here is what I got. Seems like filename too long is the issue?

$ git clone https://github.com/IdentityServer/IdentityServer4.Samples.git
Cloning into 'IdentityServer4.Samples'...
remote: Counting objects: 3802, done.
remote: Compressing objects: 100% (29/29), done.
remote: Total 3802 (delta 9), reused 0 (delta 0), pack-reused 3773
Receiving objects: 100% (3802/3802), 6.41 MiB | 12.48 MiB/s, done.
Resolving deltas: 100% (2511/2511), done.
error: unable to create file Quickstarts/8_EntityFrameworkStorage/src/QuickstartIdentityServer/Data/Migrations/Id       entityServer/ConfigurationDb/20170319194441_InitialIdentityServerConfigurationDbMigration.Designer.cs: Filename too long
error: unable to create file Quickstarts/8_EntityFrameworkStorage/src/QuickstartIdentityServer/Data/Migrations/Id       entityServer/PersistedGrantDb/20170319194432_InitialIdentityServerPersistedGrantDbMigration.Designer.cs: Filename        too long
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'

**Comment by leastprivilege** [comment]
is this resolved?

**Comment by leechen** [comment]
No, the same error. I end up download the zip.

**Comment by leastprivilege** [comment]
you probably hit MAX_PATH on Windows
