### ISSUE TITLE
Error when loading IdentityProject

### ISSUE THREAD

**Issue by Keithleo9008** [IdentityServer/IdentityServer4.Samples#149]
Hi Guys,

i replicated the steps for the Identity server  using EF for the configuration data as well as Identity but when i try load the project to create my first user or view the index page i get the following error:

> An unhandled exception occurred while processing the request.
> 
> NullReferenceException: Object reference not set to an instance of an object.
> AuthenticateAsync

and on the console debug session:

> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
>       Request finished in 204.2464ms 500 text/html; charset=utf-8
> info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]
>       Request starting HTTP/1.1 GET http://localhost:5000/
> fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[0]
>       An unhandled exception has occurred while executing the request
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at IdentityServer4.Hosting.AuthenticationHandler.AuthenticateAsync(AuthenticateContext context)
>    at Microsoft.AspNetCore.Http.Authentication.Internal.DefaultAuthenticationManager.<GetAuthenticateInfoAsync>d__12.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at IdentityServer4.Extensions.HttpContextExtensions.<GetIdentityServerUserInfoAsync>d__8.MoveNext()

Could anyone maybe point me in the right direction? 

At which point is  IdentityServer4.Hosting.AuthenticationHandler.AuthenticateAsync(AuthenticateContext context) called?

i noticed that if i replace "app.UseIdentityServer();" with "app.UseIdentity();" this error does not appear???

**Comment by leastprivilege** [comment]
is this resolved?
