### ISSUE TITLE
Client stays logged in after clicking logout until browser closed

### ISSUE THREAD

**Issue by muqeet-khan** [IdentityServer/IdentityServer4.Samples#15]
I am new to identity server and OAuth flows so this question might be a standard implementation of an implicit flow, but:

1. I am running the MVC sample and I notice the client is logged in even after clicking the logout nav link and can access secure section of the program without re-authenticating until the browser window is closed. 
2. The home page shows the user as "not logged in" after logout but navigating to secure section and navigating back to home controller the user is now logged back in without re-authentication. 
3. Once the browser windows is closed and reopened MVC site correctly asks for uname and pwd as it should. 

Shouldn't it do the same once the user has clicked on log out but hasn't closed the browser window?

**Comment by leastprivilege** [comment]
This has been discussed **several** times here already - the logout endpoint is not implemented yet. Expect updates around the RC2 release of asp.net core timeframe.
