### ISSUE TITLE
JWT in Hybrid sample

### ISSUE THREAD

**Issue by siberianguy** [IdentityServer/IdentityServer4.Samples#150]
I'm looking into Hybrid sample and can't wrap my head around how to return a token to my client after successful authorization. What I see in the sample in case of successful login, request is just redirected. So I guess I need to make a separate request to get a token?

**Comment by siberianguy** [comment]
Is there any sample with IdentityServer4 in Hybrid mode (preferably) integrated in Web Api environment (instead of MVC). There're so many things floating around and it's hard to implement based on openid specification without real code in front of you.

**Comment by leastprivilege** [comment]
Hybrid mode is totally unrelated to web apis - it is about how a client requests tokens - not how an API consumes them.

I think you need to learn more about the protocol to actually know your question ;)

**Comment by siberianguy** [comment]
You're right. I do seem a little bit lost, but you pointed my in the right direction - thank you. I will improve my knowledge on the topic and may be come back with a more specific question.
