### ISSUE TITLE
provide password for TestUser accounts

### ISSUE THREAD

**Issue by swseverance** [IdentityServer/IdentityServer4.Samples#152]
Please consider updating the [NodeJsApi README](https://github.com/IdentityServer/IdentityServer4.Samples/blob/release/NodeJsApi/readme.md) to mention that the password for user "alice" is "password", or indicate that the password can be found in /NodeJsApi/src/QuickstartIdentityServer/Config.cs

Thanks

**Comment by leastprivilege** [comment]
@AlexZeitler
