### ISSUE TITLE
NodeJsApi invalid_scope api2.read_only

### ISSUE THREAD

**Issue by swseverance** [IdentityServer/IdentityServer4.Samples#153]
the scope **api2.read_only** is referenced in two files:
/NodeJsApi/src/Client/static/app.js (line 16)
/NodeJsApi/src/Client/static/index.html (line 24)

**api2.read_only** does not appear to be one of the allowed scopes in:
/NodeJsApi/src/QuickstartIdentityServer/Config.cs

When a request is made that contains the **api2.read_only** scope the server logs the following error:

identityserver    | fail: IdentityServer4.Validation.ScopeValidator[0]
identityserver    |       Invalid scope: **api2.read_only**
identityserver    | fail: IdentityServer4.Endpoints.AuthorizeEndpoint[0]
identityserver    |       Request validation failed

Thanks!

**Comment by leastprivilege** [comment]
@AlexZeitler
