### ISSUE TITLE
error CS0579 when attempting to build ClientCredentials quickstart solution (release branch)

### ISSUE THREAD

**Issue by osudude** [IdentityServer/IdentityServer4.Samples#157]
Restoring NuGet packages...
To prevent NuGet from restoring packages during build, open the Visual Studio Options dialog, click on the Package Manager node and uncheck 'Allow NuGet to download missing packages during build.'
1>------ Rebuild All started: Project: QuickstartIdentityServer, Configuration: Debug Any CPU ------
2>------ Rebuild All started: Project: Api, Configuration: Debug Any CPU ------
3>------ Rebuild All started: Project: Client, Configuration: Debug Any CPU ------
3>obj\Debug\netcoreapp1.1\Client.AssemblyInfo.cs(14,12,14,54): error CS0579: Duplicate 'System.Reflection.AssemblyCompanyAttribute' attribute
3>obj\Debug\netcoreapp1.1\Client.AssemblyInfo.cs(15,12,15,60): error CS0579: Duplicate 'System.Reflection.AssemblyConfigurationAttribute' attribute
3>obj\Debug\netcoreapp1.1\Client.AssemblyInfo.cs(19,12,19,54): error CS0579: Duplicate 'System.Reflection.AssemblyProductAttribute' attribute
3>Done building project "Client.csproj" -- FAILED.
1>QuickstartIdentityServer -> C:\Dev\Github\IdentityServer\IdentityServer4.Samples\Quickstarts\1_ClientCredentials\src\QuickstartIdentityServer\bin\Debug\netcoreapp1.1\QuickstartIdentityServer.dll
2>Api -> C:\Dev\Github\IdentityServer\IdentityServer4.Samples\Quickstarts\1_ClientCredentials\src\Api\bin\Debug\netcoreapp1.1\Api.dll
========== Rebuild All: 2 succeeded, 1 failed, 0 skipped ==========

Not sure what I am doing wrong, please advise.

VisualStudio.15.Release/15.1.0+26403.7
Microsoft .NET Framework
Version 4.7.02046

Installed Version: Community

Visual Basic 2017   00369-60000-00001-AA478
Microsoft Visual Basic 2017

Visual C# 2017   00369-60000-00001-AA478
Microsoft Visual C# 2017

Visual C++ 2017   00369-60000-00001-AA478
Microsoft Visual C++ 2017

Application Insights Tools for Visual Studio Package   8.6.00209.10
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.30320.0
ASP.NET and Web Tools 2017

ASP.NET Web Frameworks and Tools 2017   5.2.50303.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.30209.0
Azure App Service Tools v3.0.0

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.2.5000.0
Microsoft Azure Data Lake Tools for Visual Studio

Common Azure Tools   1.9
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Fabric.DiagnosticEvents   1.0
Fabric Diagnostic Events

GitHub.VisualStudio   2.2.0.8
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

KofePackagePackage Extension   1.0
KofePackagePackage Visual Studio Extension Detailed Info

Microsoft Azure Hive Query Language Service   2.2.5000.0
Language service for Hive query

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2017 - v2.9.50131.1

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Node.js Tools   1.3.50316.00
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   4.1.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

SQL Server Data Tools   15.1.61702.140
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript   2.1.5.0
TypeScript tools for Visual Studio

Visual C++ for Linux Development   1.0.6
Visual C++ for Linux Development

Visual Studio tools for CMake   1.0
Visual Studio tools for CMake

**Comment by leastprivilege** [comment]
is this resolved?

**Comment by osudude** [comment]
Seems like it builds in VS2015 ok but not VS2017.

**Comment by leastprivilege** [comment]
then you need to clone the latest version. It is VS2017 only.

**Comment by martgut** [comment]
I'm still running in the same problem, using latest VS2017? So this issue does not seem resolved.

**Comment by leastprivilege** [comment]
I can't reproduce it.
