### ISSUE TITLE
Authorization failed for user: (null)

### ISSUE THREAD

**Issue by xGabba** [IdentityServer/IdentityServer4.Samples#158]
I cloned the samples repository and set up the `Quickstarts/6_AspNetIdentity` solution.
The first time everything worked well and I exchanged the EFCore framework with a MongoDb provider. Still everything works.
After I deleted the whole repository and setup a new, cleaner version within the MongoDb provider, I got the problem that at the `Consent` page I dont get redirect to the _MvcClient_. 

Most time I run the projects with "Shift + F5" and test it in usual Google Chrome.
I found out, that if I run the same _MvcClient_ project with F5 with the Debug Google Chrome it works. Also with Internet Explorer or MS Edge and _MvcClient_ in combination with "Shift + F5".

So any old data from the usual Google Chrome disturbs the authentication/authorization process. On the _IdentityServer_ each authentication request suceed.

The output of the _MvcClient_ console:

`
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[1]  
      Request starting HTTP/1.1 GET http://localhost:5002/Home/Secure  
info: Microsoft.AspNetCore.Authorization.DefaultAuthorizationService[2]  
      Authorization failed for user: (null).
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]     
      Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter'.
info: Microsoft.AspNetCore.Mvc.ChallengeResult[1]
      Executing ChallengeResult with authentication schemes ().
info: Microsoft.AspNetCore.Authentication.OpenIdConnect.OpenIdConnectMiddleware[12]
      AuthenticationScheme: oidc was challenged.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action MvcClient.Controllers.HomeController.Secure (MvcClient) in 1.6528ms
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 3.2216ms 302
`

**Comment by brockallen** [comment]
Perhaps you had a cookie with an old sub, and when you changed DBs the user's sub doesn't exist in the new/clean/empty DB? Anyway, not sure. Any update on this?

**Comment by xGabba** [comment]
A bit.
I recognized that if I try to run the app from the pc at home, I still have this issue. But this behave comes from that my chrome account shares the user informations. As soon as I use another browser or account it works.
I makes absolute no different if I use a complete new DB.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.

**Comment by nukec** [comment]
@xGabba you ever resolved this?

**Comment by xGabba** [comment]
@nukec I'm not absolutely sure, but I guess the problem was like @brockallen suggested, because of the cookies.
I added to the _Mvc_ project a automatic cookie refresh mechanism, which checks if the cookie is expired or not. If true, a new access_token with th refresh_token will be requested.

Take a look here.

<script src="https://gist.github.com/xGabba/b18669ce23a2739cd2d1de00c95ef7dd.js"></script>
