### ISSUE TITLE
MongoDb Quickstarter 

### ISSUE THREAD

**Issue by BoasE** [IdentityServer/IdentityServer4.Samples#161]
Not sure if this is the right place to post but i try :)

It would be nice to get a quickstart example working with mongodb instead of entityframework.
also including the integration the asp core user storage with mongodb.

I know that this could be done when looking through the EntityFrameworkSample. but this includes some EntityFramework Specifics you don't have for other databases like mongodb.

For example adding db contextes and so on.

So it would be very nice to have such a plain quickstarter without EntityFramework and SQL Server dependencies. Imo preferable mongodb.

**Comment by Rilton** [comment]
Take a look into this one: https://github.com/Rilton/IdentityServer4.Samples.Mongo
I tried to perform a pull request from this repo a few weeks ago, but they decided not to accept it because they were concerned about future maintenance and support. Mongoldb is  outside their core expertise.

**Comment by leastprivilege** [comment]
What I suggested is to produce a walkthrough that we can link to from our documentation. I am still interested in doing that.

**Comment by Rilton** [comment]
@leastprivilege sorry for misunderstanding.
When you say "walkthrough" do you mean a readme? Would you mind to elaborate?

**Comment by Gentlehag** [comment]
I think a important part is that there are 2 components a developer would need.

on the one hand it is implementing the identityserver 4 contracts with mongodb like `IPersistedGrantStore`
and on the other hand the asp.net identity part like User and RoleStore.

Thats also a thing that i'm missing in the identity4 documenation in general. As I Understand it, starting with identityerver 4 it doesn't make any storage of the user by it self its just using the identity signin pipeline on which we can use usermanager and so on

**Comment by Rilton** [comment]
That's was "kind" the approach:

- PersistedGrantStore: https://github.com/Rilton/IdentityServer4.Samples.Mongo/blob/dd2fc4f2e9d375c941db5c6042e1e2132ac8209c/9_MongoRepository/src/QuickstartIdentityServer/Startup.cs

- asp.net identity part, must be based on IdentityServer4.Stores.IClientStore: https://github.com/Rilton/IdentityServer4.Samples.Mongo/blob/dd2fc4f2e9d375c941db5c6042e1e2132ac8209c/9_MongoRepository/src/QuickstartIdentityServer/Quickstart/Account/AccountController.cs

**Comment by Gentlehag** [comment]
according to the second point, why is the clientstore passed in the account controller, it isn't used, is it?

**Comment by Rilton** [comment]
@gentletag 
I will only be able to check you comments tonight, but please feel free fix anything! That's the open source main idea!

**Comment by Rilton** [comment]
@Gentlehag 

It's my understanding that IClientStore interface is used by the IdentityServer framework internally  to find an user by ClientId - "FindClientByIdAsync method", see IdentityServer4.Stores.IClientStore code - therefore any user store should  implement it.

Regarding IUserSTore and IRolestore it should be fine.   It seems to me that the "CusttomClientStore.cs" could easily implement  "IUserSTore". In a quick glance at  [IUserStore.cs](https://github.com/aspnet/Identity/blob/5480aa182bad3fb3b729a0169d0462873331e306/src/Microsoft.AspNetCore.Identity/IUserStore.cs) source code  I noticed that it contains a similar  FindClientByIdAsync method -  signature differs IdentityServer4.Stores.IClientStore FindClientByIdAsync method

Thanks for your comments regarding the walkthrough I will take a look into those and should update the readme in the next couple of days. In this mean time keep in mind that the  mongodb sample was based in the IdentityServer4.samples "Quickstart #8: EntityFramework configuration", hence  most of the code is identical, except parts related to Repository / mongoDB - bulk of the "magic" takes place at  [IdentityServerBuilderExtensions.cs](https://github.com/Rilton/IdentityServer4.Samples.Mongo/blob/dd2fc4f2e9d375c941db5c6042e1e2132ac8209c/9_MongoRepository/src/QuickstartIdentityServer/Quickstart/Extension/IdentityServerBuilderExtensions.cs)

BTW  I took the opportunity to upgrade the project to VS 2017, update IdentityServer4 version and other nuggets.

**Comment by Rilton** [comment]
@gentlehag. In order to make things easier / quick I've just added you as contributer to  the mongodb sample repo.

**Comment by Gentlehag** [comment]
Afaik IClientStore  just handles the persistance of the configured clients not the users. See screenshot for contents that was stored in a quicktest i did 
![image](https://cloud.githubusercontent.com/assets/4619513/25983294/24d0ae3a-36e4-11e7-8539-e53e7c838b0d.png)

For really storing users and roles the asp identity storage must be implemented. To have all in one place i would recommend to also implemented it in the sample repository. maybe i find some time on the weekend for this :)

**Comment by leastprivilege** [comment]
@rilton Our plan was to add a another quickstart document to the docs that points to community provided quickstarts.

IOW - can you provide a document that walks the user through all the steps to use MongoDb with IdentityServer (can be a md file in your repo)? If yes I will add that to the docs.

It would be nice if this has a "step by step" character like our quickstarts do.

**Comment by Gentlehag** [comment]
@Rilton  i made a basic implementation, but i got a but somewhere which i can't find-. i get authenticatd and user persisted but the redirect to the auhtorize controller doesn't work anymore.

Maybe you can have a look at it? https://github.com/Rilton/IdentityServer4.Samples.Mongo/pull/1

@leastprivilege maybe you have a hint what to look at?

**Comment by Gentlehag** [comment]
@Rilton  did it now and it seems to work. 

When having custom identity storage it is also required that a Profile service is registered

**Comment by Rilton** [comment]
@gentletag great work!
I added some logging capability and will take a look over the weekend

**Comment by Gentlehag** [comment]
can you write a walktrough ? maybe here in the wiki so that this can be linked ? i could also contribute or make suggestions if you like

**Comment by Gentlehag** [comment]
ps: i merged the pull request in your repo as i assume it was also working for you :)

**Comment by Gentlehag** [comment]
looks good. btw yes the implementation is looking in the database.  the test user could be removed or in startup you make some kind of "ensure test user method" which checks with the usermanager if they exist and if not it creates them similar to the code in the account controller

**Comment by Gentlehag** [comment]
@Rilton  did you start with the guide based on the code i distributed?

**Comment by Rilton** [comment]
@Gentlehag I started reviewing/refactoring the code changes you made - nothing major - I should complete it tonight.
Unfortunately I was NOT able to start with the walkthrough - busy weekend...anyway, based on the current IdentityServer4.Samples and @leastprivilege comments it seems to me we should stick with README.MD file, probably expand/review the existing readme.

**Comment by Rilton** [comment]
@Gentlehag I performed  some refactor related work related to  DI and IdentityServerBuilderExtensions in order to bring the code more inline to Asp .NET Core  approach - Nothing major, but  it required sometime to put everything together happily.

On the other hand the current  AccountController (and other authentication related code)  require some "love". We have to add some functionality to automatically load MongoDB with the same Test Users used others IdentityServer4.Samples (e.g. Alice & Bob) in order to keep consistency and probably implement "IdentityServer4.Validation.IResourceOwnerPasswordValidator". 

Based on that I am planning to focus on authentication / AccountController in the next couple of days before jumping into  the Walkthrough. I will keep you guys posted.

**Comment by leastprivilege** [comment]
I don't follow this thread - ping me when you have something that should be linked from our docs.

**Comment by Rilton** [comment]
@leastprivilege all done. 
Please let us know if it is clear and / or wish any adjustment.
You can find the repo at https://github.com/Rilton/IdentityServer4.Samples.Mongo 

Note: In order to keep it simple for the majority of users we created 02 samples:
1)  IdentityServer4-mongo: a simple IdentityServer4 sample similar to IdentityServer4.quickstart.sample.s
2) IdentityServer4-mongo-AspIdentity: Sample based on IdentityServer4 and Asp Identity

**Comment by leastprivilege** [comment]
I personally think that your step-by-step walkthrough needs more hand holding. Just like ours do. Add more prose and maybe before/after solutions etc.

Enrich it a bit more and I will add it to the "community quickstarts".

**Comment by Rilton** [comment]
@leastprivilege thanks for your straightforward feedback. Truly appreciated that. 
I will work on that and get back to you

**Comment by xGabba** [comment]
I have a working solution in which im using a Identityserver4 with Identity and MongoDb.
For this I started with [this](https://github.com/IdentityServer/IdentityServer4.Samples/tree/dev/Quickstarts/6_AspNetIdentity), installed [this](https://www.nuget.org/packages/Microsoft.AspNetCore.Identity.MongoDB/1.0.2/) and changed [this](https://github.com/IdentityServer/IdentityServer4.Samples/blob/dev/Quickstarts/6_AspNetIdentity/src/IdentityServerWithAspNetIdentity/Startup.cs#L36) line with:
`            services.AddIdentityWithMongoStoresUsingCustomTypes<ApplicationUser, ApplicationRole>(Configuration
                                                                                                      .GetConnectionString("DefaultConnection"))
                    .AddDefaultTokenProviders();`

`<ApplicationUser, ApplicationRole>` are the custom User and Role classes. If you don't need this you can use the standard function.

In your _appsettings.json_ you need to put the connection string in:
`,
  "ConnectionStrings": {
    "DefaultConnection": "mongodb://localhost/dbname"
  }`

**Comment by Gentlehag** [comment]
@rilton any news?

**Comment by leastprivilege** [comment]
Here's the section

https://identityserver4.readthedocs.io/en/release/quickstarts/community.html

waiting for your content.

**Comment by Rilton** [comment]
Thanks I will look into that and get back to you

**Comment by Alpha-Centauri-A** [comment]
@BoasE  It is not clear to me how we could use something like "[BsonIgnore]", due to the fact that all models are part of the "IdentityServer4.Models" (IdentityServer4 libraries). 
Hence we have to use something like "BsonClassMap.RegisterClassMap<T>" for each model class to instruct MongoDB driver to ignore "_Id" (automatically created by MongoDB) when deserializing, but due to MongoDB driver limitations a "restart" is required...
I do not see this as a big deal because this "restart" is only required during the "very first" execution when the MONGODB does NOT exist yet. The app will create mongoDB database/collections during that "first execution"

**Comment by BoasE** [comment]
The Trick is That you implement Custom classes that you annotate the.  I made this in a project Maybe Ivan abstract it for here in the next week

Von meinem iPhone gesendet

Am 16.07.2017 um 00:00 schrieb rkj <notifications@github.com<mailto:notifications@github.com>>:


@BoasE<https://github.com/boase> It is not clear to me how we could use something like "[BsonIgnore]", due to the fact that all models are part of the "IdentityServer4.Models" (IdentityServer4 libraries).
Hence we have to use something like "BsonClassMap.RegisterClassMap" for each model class to instruct MongoDB driver to ignore "_Id" (automatically created by MongoDB) when deserializing, but due to MongoDB driver limitations a "restart" is required...
I do not see this as a big deal because this "restart" is only required during the "very first" execution when the MONGODB does NOT exist yet. The app will create mongoDB database/collections during that "first execution"

**Comment by souzartn** [comment]
@leastprivilege  sorry my delay, things have been hectic at work.
I just submitted a pull request to DEV with related modifications to https://identityserver4.readthedocs.io/en/release/quickstarts/community.html
