### ISSUE TITLE
info = await _signInManager.GetExternalLoginInfoAsync(); returns null no matter what.

### ISSUE THREAD

**Issue by nigel-dewar** [IdentityServer/IdentityServer4.Samples#168]
Hi There,

I've read similar issues on this issue, and have read through https://github.com/IdentityServer/IdentityServer4/issues/453 and tried all the suggestions but to no avail.

For context here is what I am using. VS 2017, with a target core framework of 1.1.1, using asp.net Identity. Libs:

IdentityServer4.AspNetIdentity v 1.0.1
IdentityServer4 v1.5.0
Microsoft.AspNetCore.Authentication.Cookies v 1.1.1
Microsoft.AspNetCore.Authentication.OpenIdConnect v 1.1.1

I have my startup OpenIdConnect Auth setup like so

```
app.UseOpenIdConnectAuthentication(new OpenIdConnectOptions
            {
                //AutomaticAuthenticate = true,
                //AutomaticChallenge = true,
                AuthenticationScheme = "OpenIdConnect",
                RequireHttpsMetadata = false,
                ClientId = _appSettings.ClientId,
                ClientSecret = _appSettings.ClientSecret,
                DisplayName = "OpenIdConnect",
                SignInScheme = "Identity.External",
                PostLogoutRedirectUri = "http://localhost:44305",
                Authority = "https://login.microsoftonline.com/common",
                ResponseType = OpenIdConnectResponseType.CodeIdToken,
                TokenValidationParameters = new TokenValidationParameters
                {
                    ValidateIssuer = false
                },
                SaveTokens = true,
                Events = new CustomAuthenticationEvents(
                    loggerFactory,
                    usermanager,
                    signInManager,
                    distributedCache,
                    dataProtectionProvider,
                    appSettings)
            });
```

As you can see I'm doing a multitenant signin for Azure AD.

If I go through the normal sign in process using the Account controller the ExternalLoginCallback function works and _signInManager.GetExternalLoginInfoAsync() get the right info.

I have a Tenant Signup process which uses a slightly different process than the Default ExternalLogin function in the AccountController. It looks like so

```
public IActionResult SignUp()
        {
        
            HttpContext.Items.Add("signup", "true");

            var state = new Dictionary<string, string> { { "signup", "true" } };

            var redirectUrl = Url.Action(nameof(SignUpCallback), "Account");

            var provider = "OpenIdConnect";

            var properties = _signInManager.ConfigureExternalAuthenticationProperties(provider, redirectUrl);

            var props = new AuthenticationProperties(state)
            {
                RedirectUri = redirectUrl,
                Items = { { "scheme", provider } }
            };

            return new ChallengeResult(provider, props);

        }
```

However in my OpenIdConnect Events class, the "Events = new CustomAuthenticationEvents(" I am trying to process these events so I can 'sign up' a tenant and create a new user for this tenant.

I have this function
```
private async Task CreateOrUpdateUserAsync(AuthenticationTicket authenticationTicket, Tenant tenant)
        {
               // This simply will not work !!! - tried everything
            ExternalLoginInfo info = await _signInManager.GetExternalLoginInfoAsync();
        }
```
But this little guy returns null all the time, and I have tried everything to figure out why.

So I have tried doing this, setting the cookie auth to use the same as IdentityServer

```
 app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationScheme = "Identity.External",
                AutomaticAuthenticate = false,
                AutomaticChallenge = false
            });
```
Where UseOpenIdConnectAuthentication is

```
               AuthenticationScheme = "OpenIdConnect",
                RequireHttpsMetadata = false,
                ClientId = _appSettings.ClientId,
                ClientSecret = _appSettings.ClientSecret,
                DisplayName = "OpenIdConnect",
               // SignInScheme = "Identity.External",
                SignInScheme = "Identity.External",
```

But to no avail.

Is there some kind of cookie mismatch that I am doing. As said, once OpenIdConnect has done its thing and returns back to the Account Controllers ExternalLoginCallback function I can get the providers info, 

But for some reason in the OIDC Events I cannot. 

The only thing I am doing at this stage is a workaround like so
```
ExternalLoginInfo info = new ExternalLoginInfo(
            principal,
            "Microsoft",
            principal.Claims.Where(x => x.Type == "http://schemas.microsoft.com/identity/claims/objectidentifier").FirstOrDefault().Value.ToString(),
           "Microsoft");
```

But it doesnt really work that well, as when I go through normal signin process which uses the default Account Controller ExternalLogin process, I get different information than what I do using the workaround shown above.

Can anybody please shed some light on this? And if I'm doing things the plain dumb way then of course, 'let me have it', I know I deserve it.

Cheers

**Comment by brockallen** [comment]
I'd suggest getting an ASP.NET Identity project working in isolation first. That way you can debug the external cookie issue independent from IdentityServer. Also, does the ASP.NET Identity quickstart sample code work for you?

**Comment by brockallen** [comment]
Any update?

**Comment by nigel-dewar** [comment]
Hi Brock, Sorry on the delay, yes you are correct, all works sweet with 07_JS quickstart.

Thank you so much for testing this. Apologies for the muck around.
