### ISSUE TITLE
Bad Request - Request Too Long

### ISSUE THREAD

**Issue by timscriv** [IdentityServer/IdentityServer4.Samples#17]
I am having this issue on IdentityServer3 and IdentityServer4. When using Chrome this seems to pop up quite a bit. The best way to reproduce is by continually opening new tabs(takes quite a few 10-20 tabs) but then this error pops up. I have seen several other issues about this but none seem to solve the issue and the ClearOverflow is not actually clearing any of the Nonce cookies.

I cloned the Samples and ran the MVC project to create this error.

![badrequest](https://cloud.githubusercontent.com/assets/5459582/14083398/1c11e8d2-f4db-11e5-898e-1fa521a49fc4.PNG)

**Comment by leastprivilege** [comment]
That's the nonce cookie of the Microsoft middleware. Not an idsrv issue.
