### ISSUE TITLE
Access token expired returns 404 NotFound instead of 401 Unauthorized

### ISSUE THREAD

**Issue by xGabba** [IdentityServer/IdentityServer4.Samples#171]
I have the following Setup: 

- Identityserver4: Authorization server
- ASP.NET Core WebAPI: Secured by Identityserver4. 
- ASP.NET Core MVC: Secured by Identityserver4. Access WebAPI with the access-token from the mvc-hybrid client.

To refresh the token I'm asking for 401 status code and with the 404 it is not working. I don't want to change the status code to 404, because 401 is the right one and 404 has another meaning.

When I try to make a request to an authorized endpoint with an expired access token at the WebApi, I get this 404 status code.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.

**Comment by sandrose48** [comment]
I am having the same issue. any work around?

**Comment by weitzhandler** [comment]
I am having the same issue.
Looking at the `HttpResponseMessage` details, I see it's attempting to request `http://localhost:12345/Account/Login?ReturnUrl=%2Fapi%2FLists%2Fquery`, which doesn't exist.

What do I have to change so that there is no Login redirection but instead a 401 result?

**Comment by weitzhandler** [comment]
@leastprivilege 
I am having the same issue.
Looking at the `HttpResponseMessage` details, I see it's attempting to request `http://localhost:12345/Account/Login?ReturnUrl=%2Fapi%2FLists%2Fquery`, which doesn't exist, and is not supposed to.

What do I have to change so that there is no Login redirection but instead a 401 result?

**Comment by xGabba** [comment]
I‘m currently working on another project so I don’t know the solution. But check this: https://github.com/aspnet/Security/issues/292

**Comment by weitzhandler** [comment]
It used to work well.
Once I upgraded to the new version the issue started to occur.
I checked out that link, I'm unable to find `LoginPath` in ASP.NET Core 2.0.

The following configuration causes an `InvalidOperationException` saying _LoginUrl is not configured_.

**Comment by weitzhandler** [comment]
After reading https://github.com/aspnet/Identity/issues/1175 I tried adding: 

      services.ConfigureExternalCookie(cao => cao.LoginPath = PathString.Empty);
      services.ConfigureApplicationCookie(cao => cao.LoginPath = PathString.Empty);

But I'm still getting 404 instead of 401.

**Comment by weitzhandler** [comment]
After so much digging, [this](https://github.com/IdentityServer/IdentityServer4.AccessTokenValidation/issues/72#issuecomment-328373892) solved the issue for me.

We have to explicitly specify the authentication scheme as follows:

    [Authorize(AuthenticationSchemes = IdentityServerAuthenticationDefaults.AuthenticationScheme]

**Comment by xGabba** [comment]
Perfect. Thank you for replying the solution!

**Comment by sandrose48** [comment]
thank you @weitzhandler for the solution
