### ISSUE TITLE
Unable to build the solution

### ISSUE THREAD

**Issue by TarunBabbar** [IdentityServer/IdentityServer4.Samples#172]
I have taken the samples code on my machine, but while trying to build the Clients solution, I am getting below error in output. I am building the solution in Visual Studio 2015 Enterprise. Anything I am missing here?

C:\Tarun\IdentityServer4.Samples-release\Clients\src\ConsoleClientCredentialsFlow\ConsoleClientCredentialsFlow.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Tarun\IdentityServer4.Samples-release\Clients\src\ConsoleClientCredentialsFlow\ConsoleClientCredentialsFlow.csproj

C:\Tarun\IdentityServer4.Samples-release\Clients\src\Constants\Constants.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Tarun\IdentityServer4.Samples-release\Clients\src\Constants\Constants.csproj

C:\Tarun\IdentityServer4.Samples-release\Clients\src\ConsoleResourceOwnerFlow\ConsoleResourceOwnerFlow.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Tarun\IdentityServer4.Samples-release\Clients\src\ConsoleResourceOwnerFlow\ConsoleResourceOwnerFlow.csproj

C:\Tarun\IdentityServer4.Samples-release\Clients\src\ConsoleClientCredentialsFlowPostBody\ConsoleClientCredentialsFlowPostBody.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Tarun\IdentityServer4.Samples-release\Clients\src\ConsoleClientCredentialsFlowPostBody\ConsoleClientCredentialsFlowPostBody.csproj

C:\Tarun\IdentityServer4.Samples-release\Clients\src\ConsoleResourceOwnerFlowRefreshToken\ConsoleResourceOwnerFlowRefreshToken.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Tarun\IdentityServer4.Samples-release\Clients\src\ConsoleResourceOwnerFlowRefreshToken\ConsoleResourceOwnerFlowRefreshToken.csproj

C:\Tarun\IdentityServer4.Samples-release\Clients\src\ConsoleResourceOwnerFlowUserInfo\ConsoleResourceOwnerFlowUserInfo.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Tarun\IdentityServer4.Samples-release\Clients\src\ConsoleResourceOwnerFlowUserInfo\ConsoleResourceOwnerFlowUserInfo.csproj

C:\Tarun\IdentityServer4.Samples-release\Clients\src\ConsoleIntrospectionClient\ConsoleIntrospectionClient.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Tarun\IdentityServer4.Samples-release\Clients\src\ConsoleIntrospectionClient\ConsoleIntrospectionClient.csproj

C:\Tarun\IdentityServer4.Samples-release\Clients\src\ConsoleResourceOwnerFlowReference\ConsoleResourceOwnerFlowReference.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Tarun\IdentityServer4.Samples-release\Clients\src\ConsoleResourceOwnerFlowReference\ConsoleResourceOwnerFlowReference.csproj

C:\Tarun\IdentityServer4.Samples-release\Clients\src\ConsoleCustomGrant\ConsoleCustomGrant.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Tarun\IdentityServer4.Samples-release\Clients\src\ConsoleCustomGrant\ConsoleCustomGrant.csproj

C:\Tarun\IdentityServer4.Samples-release\Clients\src\MvcImplicit\MvcImplicit.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Tarun\IdentityServer4.Samples-release\Clients\src\MvcImplicit\MvcImplicit.csproj

C:\Tarun\IdentityServer4.Samples-release\Clients\src\JsOAuth2\JsOAuth2.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Tarun\IdentityServer4.Samples-release\Clients\src\JsOAuth2\JsOAuth2.csproj

C:\Tarun\IdentityServer4.Samples-release\Clients\src\JsOidc\JsOidc.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Tarun\IdentityServer4.Samples-release\Clients\src\JsOidc\JsOidc.csproj

C:\Tarun\IdentityServer4.Samples-release\Clients\src\SampleApi\SampleApi.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Tarun\IdentityServer4.Samples-release\Clients\src\SampleApi\SampleApi.csproj

C:\Tarun\IdentityServer4.Samples-release\Clients\src\MvcHybrid\MvcHybrid.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Tarun\IdentityServer4.Samples-release\Clients\src\MvcHybrid\MvcHybrid.csproj

C:\Tarun\IdentityServer4.Samples-release\Clients\src\ConsoleResourceOwnerFlowPublic\ConsoleResourceOwnerFlowPublic.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Tarun\IdentityServer4.Samples-release\Clients\src\ConsoleResourceOwnerFlowPublic\ConsoleResourceOwnerFlowPublic.csproj

C:\Tarun\IdentityServer4.Samples-release\Clients\src\MvcManual\MvcManual.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Tarun\IdentityServer4.Samples-release\Clients\src\MvcManual\MvcManual.csproj

C:\Tarun\IdentityServer4.Samples-release\Clients\src\ConsolePrivateKeyJwtClient\ConsolePrivateKeyJwtClient.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Tarun\IdentityServer4.Samples-release\Clients\src\ConsolePrivateKeyJwtClient\ConsolePrivateKeyJwtClient.csproj

C:\Tarun\IdentityServer4.Samples-release\Clients\src\ConsoleHybridWithPkce\ConsoleHybridWithPkce.csproj : error  : The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  C:\Tarun\IdentityServer4.Samples-release\Clients\src\ConsoleHybridWithPkce\ConsoleHybridWithPkce.csproj

**Comment by leastprivilege** [comment]
You need VS2017 - e.g. community edition.

**Comment by TarunBabbar** [comment]
Thanks your update
