### ISSUE TITLE
Quickstart Sample 6 - IdentityServer with AspNet Identity not compatible with .NET Core

### ISSUE THREAD

**Issue by WazzaMo** [IdentityServer/IdentityServer4.Samples#173]
# Problem
Quickstart Sample 6 uses Microsoft.Composition which requires .NET Framework 4.5 and does not support .NET Core and this is not clearly stated that I could see.
https://www.nuget.org/packages/Microsoft.Composition/1.0.27

Please update the Readme.md to indicate that .NET Framework (not .NET Core) is the intended platform.

## Error Message at Restore (.NET Core 1.1)
```
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): error : Package Microsoft.Composition 1.0.27 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Microsoft.Composition 1.0.27 supports: portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259) [6_AspNetIdentity\src\IdentityServerWithAspNetIdentity\IdentityServerWithAspNetIdentity.csproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): error : One or more packages are incompatible with .NETCoreApp,Version=v1.1. [6_AspNetIdentity\src\IdentityServerWithAspNetIdentity\IdentityServerWithAspNetIdentity.csproj]
```

**Comment by Jingkun-Hu** [comment]
.net 4.5 may not be the target platform. Just comment out Composition package reference and it works

**Comment by WazzaMo** [comment]
@Jingkun-Hu thanks for your reply but that's not what I'm finding.
The reference to `Microsoft.Composition` appears to come from a dependency.

Looking at the csproj file, there is NO explicit inclusion of Microsoft.Composition.
https://github.com/IdentityServer/IdentityServer4.Samples/blob/release/Quickstarts/6_AspNetIdentity/src/IdentityServerWithAspNetIdentity/IdentityServerWithAspNetIdentity.csproj

VS 2017 points out that many of the Nuget packages have available updates.  Updating fails due to this hidden dependency.

**Comment by WazzaMo** [comment]
On further examination, I think the problem creeps in due to the package IdentityServer4.AspNetIdentity.
There are two projects:
- Host - targets dotnetcore 1.1
- IdentityServer4.AspNetIdentity.csproj which targets .NET Framework 4.5.2 !!

https://github.com/IdentityServer/IdentityServer4.AspNetIdentity/blob/dev/src/IdentityServer4.AspNetIdentity/IdentityServer4.AspNetIdentity.csproj

**Comment by leastprivilege** [comment]
`<TargetFrameworks>netstandard1.4;net452</TargetFrameworks>`

It targets *both*

**Comment by paulvanbladel** [comment]
Same problem here :(

**Comment by duncanawoods** [comment]
You can fix this by removing the dependency:

    Microsoft.VisualStudio.Web.CodeGeneration.Design

You can now restore packages and update all the dependencies. I think its a mistake adding a visualstudio package as a runtime dependency instead of just a DotNetCliToolReference tool.

**Comment by leastprivilege** [comment]
I can't repro the problem locally. But glad you found a fix. Feel free to submit a PR.

**Comment by open-environment** [comment]
Just want to add that I have this problem too, and the workaround to remove the dependency worked as well.
