### ISSUE TITLE
Quickstart Sample 6 - SecurityAttribute causes CSP errors

### ISSUE THREAD

**Issue by duncanawoods** [IdentityServer/IdentityServer4.Samples#176]
The css and js for the IdentityServer do not load from the MVC client because of CSP errors e.g.

    Refused to execute inline script because it violates the following Content Security Policy directive: "default-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-eNYKgDOxdMjUMFmlqVjLSIBHYSBciCwh8Qq2QkPk7xA='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.

    Refused to load the stylesheet 'https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.

It appears to be due to the custom SecurityHeadersAttribute the project uses on all the controllers.

**Comment by duncanawoods** [comment]
Ah running in development doesn't use CDNs. I guess that if this security policy is intended, the _layout.cshtml should not use CDNs in production:

    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>

Still get errors due to browserlink

    Refused to load the script 'http://localhost:51707/53c7a7060f0e432293b1527453470e7a/browserLink' because it violates the following Content Security Policy directive: "default-src 'self'". Note that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.

**Comment by brockallen** [comment]
The CSP code is there for you to manage based on your situation. It's just a starting point (since it's in the quickstart).

**Comment by duncanawoods** [comment]
Ok but I was disappointed to "dotnet run" a quickstart and have scary security errors and broken styling. You can do this on Sample 8. just fine because it doesn't use CDNs.

Would you like a PR removing the CDNs so that "dotnet run" will work?

**Comment by brockallen** [comment]
Ah, I see. Yea, the main difference is that for this one we started with the ASP.NET Identity template in an attempt to be as close to the "out of the box VS wizard experience". When doing so you must have run it with F5. I rarely run with F5 (I tend to use Ctrl-F5), and also I have browserlink disabled in my VS (since I have so many issues with it, this being an example of one). 

As for the "dotnet run", I also see what you're saying. So sure, if you're up for a PR then we'll accept it. Thanks.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
