### ISSUE TITLE
Not redirecting to Url after SignOut

### ISSUE THREAD

**Issue by rizamarhaban** [IdentityServer/IdentityServer4.Samples#177]
Hi,

I'm learning to use Identity Server. This method I added in the Web App client for Sign out,

        public IActionResult SignOut()
        {
            var callbackUrl = Url.Action("Index", "Home", values: null, protocol: Request.Scheme);
            return SignOut(new AuthenticationProperties { RedirectUri = callbackUrl },
                CookieAuthenticationDefaults.AuthenticationScheme, OpenIdConnectDefaults.AuthenticationScheme);
        }

The callbackUrl shows the web app client Url, however after SignOut action executed and successfully signing out, it did not redirect back to the web app, instead is showing the identity server login page. I also add this in the client configuration:

    PostLogoutRedirectUris = { $"{webDomain}" },

I believe I'm missing something here. How do I implement this flow on the Identity Server web app side. I use the asp.net MVC template with asp.net identity for the identity server project. Thanks.

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
