### ISSUE TITLE
Sample with IdentityServer and API in same process

### ISSUE THREAD

**Issue by nicolasr75** [IdentityServer/IdentityServer4.Samples#18]
I have a very simple scenario where I want to allow a small number of clients access to a legacy database type via a REST API. I have not yet thought about whether this will be self-hosted or IIS. I think it would greatly simply things if I could have IdentityServer and API in the same process sharing the same root URL.

Could you add a sample for this scenario or does there already exist one?

**Comment by leastprivilege** [comment]
There is no sample - try it yourself - should just work.

**Comment by nicolasr75** [comment]
OK, I have implemented both parts as separate projects which works well. Trying to put IdentityServer into my API app doesn't seem to work with dnx451, probably because of https://github.com/IdentityServer/IdentityServer4/issues/8 

Just one more question:
currently my connection to IdendityServer is configured like this
	app.UseIdentityServerAuthentication(options =>
	{
		options.Authority = "http://localhost:54134/";
		...
	});

Is there another way to set the authority in the case where IdSrv and API are in the same process??? Looks somehow strange that I call my own app via this URL.

**Comment by leastprivilege** [comment]
you can statically configure the middleware instead. Since you are in the same startup, you have signing cert and issuername.
