### ISSUE TITLE
why IPersistedGrantStore does not work with SQL storage??

### ISSUE THREAD

**Issue by aaguerra** [IdentityServer/IdentityServer4.Samples#181]
I was following the documentation tutorial and the topic "Using EntityFramework Core for configuration data" indicates that the configurations can be stored in the base, but the problem is that following the documentation the only thing that works for me are the configurations of client, scope, user.
the Storage of the PersistedGrant when the application is deployed, is still handled in memory
How do I make the IPersistedGrantStore not to be handled in memory??
If someone owns in a git repository an implementation of the IPersistedGrantStore that can facilitate me would be very helpful.

**Comment by brockallen** [comment]
Did you look at our EF implementation?

**Comment by aaguerra** [comment]
Using the QuickStarts example, the DB table PersistensGrand always passes empty even though users log in and ask for a token in the application
![image](https://user-images.githubusercontent.com/3911350/27987205-7fb8cc02-63cf-11e7-9a7d-73e4af52239f.png)

How is the acces_token stored in the SQL database?

**Comment by brockallen** [comment]
If you don't use the scenarios for persisted grants, then you might not get entries in the table.

**Comment by aaguerra** [comment]
If I want to do load balancing
How do you configure two IDENTITYSERVER4 servers to serve the tokens in either?

**Comment by brockallen** [comment]
I'll close this here since you have two of the same issues open.

**Comment by aaguerra** [comment]
ok
