### ISSUE TITLE
LoggedOut page with multiple IFRAMEs for multiple clients?

### ISSUE THREAD

**Issue by danielearwicker** [IdentityServer/IdentityServer4.Samples#183]
[IdentityServer docs](http://docs.identityserver.io/en/release/topics/signout.html) explain how the IDS is responsible for inserting hidden `iframe`s (one per client app) to a `src` of their choice so they get notified when the user signs out.

Looking at the examples here I see only support for a single client `iframe` URL being available to include in the `LoggedOut` page, e.g. in [LoggedOut.cshtml](https://github.com/IdentityServer/IdentityServer4.Samples/blob/release/Quickstarts/8_EntityFrameworkStorage/src/QuickstartIdentityServer/Views/Account/LoggedOut.cshtml)

```
    @if (Model.SignOutIframeUrl != null)
    {
        <iframe width="0" height="0" class="signout" src="@Model.SignOutIframeUrl"></iframe>
    }
```

Tracking back to where the view model is built so I can see how to support single sign-out from multiple clients I get to:

```cs
public async Task<LoggedOutViewModel> BuildLoggedOutViewModelAsync(string logoutId)
{
    // get context information (client name, post logout redirect URI and iframe for federated signout)
    var logout = await _interaction.GetLogoutContextAsync(logoutId);

    var vm = new LoggedOutViewModel
    {
        // blah
        SignOutIframeUrl = logout?.SignOutIFrameUrl,
```

So `GetLogoutContextAsync` only provides one such URL. Am I misunderstanding the docs? Is there some other approach needed when supporting multiple client apps and notifying them all when the user signs out?

**Comment by leastprivilege** [comment]
The iframe in turn contains additional iframes for each client.

**Comment by kibagami-jubei** [comment]
How do we configure identity server as federation gateway?
