### ISSUE TITLE
Asp.Net Identity with IdentityServer EF (Combining Sample 6 and Sample 8)

### ISSUE THREAD

**Issue by NickBrooks** [IdentityServer/IdentityServer4.Samples#184]
I'm able to get all the samples working but putting it all together is unfortunately not clicking with me.

I'm trying to get Asp.Net Identity working with IdentityServer4.EntityFramework, running all the User and IdentityServer data in the same database. I've done that by specifying the three different DbContexts and the Db contains all the tables it needs.

Now I'm trying to run the project and it says something like 'Two Controllers exist'.  So I remove the default Asp.Net Identity Home, Account and Manage controllers and it runs, however, left with just the Quickstart UI and there's no options/links for the user to register or login??? How is all this supposed to work??

Is it possible to have a ninth example with everything put together because all the samples focus on one thing, which is great, but putting it together I'm struggling to get it all clicking. 

Any help appreciated! :)

**Comment by NickBrooks** [comment]
I guess for reference, firstly, here's the error I get out of the box...

```
An unhandled exception occurred while processing the request.

AmbiguousActionException: Multiple actions matched. The following actions matched route data and had all constraints satisfied:

IdentityServer4.Quickstart.UI.HomeController.Index (Abstrack.Identity)
Abstrack.Identity.Controllers.HomeController.Index (Abstrack.Identity)
Microsoft.AspNetCore.Mvc.Internal.ActionSelector.SelectBestCandidate(RouteContext context, IReadOnlyList<ActionDescriptor> candidates)
```

Secondly, the Asp.Net Identity sample looks like this (but the IdentityServer client data is not persisted):

![](http://docs.identityserver.io/en/release/_images/6_home_page.png)

And the last project which does persist the IdentityServer data looks like this (user can't register):

![default](https://user-images.githubusercontent.com/4286755/28433567-59167d74-6db6-11e7-89be-7d047970cf9f.JPG)

**Comment by NickBrooks** [comment]
Hi - just wondering if anyone has any pointers/help on this one!?

**Comment by MNF** [comment]
I've also struggled with merging QuickStart 6 and 8 and described my work at https://stackoverflow.com/questions/43379938/which-identityserver4-sample-should-i-choose-as-a-starting-point, but your mileage may vary. It will be great to have combined QuickStart sample.

**Comment by brockallen** [comment]
Any update?

**Comment by brockallen** [comment]
Sample done: https://github.com/IdentityServer/IdentityServer4.Samples/commit/dbde896171c8d2c59e079e82f1a9ce04d1954035
