### ISSUE TITLE
Docker Example not working 

### ISSUE THREAD

**Issue by albertolo** [IdentityServer/IdentityServer4.Samples#187]
When running docker-compose up fails on Windows 10 
**ERROR: client version 1.21 is too old. Minimum supported API version is 1.24, please upgrade your client to a newer version**

Client:
 Version:      17.06.0-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 21:30:30 2017
 OS/Arch:      windows/amd64

Server:
 Version:      17.06.0-ce
 API version:  1.30 (minimum version 1.24)
 Go version:   go1.8.3
 Git commit:   02c1d87
 Built:        Fri Jun 23 22:19:00 2017
 OS/Arch:      windows/amd64
 Experimental: true

**Comment by programatt** [comment]
@albertolo according to the docker-compose docs any docker-compose.yml without a version tag will be assumed to be version 1.0. [This](http://www.jeffreyfritz.com/2017/01/docker-compose-api-too-old-for-windows/) blog post describes a similar version error and it was solved by adding the version to the docker-compose.yml. Funny enough I just submitted a [PR](https://github.com/IdentityServer/IdentityServer4.Samples/pull/189) tonight that adds that with some other things. So if it is accepted, this should be resolved.
