### ISSUE TITLE
Is there any possibility to use my own db in IDS4 yet?

### ISSUE THREAD

**Issue by hmheng** [IdentityServer/IdentityServer4.Samples#19]
i would like to implement IDS4 with my MVC6 application. however, i couldn't find any details on how to implement it by using my own SQL server instead of inmemory data.

hope there's anyone can help me for the implementation.
Thanks a lot first ya.

**Comment by leastprivilege** [comment]
absolutely. Check our code on the login pages etc...also you need an implementation of IProfileService

**Comment by hmheng** [comment]
is this only limited to Users?
can i make client & scopes stores in my db as well so i can create a form to change it dynamically?

**Comment by leastprivilege** [comment]
yes of course

**Comment by brockallen** [comment]
We now have a quickstart for ASP.NET Identity: https://identityserver4.readthedocs.io/en/release/quickstarts/6_aspnet_identity.html
