### ISSUE TITLE
Option to cancel sign-in/sign-up and redirect back

### ISSUE THREAD

**Issue by DDN-Shep** [IdentityServer/IdentityServer4.Samples#190]
We are currently using the IdentityServer4 quick start project and have updated the UI to suit our needs. However, there's something that completely eludes me;

We would like to provide the option to Cancel and return back to the calling client (perhaps the client changes their mind and cannot be bothered signing up or whatever).

I can't see this documented anywhere, can you recommend a way to go about implementing this please?

**Comment by brockallen** [comment]
There's nothing in OIDC for this, except to trigger a deny (from the consent screen for example). Perhaps we could consider adding something to help here (from any page, like your registration one as an example)... I'll look into it, but no promises tho :)

**Comment by DDN-Shep** [comment]
No problem, thanks for having a little look into it at the very least.

**Comment by leastprivilege** [comment]
This was done in the QS UI
