### ISSUE TITLE
Constants & using Clients issue

### ISSUE THREAD

**Issue by gogshela3** [IdentityServer/IdentityServer4.Samples#191]
Hi, 
in MVC Manual Client app HomeComponent - I got en errors "The name 'Constants' does not exist".

also controller cannot read:
"using Clients;"

please Help

**Comment by brockallen** [comment]
Did you just open the one project and not the entire clients solution?

**Comment by gogshela3** [comment]
Yes opened full clients project but I've error. (see attachment)
![capture](https://user-images.githubusercontent.com/26521731/28977852-cf372fae-7954-11e7-8631-c8df60f919f1.PNG)

**Comment by gogshela3** [comment]
also, constants added as reference 
![capture1](https://user-images.githubusercontent.com/26521731/28978109-ce0e1ea2-7955-11e7-81dd-432f7fa70001.PNG)

**Comment by leastprivilege** [comment]
Any update on the issue? closing for now - feel free to re-open if it needs further discussion.
