### ISSUE TITLE
IdentityServer4 for Web Api 2 .Net Framework not .Net Core

### ISSUE THREAD

**Issue by ecomputer83** [IdentityServer/IdentityServer4.Samples#195]
I am using WebApi 2 .Net framework, how can i integrate IdentityServer4 to it. I tried the .Net Core and it works but i need to reference some project that uses .NetFramework 4.6.2.

Is there a way to integrate IdentityServer4 to WebApi 2 .Net Framework?

**Comment by brockallen** [comment]
Look at these samples: https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Clients/SampleAspNetWebApi
