### ISSUE TITLE
Can we have a javascript client sample without redirecting to identityserver to login?

### ISSUE THREAD

**Issue by hnviradiya9** [IdentityServer/IdentityServer4.Samples#196]
I have asked many questions on Stackoverflow. But no response. Just want to know how can I implement identityserver as an API which allows javascript client to get authenticated. But without redirecting to login page of identity server.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/
