### ISSUE TITLE
ASP.NET Core 2.0

### ISSUE THREAD

**Issue by atsvetkov** [IdentityServer/IdentityServer4.Samples#199]
Any plans on upgrading the samples to ASP.NET Core 2.0? I know there are some API changes - @brockallen, how difficult you think it would be to migrate? If this sounds like a good idea but not of the highest priority for you, I would be willing to give it a try.

**Comment by brockallen** [comment]
Soon. I have done all the work already on the dev branch, I just need to release a nuget -- we will on monday.

**Comment by atsvetkov** [comment]
Thanks!

**Comment by leastprivilege** [comment]
Actually the dev branch has moved to 2.0 as of today.
