### ISSUE TITLE
Fix IdSvrHost application cannot find certificate exception

### ISSUE THREAD

**Issue by TimMurphy** [IdentityServer/IdentityServer4.Samples#2]
When you do the following

- Clone [IdentityServer4.Samples](https://github.com/IdentityServer/IdentityServer4.Samples.git)
- Open `.\Mvc\Mvc.sln`
- Start the application from Visual Studio

Then the following error is displayed:

```
Oops.
500 Internal Server Error
System.Security.Cryptography.CryptographicException
The system cannot find the file specified.
```

This error is resolved by copying `idsrv3test.pfx` from [IdentityServer4](https://github.com/IdentityServer/IdentityServer4.git) repository to `.\Mvc\src\IdSvrHost\idsrv3test.pfx`.

When preparing a pull request I found `.\.gitignore` includes `idsrv3test.pfx`. Is there a reason for this? I stopped creating a pull request because of this fact.

**Comment by brockallen** [comment]
Ok, I added the .pfx. Thanks.
