### ISSUE TITLE
Javascript Oidc - Checksession to IDSRVR 4 return 404

### ISSUE THREAD

**Issue by Jenan** [IdentityServer/IdentityServer4.Samples#20]
I tried the sample called Javascript Oidc and when I obtained the access token and check session - check_session_iframe: "http://localhost:22530/connect/checksession" and then GET http://localhost:22530/connect/checksession 404 (Not Found).

How can I fix this 404?

**Comment by brockallen** [comment]
Check session is not yet implemented in IdSvr4. It will be eventuially.

**Comment by mribichich** [comment]
+1

**Comment by leastprivilege** [comment]
but it is now - right? @brockallen

**Comment by brockallen** [comment]
Correct. We even have an integration test specifically for 404: https://github.com/IdentityServer/IdentityServer4/blob/dev/test/IdentityServer.IntegrationTests/Endpoints/CheckSession/CheckSessionTests.cs#L30
