### ISSUE TITLE
ExternalLoginOnly does not work with Windows Authentication

### ISSUE THREAD

**Issue by carlosfza** [IdentityServer/IdentityServer4.Samples#200]
While I have been developing with IdentityServer4 for a some weeks, I am still relativelly new to Asp.Net Core Authentication, so there is the possibility of miss-configuration on my part. This issue occurs in a project based on the quickstart 4, with minor alterations to enable Windows Authentication in the AccountOptions.cs file.

This issue occurs when a client attempts to authenticate with Windows Authentication using ExternalLoginOnly, by requesting"acr_values" of "idp:Negotiate". In this scenario, IdentityServer, after ExternalLoginCallback,  instead of providing the consent page, the client is redirected towards ExternalLogin once again. Since the client has already performed the challenge, this action crashes my client.

Alternativelly, not requesting ExternalLoginOnly via acr_values, and selecting windows authentication in the log-in page works as expected.

As a side question, is it possible to, using the authorization grant, for an enterprise scenario, use Windows Authentication while skipping also the consent page?

**Comment by brockallen** [comment]
I'll try to repro.

**Comment by carlosfza** [comment]
Hi again,

In order to help you reproduce, I have created a simple UWP client that exemplifies this behaviour. I used a simple client using IdentityModel, using similar logic to the one presented at IdentityServer3 Xamarin.Forms sample client (https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Xamarin), with the acr_values added or not, to exemplify the situation.

`dic.Add("acr_values", "idp:Negotiate");`

All changes to the quickstrart4 identity server were the following:

- In the project tab, allow for Windows Authentication.

- In AccountOptions.cs:

`public static bool WindowsAuthenticationEnabled = true;  //was false`

- In Config.cs, I used the mvc client, and thus added a new RedirectUri to the list, which I used for my client.

If you would like to, I can also provide a zip with the test quickstart4+client.

**Comment by brockallen** [comment]
Ah, sorry -- I misunderstood -- you're on 1.x. Did you try "idp:Windows" for the acr_values? We did have a bug and IIRC we fixed it recently. It involved changing the QS logic.

**Comment by carlosfza** [comment]
Using "idp:Windows" option does not work with the QS, firstly because its not a supported provider, leading to:
`if (AccountOptions.WindowsAuthenticationSchemes.Contains(provider)) //fails because the default schemes are "Negotiate" and "NTLM"`

Even after adding the "Windows" scheme, this scheme doesn't seem to be recognized as a valid challenge, since I get the error "No authentication scheme is configured to handle the scheme Windows" once the QS gets to the:

`return new ChallengeResult(AccountOptions.WindowsAuthenticationSchemes); //present in AccountController's ExternalLogin method`

Without the "acr_values" clicking the "Windows" button on the external options of the Home view sets the provider value to "Negotiate". Therefore I don't think setting "idp:Windows" has the potential to solve the issue. 

In debugging the issue, I notice that **without** using "acr_values", the Login action on AccountController is only triggered once, ending in `return View(vm)`. Alternatively, when"idp:<anything>" is provided in the "acr_values", the Login action instead calls `return await ExternalLogin(vm.ExternalLoginScheme, returnUrl);`, and after the Challenge is performed and ExternalLoginCallback action is finished, instead of being redirected with the token as expected, the Login action is once again invoked, which calls the ExternalLogin, which requires a new challenge, which just crashes the whole thing.

The page flow goes somewhat like this:
**Login** -_calls_-> **ExternalLogin** -_issues challenge_-> **ExternalLogin** -_signs in and redirects_-> **ExternalLoginCallback** -_issues cookie, redirects_-> ??**Login**?? -_calls_-> **ExternalLogin** -_issues challenge and crashes client_-||

I believe this to be the issue, either in the IdentityServer4 1.x logic calling the Login action multiple times when it should have instead redirected with the token, or some other issue related to that in the QS logic.

**Comment by brockallen** [comment]
So we did have an issue for this a while back and I did fix it, but it was on the dev branch. Here's the commit, so if you can apply this to yours then I think you'll be all set: https://github.com/IdentityServer/IdentityServer4/commit/89162ca6f7a27684f24ff96f7d2dd6a71d6e4fa0

**Comment by carlosfza** [comment]
Just tested and I can confirm it works.

**Comment by brockallen** [comment]
Ok, so you're all set then?

**Comment by carlosfza** [comment]
Still much to do, but working well so far. Thanks.
