### ISSUE TITLE
Add silent.html to allowed redirect uris for js_oidc client.

### ISSUE THREAD

**Issue by ngbrown** [IdentityServer/IdentityServer4.Samples#201]
The `silent.html` redirect uri needs to be added to the list here:
https://github.com/IdentityServer/IdentityServer4.Samples/blob/2bf6eed7d9d2be5214001d09d5a76f97e4a3c0f7/NodeJsApi/src/QuickstartIdentityServer/Config.cs#L63

Because the javascript client will attempt to silently renew to this redirect location.
https://github.com/IdentityServer/IdentityServer4.Samples/blob/2bf6eed7d9d2be5214001d09d5a76f97e4a3c0f7/Clients/src/JsOidc/wwwroot/app.js#L23

Since the default access token time is 1 hour, it might help to shorten the lifetimes in the sample so refresh can be observed.

**Comment by brockallen** [comment]
@AlexZeitler -- can you do this?

**Comment by AlexZeitler** [comment]
Yes, but might take a few days (Saturday/Sunday).

**Comment by brockallen** [comment]
Ok thanks.

**Comment by AlexZeitler** [comment]
@brockallen @ngbrown which value for the access token time would be useful for you?

**Comment by ngbrown** [comment]
These are the times that I ended up using to see the refreshes on a regular basis:

```js
                new Client
                {
                   //...
                    AbsoluteRefreshTokenLifetime = 200,
                    IdentityTokenLifetime = 15,
                    AccessTokenLifetime = 100,
                    AuthorizationCodeLifetime = 15,
                    SlidingRefreshTokenLifetime = 120,
                   //...
                },
```

**Comment by AlexZeitler** [comment]
@brockallen done. Took a few days longer as I have been sick over the weekend.

**Comment by brockallen** [comment]
Thanks and feel better! :)
