### ISSUE TITLE
wpf with IS4

### ISSUE THREAD

**Issue by luigi108** [IdentityServer/IdentityServer4.Samples#205]
Hi,
I'm looking for an example of WPF with IS4 and I can not find; I need help to know how to configure wpf for WebApi access and what type of GrantTypes should I use to work with IS4 WebApi and WPF. 
Thank you very much

**Comment by leastprivilege** [comment]
Use this WinForms sample as a starting point.

https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/tree/master/WinFormsWebView

Then either implement a WPF webview - or use the system browser.

**Comment by luigi108** [comment]
Thank you
