### ISSUE TITLE
How to force logout / endSession

### ISSUE THREAD

**Issue by wluijk** [IdentityServer/IdentityServer4.Samples#207]
When i start sample 2 with Resource Owner Password flow i get the whole flow working except the logout  or endSession working. When i call the "/connect/endsession" i get a not found error. Any help will be appreciated. From the docs i understand the logoutId parameter is optional....
The IdentityServer says the idsrv was not authenticated.
The request path /connect/endsession matched to endpoint type EndSession

**Comment by brockallen** [comment]
Resource owner flow is OAuth2, and there is no concept of logout.

**Comment by wluijk** [comment]
Which flow is most used when dealing with API in the cloud and Android Apps in and outside the company?

**Comment by brockallen** [comment]
hybrid + pkce
