### ISSUE TITLE
error en IS4 NetIdentity con WinFormWebView

### ISSUE THREAD

**Issue by luigi108** [IdentityServer/IdentityServer4.Samples#208]
Hi

I have done testing with the example https://github.com/IdentityServer/IdentityServer4.Samples/tree/release/Quickstarts/6_AspNetIdentity with https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/tree/master/WinFormsWebView ; I have added the native.hybrid client on the IS4, but I have an error, which I am doing wrong or which demo to modify to work both.
I attached the error image, thanks for your help

![error](https://user-images.githubusercontent.com/31579622/30465611-9386ddba-999d-11e7-9f37-9ea954e4bec0.jpg)

Code client:
 ` new Client
                {
                    ClientId = "native.hybrid",
                    ClientName = "Native Client (Hybrid with PKCE)",

                    RedirectUris = { "https://notused" },
                    PostLogoutRedirectUris = { "https://notused" },

                    RequireClientSecret = false,

                    AllowedGrantTypes = GrantTypes.Hybrid,
                    RequirePkce = true,
                    AllowedScopes = { "openid", "profile", "email", "api" },
                    AllowOfflineAccess = true
                },

`

**Comment by leastprivilege** [comment]
no logs. no help.

**Comment by luigi108** [comment]
Hi

I run it line by line and I notice that the line var result = await _oidcClient.LoginAsync (DisplayMode.Visible); of the private async method void LoginButton_Click (object sender, EventArgs e) does not execute the method public async Task <IActionResult> Login (string returnUrl) of the server's AccountController driver, does not enter the method.
When running var result = await _oidcClient.LoginAsync (DisplayMode.Visible); of the method private async void LoginButton_Click (object sender, EventArgs e), what is the method that executes immediately in the IS4 Seridor?

**Comment by luigi108** [comment]
It does not show me the option to enter the user and the password, only the error message (attached in the first message)

**Comment by luigi108** [comment]
hi,

What I do not understand is that your demo https://github.com/IdentityServer/IdentityServer4.Samples/tree/release/Quickstarts/6_AspNetIdentity sole adds in config new Client
                {
                    ClientId = "native.hybrid",
                    ClientName = "Native Client (Hybrid with PKCE)",

                    RedirectUris = {"https: // notused"},
                    PostLogoutRedirectUris = {"https: // notused"},

                    RequireClientSecret = false,

                    AllowedGrantTypes = GrantTypes.Hybrid,
                    RequirePkce = true,
                    AllowedScopes = {"openid", "profile", "email", "api"},
                    AllowOfflineAccess = true
                }, and in your windows demo modify public SampleForm ()
        {
            InitializeComponent ();

            var options = new OidcClientOptions
            {
                Authority = "http: // localhost: 5000",
                // Authority = "https://demo.identityserver.io",
                ClientId = "native.hybrid",
                Scope = "openid email api offline_access",
                RedirectUri = "http: //localhost/winforms.client",

                Browser = new WinFormsEmbeddedBrowser ()
            };

            _oidcClient = new OidcClient (options);
        } and do not work together

**Comment by luigi108** [comment]
The windows client https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/tree/master/WinFormsWebView with the IS4 https://github.com/IdentityServer/IdentityServer4.Demo/tree/master/src/IdentityServer4Demo if they work ; why does not the windows client work https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/tree/master/WinFormsWebView with the IS4NetIdentity Demo?

**Comment by luigi108** [comment]
Hi

Find my error, they already work missing add 2 classes DemoRedirectValidator and DemoCorsPolicy; Thank you.
