### ISSUE TITLE
Logout issue in Identity server 4

### ISSUE THREAD

**Issue by rahulmistry25425** [IdentityServer/IdentityServer4.Samples#209]
Hello, i am using identity server 4 with .net core 2.

i have copy and pasted quickstart template in project, but now i am facing logout issue.while i am trying to logout from identity server but it is not working and still loged in identity server.

Here is the screenshot

![untitled](https://user-images.githubusercontent.com/15902578/30535293-784e977e-9c7f-11e7-8d10-4f8f68be9d8c.png)

please let me know what i am doing wrong?

**Comment by brockallen** [comment]
Did you update the quickstart UI code when you upgraded?

**Comment by brockallen** [comment]
You will need to inspect the logs and diagnose some more. There's not enough info here.

**Comment by brockallen** [comment]
Any update?

**Comment by rahulmistry25425** [comment]
while clicked on logout,logs are here
```
info: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[8]
      AuthenticationScheme: Identity.Application was successfully authenticated.
info: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[8]
      AuthenticationScheme: Identity.Application was successfully authenticated.
info: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[8]
      AuthenticationScheme: Identity.Application was successfully authenticated.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method IdentityServer4.Quickstart.UI.AccountController.Logout (ASAP.IdentityServer) with arguments () - ModelState is Valid
info: Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor[1]
      Executing ViewResult, running view at path /Views/Account/Logout.cshtml.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action IdentityServer4.Quickstart.UI.AccountController.Logout (ASAP.IdentityServer) in 12.6394ms
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 44.5161ms 200 text/html; charset=utf-8
```

**Comment by brockallen** [comment]
Was it null on the GET request to logout? If so, you need to check the logs from the end session endpoint.

**Comment by Lufijane** [comment]
Same issue here. How to recreate:

1. Run IdentityServerWithAspNetIdentity project in 6_AspNetIdentity sample
2. Go to IDP portal website (http://localhost:5000/)
3. Click log in (register new user if needed)
4. Click log out
5. After log out you can still see "Hello youremail" on navbar

I think user acctually gets logged out but navbar is not correctly refreshed

**Comment by brockallen** [comment]
I think this was fixed here: https://github.com/IdentityServer/IdentityServer4.Samples/pull/222. If not, please reopen and/or let me know. Thanks.
