### ISSUE TITLE
Get Clients and Scopes from database? 

### ISSUE THREAD

**Issue by leo9223** [IdentityServer/IdentityServer4.Samples#21]
How to get clients and scopes from database?

**Comment by brockallen** [comment]
We have interfaces you can implement -- IScopeStore and IClientStore. Put them into the ASP.NET DI system and we'll use them.

**Comment by leo9223** [comment]
Sir is there any example out? I can see then ..?

**Comment by brockallen** [comment]
Only the IdSvr3 versions.

**Comment by leo9223** [comment]
Sir please have a look 

        public async Task<Client> FindClientByIdAsync(string clientId)
        {
            

            Clients objCl = adc.Clients.FirstOrDefault(c => c.ClientId == clientId);

            Client client = new Client()
            {
                ClientId = objCl.ClientId,
                ClientSecrets = new List<Secret>
                {
                    new Secret(objCl.ClientSecret.Sha256())
                },

                Flow = Flows.ResourceOwner
            };

            client.AllowedScopes = new List<string>();

            await Task.Delay(5000);

            foreach (var scope in objCl.ClientScopes)
            {
                client.AllowedScopes.Add(scope.Scope.ScopeName);
            }


            return client;
        }


is it right way to code this method?
adc is my dbcontext which is populated but getting internal server error on client side

**Comment by joaomello** [comment]
Remove:
`await Task.Delay(0);`
Change:
`Clients objCl = adc.Clients.FirstOrDefault(c => c.ClientId == clientId);`
To:
`Clients objCl = adc.Clients.FirstOrDefaultAsync(c => c.ClientId == clientId);`

**Comment by leo9223** [comment]
Thankyou @joaomello

but there is only FirstOrDefault exist !

no FirstOrDefaultAsync exists for methods of adc.Clients :(

**Comment by jarroda** [comment]
We have a project that implements all the stores for EntityFrameworkCore.

**Comment by brockallen** [comment]
The quickstart covers this now: https://identityserver4.readthedocs.io/en/release/quickstarts/8_entity_framework.html
