### ISSUE TITLE
How to enable Azure integration in IdentityServer4 for Core 2.0?

### ISSUE THREAD

**Issue by johnxjcheng** [IdentityServer/IdentityServer4.Samples#210]
The question was originally posted here: 
https://stackoverflow.com/questions/46332180/how-to-enable-azure-integration-in-identityserver4-for-core-2-0

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!

**Comment by johnxjcheng** [comment]
Apparently, my original post had targeted the free support: StackOverflow. Good to know.
