### ISSUE TITLE
Controller does not allow additional actions

### ISSUE THREAD

**Issue by wluijk** [IdentityServer/IdentityServer4.Samples#211]
I am using this sample controller to add custom actions but a new action with method get is not allowed. Who has the hint? As soon as i add another action i get 404 on all actions of that controller.

    [Route("[controller]")]
    [Authorize]
    public class IdentityController : ControllerBase
    {
        [HttpGet]
        public IActionResult Get()
        {
            return new JsonResult(from c in User.Claims select new { c.Type, c.Value });
        }
        [HttpGet]
        public IActionResult Try()
        {
            return new JsonResult(from c in User.Claims select new { c.Type, c.Value });
        }
    }

**Comment by brockallen** [comment]
Use attribute routing.
