### ISSUE TITLE
Visual Studio Code Issue

### ISSUE THREAD

**Issue by Wigatron** [IdentityServer/IdentityServer4.Samples#212]
Hi All,

I'm having some issues getting Visual Studio Code to operate. 

When I compile a test APP I get the following error. 

Any help is appreciated 

![image](https://user-images.githubusercontent.com/25162134/30889701-a6dfd65a-a36b-11e7-93b6-2a9cc826b6d1.png)

**Comment by brockallen** [comment]
Don't know -- contact Microsoft support.
