### ISSUE TITLE
Question - Can I run the examples in VSCode on my Mac?

### ISSUE THREAD

**Issue by Martin-Andersen** [IdentityServer/IdentityServer4.Samples#216]
Sorry for asking but I am having trouble running the examples in VSCode.

I know how to run them on windows in Visual Studio but in VSCode I only know how to run and build one project.

**Comment by brockallen** [comment]
So then run them from the command line.

**Comment by snailsnot** [comment]
Try right clicking on each project folder and select run in/from (?) terminal.  in each terminal enter: **dotnet run**
