### ISSUE TITLE
Question: Adding a proof key and signature

### ISSUE THREAD

**Issue by Jenan** [IdentityServer/IdentityServer4.Samples#217]
Hello,
I've watched the video with some overview of IdentityServer and posibilities with token called pop token. And there was interesting schema how implement this type of pop token. 

Is it possible to get some examle or some points around this area - pop tokens - for IdentityServer4 and .NET Core?

![pkce](https://user-images.githubusercontent.com/1324242/31049161-9d1fcaca-a62d-11e7-812e-10e81416da11.PNG)
https://speakerdeck.com/leastprivilege/mobile-applications

**Comment by brockallen** [comment]
We don't have pop token support in IdentityServer4 since the attitude on way proof of possession has changed (and the PoP spec was never finalized). The new spec uses the HTTP token binding spec, and they are not yet finalized either.
