### ISSUE TITLE
Code vs Token in Javascript (SPA) Clients

### ISSUE THREAD

**Issue by dendle** [IdentityServer/IdentityServer4.Samples#22]
Hello All,

I have a question about why it is advised to use the implicit flow (response_type=token) in SPA clients.

The main answer is that using the code flow would require the SPA having the client secret somewhere ins the JavaScript, which is easily accessible.

However, if you use the implicit flow, would the actual access token be available in the 'back stack' of the browser?

For example, if a user logs into my SPA, they go through implicit flow, and the access token is returned in the hash fragment at a route somewhere inside the SPA - the SPA gets this value, and clears the hash fragment by redirecting to another route in the SPA (like the homepage).

Lets say you SPA has a Log Out button, that takes them away to the login page.  Couldn't someone easily just keep pressing the back button until the point where the hash fragment re-appears, and then go from there? effectively being logged in as that person again?

Yes, you'd need physical access to the machine, but is there something else I'm missing?

In the same case, if the SPA client used code flow, the one-time code would be rendered useless the next time you tried to exchange it for a token.

And, seeing as the id server will only allow redirects to registered HTTPS urls, I'm not sure which I'd prefer - the client secret being on the SPA, or the back button being a workaround to getting an access token.

I know I'm missing something, could someone tell me what?

Thanks for your advice in advance,
Matt

**Comment by brockallen** [comment]
> Couldn't someone easily just keep pressing the back button until the point where the hash fragment re-appears, and then go from there? effectively being logged in as that person again?

nonce and state prevent this. check the specs.
