### ISSUE TITLE
React redux-oidc

### ISSUE THREAD

**Issue by Hyjaz** [IdentityServer/IdentityServer4.Samples#220]
Hello, I was able to acquire the token using the library oidc-client.js, however currently I have a hard time understanding how to validate the generated token by my identityProvider(Microsoft). 

Basically, whether I make my call with postman, or the client itself with the bearer token, I always get a `401 - Unathorized` response back.

Would you have a sample, where it demonstrate a token that was generated by a different client (in my case my client was made with reactjs) how it can be handle by the backend such that I can use the authorize attribute to protect my webapi.

Again the problem that I am having is that it returns a 401 error.

My client app is registered through azure.
My server web api is also registered through azure, with a different client Id.

When I received my token, I am not able to authenticate to my server? 

Is there some steps that I am missing?

Thank you!! This is a question.

**Comment by brockallen** [comment]
This seems to be a general question about IdentityServer - not a bug report or an issue.

Please use one of the our free or commercial support options

See [here](https://identityserver4.readthedocs.io/en/release/intro/support.html) for more details.

Thanks!
