### ISSUE TITLE
GIT Clone 2.0 release blows up on windows boxes because filename is too long

### ISSUE THREAD

**Issue by osudude** [IdentityServer/IdentityServer4.Samples#221]
> Cloning into 'IdentityServer4.Samples'...
> remote: Counting objects: 4493, done.
> remote: Compressing objects: 100% (83/83), done.
> remote: Total 4493 (delta 33), reused 56 (delta 20), pack-reused 4387
> Receiving objects: 100% (4493/4493), 7.30 MiB | 1.87 MiB/s, done.
> Resolving deltas: 100% (2963/2963), done.
> error: unable to create file Quickstarts/Combined_AspNetIdentity_and_EntityFrameworkStorage/src/IdentityServerWithAspIdAndEF/Data/Migrations/IdentityServer/ConfigurationDb/20171005153917_InitialIdentityServerConfigurationDbMigration.Designer.cs: Filename too long
> error: unable to create file Quickstarts/Combined_AspNetIdentity_and_EntityFrameworkStorage/src/IdentityServerWithAspIdAndEF/Data/Migrations/IdentityServer/PersistedGrantDb/20171005153857_InitialIdentityServerPersistedGrantDbMigration.Designer.cs: Filename too long
> error: unable to create file Quickstarts/Combined_AspNetIdentity_and_EntityFrameworkStorage/src/IdentityServerWithAspIdAndEF/Data/Migrations/IdentityServer/PersistedGrantDb/20171005153857_InitialIdentityServerPersistedGrantDbMigration.cs: Filename too long
> 

Note, git clone worked fine on the 1.0 release.

**Comment by alvachien** [comment]
Same issue.

**Comment by Janidbest** [comment]
same issue 
 

> Quickstarts/Combined_AspNetIdentity_and_EntityFrameworkStorage/src/IdentityServerWithAspIdAndEF/Data/Migrations/IdentityServer/ConfigurationDb/20171005153917_InitialIdentityServerConfigurationDbMigration.Designer.cs: Filename too long
error: unable to create file Quickstarts/Combined_AspNetIdentity_and_EntityFrameworkStorage/src/IdentityServerWithAspIdAndEF/Data/Migrations/IdentityServer/ConfigurationDb/20171005153917_InitialIdentityServerConfigurationDbMigration.cs: Filename too long
error: unable to create file Quickstarts/Combined_AspNetIdentity_and_EntityFrameworkStorage/src/IdentityServerWithAspIdAndEF/Data/Migrations/IdentityServer/PersistedGrantDb/20171005153857_InitialIdentityServerPersistedGrantDbMigration.Designer.cs: Filename too long
error: unable to create file Quickstarts/Combined_AspNetIdentity_and_EntityFrameworkStorage/src/IdentityServerWithAspIdAndEF/Data/Migrations/IdentityServer/PersistedGrantDb/20171005153857_InitialIdentityServerPersistedGrantDbMigration.cs: Filename too long

**Comment by Janidbest** [comment]
Did able to clone using the following command. Git Desktop has the issue.

 $ git clone -c core.longpaths=true https://github.com/IdentityServer/IdentityServer4.Samples
