### ISSUE TITLE
Quickstart Missing signout-redirect.js from wwwroot

### ISSUE THREAD

**Issue by Aeseir** [IdentityServer/IdentityServer4.Samples#224]
Love the work guys. Slight issue with a quickstart seed that can be fixed in seconds
**Quickstart 6: IdentityServer and ASP.NET Identity**
[https://github.com/IdentityServer/IdentityServer4.Samples/tree/dev/Quickstarts/6_AspNetIdentity/src/IdentityServerWithAspNetIdentity](url)

In the source code, wwwroot folder is missing **signout-redirect.js**. So if users request automatic redirect it won't work because **LoggedOut.cshtml** cannot find the file. Not sure if it is intentional or not (still learning about ID4).

Simple fix is to copy the signout-redirect.js from any other quickstart into the folder and it works.

**Comment by brockallen** [comment]
Done

**Comment by Aeseir** [comment]
Sorry @brockallen different timezones lol.

For other peoples benefit another solution is to implement following few steps in the Logout model to bypass the need for the pageload (thus javascript file):

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Logout(LogoutInputModel model)
        {
            // existing code

            // if you don't want identity server to load the LoggedOut page you can redirect automatically
           // check if there is a URI to redirect to
            if (!vm.PostLogoutRedirectUri.IsNullOrEmpty())
            {
                // if there is a URI then redirect
                return Redirect(vm.PostLogoutRedirectUri);
            }
           
            // otherwise continue on and display the logout page
            return View("LoggedOut", vm);
        }

**Comment by brockallen** [comment]
> For other peoples benefit another solution is to implement following few steps in the Logout model to bypass the need for the pageload (thus javascript file):

I'd discourage this approach, as it prevents the signout callback iframe from having a chance to load.

**Comment by Aeseir** [comment]
Interesting didn't consider that. Thanks will review my approach.
