### ISSUE TITLE
At what stage does a client retrieve Bearer Token

### ISSUE THREAD

**Issue by siberianguy** [IdentityServer/IdentityServer4.Samples#226]
I have a typical setup: SPA application, .NET Core Api and Identity Server 4. Authentication is done via Google and I need access to offline_token, so Hybrid grant seems to be the best fit.

I'm looking into Hybrid sampe and I don't get one thing: at what stage am I supposed to pass a BearerToken to my SPA? I expected to see something like that in ExternaLoginCallback but no. Another guess I have is that SPA is supposed to make a request to a TokenEndpoint but how if there's no login and password?

I'm definitely missing something obvious here. Would appreciate a hint in the right direction.

**Comment by brockallen** [comment]
> I have a typical setup: SPA application, .NET Core Api and Identity Server 4. Authentication is done via Google and I need access to offline_token, so Hybrid grant seems to be the best fit.

SPAs use implicit, not hybrid. IOW, they are not allowed to use the offline_access scope.

**Comment by siberianguy** [comment]
But my backend API needs a Googe's offline token to add events to Google Calendar at any moment. As I understand, it's not possible in case of implicit. Can't I have Hybrid flow and send a Bearer token to my SPA at the same time?

**Comment by brockallen** [comment]
Then it's not just a SPA -- it's server and client side code. So then yes, do hybrid from your server side code, and share the access token with your JS client. You will have token lifetime issues to deal with next...

**Comment by siberianguy** [comment]
Do I have to share access token or can I make IdentityServer generate a bearer token to my client? At what stage should I share the token? May be in the redirect url parameter from ExteralLoginCallback? Should I use Oidc or it doesn't support my scenario?

I'm so confused now. Is there any sample doing something similar?

**Comment by brockallen** [comment]
> Is there any sample doing something similar?

No, not for that mixed client/server mode. We do offer consulting services, though.
