### ISSUE TITLE
ResourceOwnerPassword Client is Wrong

### ISSUE THREAD

**Issue by 8jane** [IdentityServer/IdentityServer4.Samples#229]
In the repo (IdentityServer4.Samples/Quickstarts/2_ResourceOwnerPasswords/) the client does not actually use RequestResourceOwnerPasswordAsync. Is is using RequestClientCredentialsAsync from the 1_ClientCredentials project.

**Comment by leastprivilege** [comment]
https://github.com/IdentityServer/IdentityServer4.Samples/blob/release/Quickstarts/2_ResourceOwnerPasswords/src/ResourceOwnerClient/Program.cs

**Comment by 8jane** [comment]
doh!
