### ISSUE TITLE
IdentityServer 4 AspNetIdentity Not Redirecting after register

### ISSUE THREAD

**Issue by beachjf** [IdentityServer/IdentityServer4.Samples#230]
I downloaded the latest version of IdentityServer 4 Sample and I try the AspNetIdentity

1-I start the API
2-I start the Identity Server
3-I start the MVC Client

I click on the Secure link from MVC Client, I'm redirecting to the Login Page properly. At this step, I do not have a user register yet. I click on the register button. the redirect_url seem to be ok.
I register the user, but I'm not redirecting to the MCV client.

I check in the database and my user are created properly. 
I also set EmailConfirmed = true in the database.

An other test I did.
Click On Secure from MVC Client
I'm redirecting to login page
I try to login with my user previously registered.
I'm not redirecting to the MVC CLient.

Thanks

**Comment by brockallen** [comment]
You need to propagate the returnUrl. If you want our sample to do that for you, feel free to submit a PR.

**Comment by lgoudriaan** [comment]
So the demo isn't supposed to redirect back to the mvcclient after a successful login?

Expected flow:
1. Start both sites
2. Click the secure link in the mvc site, I will be redirected to the identityserver
3. I login with my asp.net identity user account.
4. I will be redirected back to the /secure in mvcclient

Or am i missing something? My logs: https://pastebin.com/QSku2y9m

**Comment by brockallen** [comment]
The ASP.NET Identity template is not a good template for building a token server. The sample we put here is trying to show getting started, but you ultimately have to decide for yourself what you want the functionality to be.

**Comment by lgoudriaan** [comment]
The problem was that it wasn't logging in at all. I figured it out, I wasn't running in Https 🤦‍♂️ .
Maybe @beachjf was doing the same?

Anyways thanks @brockallen for your time, and great library 👍
