### ISSUE TITLE
AspNetIdentity and Combined_AspNetIdentity_EF QS ignores acr_values idp and EnableLocalLogin

### ISSUE THREAD

**Issue by vodesoft** [IdentityServer/IdentityServer4.Samples#231]
Hello!

AspNetIdentity and Combined_AspNetIdentity_and_EntityFrameworkStorage quick starts projects both ignore acr_values idp in /connect/authorize as well as Client's EnableLocalLogin settings.

Looks like a commented code of AccountService.BuildLoginViewModelAsync does not have it's fully functional replacement part for AspNet Identity Login page yet. Do you plan to provide QS recomendations how to handle acr_values idp in most correct way for projects use AspNetIdentity?

Thanks!

**Comment by vodesoft** [comment]
This pool request fixes idp handling but leaves EnableLocalLogin issue untouched https://github.com/IdentityServer/IdentityServer4.Samples/pull/232

**Comment by brockallen** [comment]
Yea, it's tricky merging our standard QS UI with the ASP.NET Identity account template.

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by vodesoft** [comment]
There is no related changes applied on any branch yet. So the issue is still be an actulal.

**Comment by brockallen** [comment]
> There is no related changes applied on any branch yet. So the issue is still be an actulal.

Right, because I said this:

> Yea, it's tricky merging our standard QS UI with the ASP.NET Identity account template.

The quickstart for ASP.NET Identity is only trying to show the minimal changes to the ASP.NET template to get started. My point is that if you want that feature, I'd encourage you to add it to your own UI code.

**Comment by brockallen** [comment]
Merged the PR. Thanks
