### ISSUE TITLE
Quickstarts with AspNetIdentity return to login after going to page with manage grants

### ISSUE THREAD

**Issue by Jenan** [IdentityServer/IdentityServer4.Samples#233]
I have tried the quickstarts with AspNetIdentity and if I am login and try go to the page called `/grants` then  I am automaticly redirected to login page.

Why is used in GrantsController the Authorization attribute with this schema? -

`[Authorize(AuthenticationSchemes = IdentityServer4.IdentityServerConstants.DefaultCookieAuthenticationScheme)]`

How can I fix it?

Thank you.

**Comment by brockallen** [comment]
Change the scheme to be the same name as the cookie scheme used by ASP.NET Identity. Also, feel free to send a PR with the fix to us.

**Comment by Jenan** [comment]
I've created the PR.
