### ISSUE TITLE
Redirect after logout not working (IdentityServer4)

### ISSUE THREAD

**Issue by AamirTamtec** [IdentityServer/IdentityServer4.Samples#242]
redirect not working when logout called, post_logout_redirect_uri is defined correct but logoutid is null
No error but remains on the same page

public async Task<IActionResult> Logout(LogoutViewModel model)//int? logoutId//
{
    await HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);
    await HttpContext.SignOutAsync();
 }
PostLogoutRedirectUris = new List<string>
 {
    "http://127.0.0.1:5000/signout-callback-oidc"
 }

**Comment by AamirTamtec** [comment]
Using IdentityServer4 2.0.1 and AspNetCore 2.0.0

**Comment by brockallen** [comment]
And what do the logs say?

**Comment by AamirTamtec** [comment]
No error on the log but it stayed on the same page

dbug: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[9]
      AuthenticationScheme: Identity.Application was not authenticated.
trce: IdentityServer4.Hosting.EndpointRouter[0]
      No endpoint entry found for request path: /account/logout
dbug: Microsoft.AspNetCore.Routing.Tree.TreeRouter[1]
      Request successfully matched the route with name '(null)' and template 'Account/Logout'.
dbug: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action TTIdentityServer.Controllers.AccountController.Logout (TTIdentityServer)
dbug: Microsoft.AspNetCore.Mvc.ViewFeatures.CookieTempDataProvider[1]
      The temp data cookie .AspNetCore.Mvc.CookieTempDataProvider was not found.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Executing action method TTIdentityServer.Controllers.AccountController.Logout (TTIdentityServer) with arguments (TTIdentityServer.Models.AccountViewModels.LogoutViewModel) - ModelState is Invalid
info: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[11]
      AuthenticationScheme: idsrv signed out.
info: Microsoft.AspNetCore.Authentication.Cookies.CookieAuthenticationHandler[11]
      AuthenticationScheme: Identity.External signed out.
dbug: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action method TTIdentityServer.Controllers.AccountController.Logout (TTIdentityServer), returned result Microsoft.AspNetCore.Mvc.EmptyResult.
info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
      Executed action TTIdentityServer.Controllers.AccountController.Logout (TTIdentityServer) in 1266.6628ms
dbug: Microsoft.AspNetCore.Server.Kestrel[9]
      Connection id "0HL9BD23U48QH" completed keep alive response.
info: Microsoft.AspNetCore.Hosting.Internal.WebHost[2]
      Request finished in 1531.466ms 200

**Comment by AamirTamtec** [comment]
After removing FrontChannelLogoutUri getting this..Have access token but not the id_token


fail: IdentityServer4.Validation.TokenValidator[0]
      Unknown or disabled client: http://127.0.0.1:5000/resources.
info: IdentityServer4.Validation.EndSessionRequestValidator[0]
      End session request validation failure: Error validating id token hint
      {
        "SubjectId": "unknown",
        "Raw": {
          "id_token_hint": "eyJhbGciOiJSUzI1NiIsImtpZCI6IjMxMGFiZjI3ZTg4NTc5N2U1MThkYWZhNGQyMDliZWQ2IiwidHlwIjoiSldUIn0.eyJuYmYiOjE1MTA2NzAwNjQsImV4cCI6MTUxMDY3MzY2NCwiaXNzIjoiaHR0cDovLzEyNy4wLjAuMTo1MDAwIiwiYXVkIjpbImh0dHA6Ly8xMjcuMC4wLjE6NTAwMC9yZXNvdXJjZXMiLCJ0cml0aXVtIl0sImNsaWVudF9pZCI6IlRyaXRpdW1OZyIsInN1YiI6ImNhNDM0OTdlLTVlM2YtNDUxYS04ZTliLTRmNWI0ZGJjNGJmNiIsImF1dGhfdGltZSI6MTUxMDY3MDA2MywiaWRwIjoibG9jYWwiLCJuYW1lIjoiYW1pci5tYW5zb29yaUB0YW10ZWNoLm9yZyIsIkFzcE5ldC5JZGVudGl0eS5TZWN1cml0eVN0YW1wIjoiNjE2MTY1MGEtOTg3YS00OWFhLWJhMmQtNjczNDkzNTQzMzZjIiwic2NvcGUiOlsib3BlbmlkIiwicHJvZmlsZSIsImVtYWlsIiwiY3VzdG9tLnByb2ZpbGUiLCJ0cml0aXVtIiwib2ZmbGluZV9hY2Nlc3MiXSwiYW1yIjpbInB3ZCJdfQ.MWVvq-nitBmp2EBj6yL_QpUgPPnlMGWXzVtzc0PNeI_IYaIBqW4153TgEqoLhOmGKxSxydmwASK27qRqS_o1m6W2Qawo9DgCPLxVakgnLiqNbu73ORB37Q4_UNc1KcpnRtIW7hEzrStU-6rZx2h6EpCZQs9s4LoD-0tiepJU-LAlKXsyw_EQJjsAyRDyf94x1lLg_wO0ereCA-8TF1TMsIqvr5124QRQE1cIfWFPkTZosUQpzRFEXSt-0nPv4fxLUeUTT5tYhUbNuMCaXgx_rE_pHh-VM-eizOSiSbwyWIIy-vVKZorl5o8HIUEb1SchQHau9G8_Bh4gzhl8ceigsQ",
          "post_logout_redirect_uri": "http://127.0.0.1:5000/index.html"
        }
      }
fail: IdentityServer4.Endpoints.EndSessionEndpoint[0]
      Error processing end session request Invalid request

**Comment by brockallen** [comment]
Are you sending the access token as the id_token_hint?

**Comment by AamirTamtec** [comment]
yes. even though i have added openid but not getting id_token

i have defined AllowedGrantTypes = HybridAndClientCredentials

**Comment by brockallen** [comment]
Not sure then. I'd test with our working samples and then compare that to your project.

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by AamirTamtec** [comment]
Are there any samples for IdentityServer4 with AspNetCore2.0 ?

**Comment by brockallen** [comment]
They're all updated for ASP.NET Core 2.

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
