### ISSUE TITLE
Is there a Angular version of Quickstart UI?

### ISSUE THREAD

**Issue by taigosantos** [IdentityServer/IdentityServer4.Samples#243]
Could someone explain to me why the IdentityServer4 UI Quickstart is made in an MVC project? Is there any explanation or restriction regarding safety? Could this example UI Quickstart be in Angular? Is there a project that, instead of using the example UI Quickstart in MVC, is using Angular?

**Comment by brockallen** [comment]
You mean why is the JS quickstart a MVC host?

**Comment by andreasano** [comment]
Hi Tiago,

I found a project close to what you want. Still, the angular part is
embedded to a mvc project but after some work to do, you can decouple them.

https://github.com/elanderson/Angular-Core-IdentityServer


 Hope it helps.

Andre Asano

**Comment by taigosantos** [comment]
Nice thanks man... @andreasano 

I would very much like to know why a UI Web Server App (Mvc Razor) was used instead of a JS UI (Angular) such as Quickstart. It has something to do with security, or simply choice of the IdentityServer developers

**Comment by taigosantos** [comment]
Yeas @brockallen

**Comment by brockallen** [comment]
> You mean why is the JS quickstart a MVC host?

Well, we need some host. We could have used node.js, but most people using IdentityServer are coming from a .NET background. That's all.

**Comment by brockallen** [comment]
Closing. If you still have issues, feel free to reopen.
