### ISSUE TITLE
Git clone issues

### ISSUE THREAD

**Issue by kuncevic** [IdentityServer/IdentityServer4.Samples#245]
Just cloned the repo and got this errors:

> git clone https://github.com/IdentityServer/IdentityServer4.Samples
> Cloning into 'IdentityServer4.Samples'...
> remote: Counting objects: 4629, done.
> remote: Compressing objects: 100% (47/47), done.
> remote: Total 4629 (delta 29), reused 28 (delta 15), pack-reused 4565
> Receiving objects: 100% (4629/4629), 7.02 MiB | 731.00 KiB/s, done.
> Resolving deltas: 100% (3092/3092), done.
> error: unable to create file Quickstarts/Combined_AspNetIdentity_and_EntityFrameworkStorage/src/IdentityServerWithAspIdAndEF/Data/Migrations/IdentityServer/ConfigurationDb/20171005153917_InitialIdentityServerConfigurationDbMigration.Designer.cs: Filename too long
> error: unable to create file Quickstarts/Combined_AspNetIdentity_and_EntityFrameworkStorage/src/IdentityServerWithAspIdAndEF/Data/Migrations/IdentityServer/PersistedGrantDb/20171005153857_InitialIdentityServerPersistedGrantDbMigration.Designer.cs: Filename too long
> Checking out files: 100% (1653/1653), done.
> fatal: unable to checkout working tree
> warning: Clone succeeded, but checkout failed.
> You can inspect what was checked out with 'git status'
> and retry the checkout with 'git checkout -f HEAD'

Windows 10

**Comment by urbanhusky** [comment]
I had the same issue :)

Set git options to allow long filenames:
https://stackoverflow.com/questions/21123415/git-pull-aborted-with-error-filename-too-long

Either globally:
`git config --system core.longpaths true`

Or just for that repository:
Open the `.git/config` file (in the folder where the repo is)

```
[core]
    repositoryformatversion = 0
    filemode = false
    ...
    longpaths = true        <-- (add this line under core section)
```

**Comment by brockallen** [comment]
Yea, this is a windows issue.
