### ISSUE TITLE
Database contexts should not be disposed in seed method

### ISSUE THREAD

**Issue by urbanhusky** [IdentityServer/IdentityServer4.Samples#246]
Hi,

I think that the database contexts should not be disposed in the seed method, because their lifecycle is tied to the scope:

https://github.com/IdentityServer/IdentityServer4.Samples/blob/be539a2453a3fa90599609d1a71ffd067aafb115/Quickstarts/8_EntityFrameworkStorage/src/QuickstartIdentityServer/SeedData.cs#L12-L32

The contexts get disposed due to the `using` statement, but the `IServiceProvider.GetRequiredService` will always return the same context (within the scope). This most likely does not cause an issue in your code because you don't make use of the service again, but it is a template that could get other users into trouble.

For example: 
I used similar code and migrated databases from within an `using` block. I then got exceptions (`NullReferenceException`) when I tried to use an ASP.NET Core 2.0 Identity `UserManager`.
The disposed context was injected into the `UserManager`. 
So either using the context again, or a service that resolves it via DI, will cause issues.

**Comment by brockallen** [comment]
This is the most up to date version: https://github.com/IdentityServer/IdentityServer4.Samples/blob/dev/Quickstarts/8_EntityFrameworkStorage/src/QuickstartIdentityServer/SeedData.cs#L16

**Comment by urbanhusky** [comment]
I used a permalink to the, at the moment of writing, most up to date version. 
The issue exists on the current `dev` HEAD

_Link to current (at any moment >= time of writing) version_
https://github.com/IdentityServer/IdentityServer4.Samples/blob/dev/Quickstarts/8_EntityFrameworkStorage/src/QuickstartIdentityServer/SeedData.cs#L16-L28

- L16: The scope is created. Any resolutions of database contexts within this scope will be scoped. _Should be scoped because they should be registered scoped. `services.AddDbContext(…)` does exactly that. https://docs.microsoft.com/en-us/aspnet/core/fundamentals/dependency-injection_
- L18: The `PersistedGrantDbContext` is resolved. Its lifecycle is tied to the scope
- L21: The `PersistedGrantDbContext` is disposed. Resolving it again, yields the same **disposed** context. 
- L23 & L27: same as above, but for `ConfigurationDbContext`

Both contexts are now disposed. If a user would copy this pattern, they would end up with exceptions if they tried something like this again:
```
using (var context = scope.ServiceProvider.GetRequiredService<ConfigurationDbContext>())
{
    // context is already disposed
}
```

In my case it happened with ASP.NET Core Identity but the same exact pattern:
```
using (var context = serviceProvider.GetRequiredService<ApplicationDbContext>())
{
    context.Database.Migrate();
}

using (var userManager = serviceProvider.GetRequiredService<UserManager<ApplicationUser>>()=
{
    var adminUsers = userManager.Users.Where(user => user.IsAdmin); // throws NullReferenceException once evaluated
}

**Comment by urbanhusky** [comment]
Or, in short:
Do not dispose database contexts (or any _Scoped_ object)

**Comment by brockallen** [comment]
Ah,. I see what you're saying -- I was confused. You mean don't use the `using` statement because the `scope` will do the `Dispose()`. Yes, good point.

**Comment by brockallen** [comment]
Fixed. Thanks.

**Comment by urbanhusky** [comment]
Glad I could help 👍
