### ISSUE TITLE
Quickstart 6_AspNetIdentity build error with context.IdP

### ISSUE THREAD

**Issue by stephenjr** [IdentityServer/IdentityServer4.Samples#247]
File IdentityServer4.Samples/Quickstarts/6_AspNetIdentity/src/IdentityServerWithAspNetIdentity/Controllers/AccountController.cs contains the following code in the Login method:

`            if (context?.IdP != null && (await _signInManager.GetExternalAuthenticationSchemesAsync()).Any(p => string.Equals(p.Name, context.IdP, StringComparison.InvariantCultureIgnoreCase)))
            {
                return ExternalLogin(context.IdP, returnUrl);
            }
`
This causes the build error CS0103	The name 'context' does not exist in the current context.

**Comment by BrettBailey** [comment]
Just hit same compile issue in the combined aspnet & ef example on both release and dev branches
https://github.com/IdentityServer/IdentityServer4.Samples/blob/release/Quickstarts/Combined_AspNetIdentity_and_EntityFrameworkStorage/src/IdentityServerWithAspIdAndEF/Controllers/AccountController.cs

**Comment by BrettBailey** [comment]
Added a PR here https://github.com/IdentityServer/IdentityServer4.Samples/pull/248
