### ISSUE TITLE
[PROPOSAL] Update this IdentityServer4.Samples to use ASP.NET Core 2.0

### ISSUE THREAD

**Issue by eriawan** [IdentityServer/IdentityServer4.Samples#249]
Could I propose to update this IdentityServer4.Samples to use ASP.NET Core 2.0?

If accepted, I will create separate WIP PR to update these samples to use ASP.NET Core 2.0 🙂 

cc @brockallen and @leastprivilege

**Comment by leastprivilege** [comment]
which samples?

**Comment by eriawan** [comment]
@leastprivilege 
Apologize. 
I mean this sample: https://github.com/IdentityServer/IdentityServer4.Samples/tree/release/NodeJsApi

**Comment by leastprivilege** [comment]
We gonna remove this sample, since it is not maintained anymore.

**Comment by eriawan** [comment]
Ok, thanks! 
Could I also update the remaining code samples to update the IdentityServer to use IdentityServer version 2.0.5? Afaik, this is the current stable version on nuget.org.
