### ISSUE TITLE
User.Identity.Name is not set after authentication

### ISSUE THREAD

**Issue by iAlexanderMoon** [IdentityServer/IdentityServer4.Samples#25]
```
Hello,

I have run the following sample: Clients/src/MvcImplicit/Views/Home/Index.cshtml

@if(User.Identity.IsAuthenticated)
{
    <h1>Logged in as: @User.Identity.Name</h1>
}
else
{
    <h1>Not Logged In</h1>
}

and added similar code to sample: MVC and API/src/AspNetCoreAuthentication/Views/Home/Index.cshtml

Both acknowledge that the user is now logged in, however neither displays the name.

In previous versions I remember handling AuthorizationCodeReceived and creating a ClaimsIdentity while setting the key of the claim containing the name (JwtClaimTypes.PreferredUserName).

Is there something similar that needs to be done that is missing from the samples?

Thanks for the help. IdentityServer is great.
```

**Comment by iAlexanderMoon** [comment]
Okay, I think I figured it out. Requested "profile" scope and adding TokenValidationParameters specifying the NameClaimType to "name" got it to work.
 ```
            var oidcOptions = new OpenIdConnectOptions
            {
                AuthenticationScheme = "oidc",
                SignInScheme = "cookies",

                Authority = Clients.Constants.BaseAddress,
                RequireHttpsMetadata = false,
                ClientId = "mvc_implicit",
                ResponseType = "id_token token",
                SaveTokens = true,

                TokenValidationParameters = new TokenValidationParameters() { NameClaimType = "name" }
            };
```

**Comment by killermouse** [comment]
I have the same problem, and your solution didn't work for me!

**Comment by iAlexanderMoon** [comment]
What claim types are you getting back from the response? It may be different depending on how the server is configured. You may not have a NameClaimType "name".

**Comment by killermouse** [comment]
I'am using the basic samples:

**Comment by killermouse** [comment]
new InMemoryUser{
                    Subject = "818727",
                    Username = "alice",
                    Password = "alice",
                    Claims = new Claim[]
                    {
                        new Claim(JwtClaimTypes.Name, "Alice Smith"),
                        new Claim(JwtClaimTypes.GivenName, "Alice"),
                        new Claim(JwtClaimTypes.FamilyName, "Smith"),
                        new Claim(JwtClaimTypes.Email, "AliceSmith@email.com"),
                        new Claim(JwtClaimTypes.EmailVerified, "true", ClaimValueTypes.Boolean),
                        new Claim(JwtClaimTypes.Role, "Admin"),
                        new Claim(JwtClaimTypes.Role, "Geek"),
                        new Claim(JwtClaimTypes.WebSite, "http://alice.com"),
                        new Claim(JwtClaimTypes.Address, @"{ 'street_address': 'One Hacker Way', 'locality': 'Heidelberg', 'postal_code': 69118, 'country': 'Germany' }", Constants.ClaimValueTypes.Json)
                    }
                },

**Comment by iAlexanderMoon** [comment]
Well JwtClaimTypes.Name = "name" so it's not that.

**Comment by killermouse** [comment]
where you define that claim and how?!

**Comment by krissaspdev** [comment]
I had the same problem (MvcImplicit client sample)
Adding line TokenValidationParameters = new TokenValidationParameters() { NameClaimType = "name" } is sufficient
The only problem is a fact that there is no "name" claim included in the Token.
I added this manually to sql table (while testing Entity Framework Core persistence layer) and it works as expected, but it's not a right solution. It seems that this is IdentityServer4 issue, but I'm not sure...

**Comment by virshu** [comment]
I realize it's a fairly old thread (5 months sounds like eternity), but I have the same problem. User.Identity.Name is null after login. Adding line `TokenValidationParameters = new TokenValidationParameters() { NameClaimType = "name" }` didn't help. I *do* see a claim, though, and I can get it by `User.FindFirst("name").Value`, but it doesn't seem right. Is User.Identity.Name supposed to be null? Or I am doing something wrong? Thanks

**Comment by brockallen** [comment]
Make sure you're requesting a scope that includes the name claim.

**Comment by virshu** [comment]
Hi Brock. Thank you for your response. Although I am not sure what you mean - none of the scopes in `IdentityServer4.Models.StandardScopes` include "the name claim", as far as I can understand, but your comment pointed me in the right direction. [http://docs.identityserver.io/en/dev/quickstarts/5_hybrid_and_api_access.html](The example) (Modifying the MVC client section) uses `ResponseType = "code id_token"`. When I changed to `ResponseType = "code id_token token"`, as in the question above, it all started working. I wish I understand better what these response types mean, but at least for now it works! Thanks a lot!

**Comment by raffaeu** [comment]
Even if the post is a bit old, I think is correct to explain why it doesn't work for some of you.
As mentioned by @brockallen, Identity Server, on the client side, allows you to configure the **scopes**. These scopes are nothing else than a list of information (claims) that we can retrieve from the authenticated user.

If you look at this demo application:
https://github.com/IdentityServer/IdentityServer4.Samples/blob/release/Clients/src/MvcHybrid/Startup.cs

The code is working because they return plenty of **scopes**:
```c#
ResponseType = "code id_token",
Scope = { "openid", "profile", "email", "api1", "offline_access" },
GetClaimsFromUserInfoEndpoint = true,
```

Also notice the property `GetClaimsFromUserInfoEndpoint`?

While the suggestion of @virshu is not correct because if you pass also the `token` option in the respose type, you make your cookie unsecure because it will contain also the bearer token, which is something you don't want inside the cookie.

**Comment by elfarouqy** [comment]
Hello,
Some body help me i can't get name after authentication
.net Core Server and Mvc Net Client thanks to answer me

**Comment by raffaeu** [comment]
Did you properly grant permissions to the correct claims? Because
Identity.Name is a claim.

**Comment by elfarouqy** [comment]
Thanks raffaeu for your answer 
yes but when i wanna call name in project aspnet without core i cant get name when i add this code in statup 
TokenValidationParameters = new TokenValidationParameters
                {
                    NameClaimType = "name",
                    RoleClaimType = "role",
                }

i got error

**Comment by raffaeu** [comment]
Compilation error or Runtime error? Are you sure you have the correct Nuget
packages?

**Comment by elfarouqy** [comment]
Yes it work when i connect Server Asp .net Core with Mvc 5 asp .net Core but when i connect Server .net Core with Mvc 5 Asp Net  i got error and when i remove this code 
TokenValidationParameters = new TokenValidationParameters
{
NameClaimType = "name",
RoleClaimType = "role",
}
it work but i can't get name in claim

**Comment by raffaeu** [comment]
I don't think you can use it without net core, at least not the identity
server 4 packages.

**Comment by elfarouqy** [comment]
yes it work with openidconnect but after authentication i get ID user but i cant get name and role this is my probleme

**Comment by elfarouqy** [comment]
yes  with identityServer4

**Comment by elfarouqy** [comment]
Hello
can you tell me how can i get Role From .net Core Server to Asp MVC 5 Net 
+ i get name but role no thanks to answer me :D

**Comment by Shadowman4205** [comment]
@raffaeu 
Hello,  i am user node app. i passing for the moment as responseType: "code id_token token"
u said this is wrong, but if i do not pass access token i get only id_token, how can o use this to get userinfo name,fullname,email, claims? And also what u mean access_token passed to cookies? when, at identity server? how disallow that?

**Comment by farshid3003** [comment]
I have role problem as well
My IDS server is core 2.0 
I use it with old mvc client and every thing is correct but with .net core 2.0 client I cannot get roles

**Comment by farshid3003** [comment]
I found the problem
I handle on user information receive event 
 options.Events.OnUserInformationReceived = OnUserInformationReceived; 

and I saw that role is an array now:
{[role, [  "SuperAdmin",  "Admin",  "LdapUser",  "TranslationAdmin",  "dev",  "admin",  "CSM_User"]]}

**Comment by farshid3003** [comment]
https://github.com/aspnet/Security/issues/1449
https://github.com/aspnet/Security/pull/1501
