### ISSUE TITLE
missing assembly of "Microsoft.AspNetCore.Antiforgery"

### ISSUE THREAD

**Issue by silentrock** [IdentityServer/IdentityServer4.Samples#250]
The following error was reported when I downloaded the updated identityServer4.Samples:

> An assembly specified in the application dependencies manifest (identityserverwithaspidandef.deps.json) was not found:
  package: 'Microsoft.AspNetCore.Antiforgery', version: '2.0.1'
  path: 'lib/netstandard2.0/Microsoft.AspNetCore.Antiforgery.dll'
This assembly was expected to be in the local runtime store as the application was published using the following target manifest files:
  aspnetcore-store-2.0.3.xml

The error was temporarily fixed when I rewinded Microsoft.AspNetCore.All from version 2.0.3 to 2.0.0, but not sure how it happened.

**Comment by leastprivilege** [comment]
You probably don't have the latest version of the .NET SDK.

**Comment by silentrock** [comment]
It is, indeed I had .NET SDK version 2.0.0. Thanks!
