### ISSUE TITLE
500 when cancelling external login (Quickstart4_ExternalAuthentication)

### ISSUE THREAD

**Issue by jameswilddev** [IdentityServer/IdentityServer4.Samples#251]
- Open Quickstart4_ExternalAuthentication.
- Click "Click here to manage your stored grants.".
- Click "External Login" > "OpenID Connect".
- Click "Cancel".

`
An unhandled exception occurred while processing the request.
OpenIdConnectProtocolException: Message contains error: 'access_denied', error_description: 'error_description is null', error_uri: 'error_uri is null'.
`

Looks resolvable via this: https://github.com/openiddict/openiddict-core/issues/334#issuecomment-273487558

Not sure if it applies to the other external sign-in options.

**Comment by brockallen** [comment]
That's Microsoft throwing the exception, not us. Ask them about it, please.

**Comment by jameswilddev** [comment]
Microsoft's advice is to handle the event: https://github.com/aspnet/Security/issues/710#issuecomment-192018610

**Comment by brockallen** [comment]
So then handle it how you see fit in your application. I'm not clear what you're asking us to do.

**Comment by jameswilddev** [comment]
I might be misunderstanding, but wouldn't it be correct for the sample to handle it, to demonstrate a best-practices implementation of external identity providers?

**Comment by brockallen** [comment]
> I might be misunderstanding, but wouldn't it be correct for the sample to handle it, to demonstrate a best-practices implementation of external identity providers?

Sure, we could show it in the samples. Please submit a PR, then.
