### ISSUE TITLE
Request an Angular2 client

### ISSUE THREAD

**Issue by byunru** [IdentityServer/IdentityServer4.Samples#26]
Request an Angular2 client project.

**Comment by brockallen** [comment]
For writing a JS client, we suggest using oidc-client-js: https://github.com/IdentityModel/oidc-client-js. The beta is based on es6.

**Comment by damienbod** [comment]
Hi @byunru 
Here's an example of an Angular 2 client:

https://github.com/damienbod/AspNet5IdentityServerAngularImplicitFlow/tree/master/src/Angular2Client

https://damienbod.com/2016/03/02/angular2-openid-connect-implicit-flow-with-identityserver4/

If you want to use the OIDC library from @brockallen, it should be easy enough to replace the oidc logic with the library. 

Auth0 also provide an OIDC Angular 2 client with could be used together with IdentityServer4

Greetings Damien

**Comment by PivotalAnimal** [comment]
Thanks for bringing this to our attention.
