### ISSUE TITLE
dotnet restore error

### ISSUE THREAD

**Issue by thiagodds** [IdentityServer/IdentityServer4.Samples#27]
I tried restore the IdentityServer project packages with `dotnet restore` (using RC2) and I came across this error:

> Unable to resolve 'IdentityServer4 (>= 1.0.0-beta2)' for '.NETCoreApp,Version=v1.0'.

After that, I created a new empty project and I added IdentityServer4. The same error happens.

**Comment by leastprivilege** [comment]
https://www.nuget.org/packages/IdentityServer4/

**Comment by thiagodds** [comment]
Still not working.
![restore error](https://cloud.githubusercontent.com/assets/2293088/15448612/6e3348fe-1f3d-11e6-8957-1d458f287c97.png)

What else could be wrong with my environment?

**Comment by damienbod** [comment]
Hi @thiagodds 

The nuget online packages are disabled in your visual studio. Under Tools/NuGet Package Manager/Package Manager Settings/Package Sources,  enable the NuGet feed. (checked checkbox)

Greetings Damien

**Comment by thiagodds** [comment]
Thanks @damienbod, works.
