### ISSUE TITLE
IdentityServer4 and Entity Framework

### ISSUE THREAD

**Issue by killermouse** [IdentityServer/IdentityServer4.Samples#28]
Will be released one version where IdentityServer4 works together with asp.net Entity Framework?

Best regards

**Comment by ericgreenmix** [comment]
Here is an implementation.

https://www.nuget.org/packages/TwentyTwenty.IdentityServer4.EntityFrameworkCore/

**Comment by killermouse** [comment]
I would like to see a example with two or more applications, where one is the Identity server and the others the clients. 
In the identity server, the users and roles cames from Entity Framework tables.
The clients applications make single sign on, in identity server application, and have to respect some roles.

Thank you and best regards
