### ISSUE TITLE
ValidateAccessTokenAsync

### ISSUE THREAD

**Issue by walid1001** [IdentityServer/IdentityServer4.Samples#31]
Hi
I'm  trying to implement ActAsGrantValidator on an identity server and I facing an issue on ValidateAsync at ValidateAccessTokenAsync which just stuck  without any return value.

am I missing something ?

Thank you for your help.

**Comment by leastprivilege** [comment]
tbh we are still in the process of getting the foundation right for core. I haven't done any extensive testing with custom grants. 

Tell us more what you are trying to do and in problems you are running exactly.

**Comment by chippiearnold** [comment]
You might be getting the same deadlock issue I was having, particularly if you are using Entity Framework for your client store. Try changing the line in your ActAsGrantValidator:

from this:
`var result = _validator.ValidateAccessTokenAsync(param).Result;`

to this:
`var result = Task.Run(() =>_validator.ValidateAccessTokenAsync(param)).Result;`

It worked for me.

**Comment by brockallen** [comment]
All set on this issue -- can we close?

**Comment by brockallen** [comment]
We released rc4 this week with some significant resource configuration changes. please see the updates (https://leastprivilege.com/2016/12/01/new-in-identityserver4-resource-based-configuration/) and if you have further issues, please ping us here, or open a new issues.
