### ISSUE TITLE
Microsoft.DotNet.Props was not found

### ISSUE THREAD

**Issue by rogersbrad** [IdentityServer/IdentityServer4.Samples#32]
I downloaded the zip file, extracted, opened the solution file.  Solution MVC and API failed to load,

`C:\Users\zzzz\Downloads\IdentityServer4.Samples-dev\IdentityServer4.Samples-dev\MVC and API\src\Api\Api.xproj : error  : The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Users\zzzz\Downloads\IdentityServer4.Samples-dev\IdentityServer4.Samples-dev\MVC and API\src\Api\Api.xproj`

Trying to apply Authentication and my own Roles into an MVC Project, thanks

**Comment by joaomello** [comment]
Did tou install https://www.microsoft.com/net/core#windows?

**Comment by rogersbrad** [comment]
Ok, Installed this from your link.  Tried running again, the Start button shows "IIS Express".  it sits there and tries to Build, maybe stuck in some infinite loop.  Looked frozen, have to wait until its doing something, loading symbols.  It took over 5 minutes looked frozen. 

Browser page is up.  1 word clickable link: Secure.

  click that?  throws an exception:  
An unhandled exception occurred while processing the request.
WinHttpException: A connection with the server could not be established
System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

web.config:
`<?xml version="1.0" encoding="utf-8"?>
<configuration>

  

  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified"/>
    </handlers>
    <aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" stdoutLogEnabled="false" stdoutLogFile=".\logs\stdout" forwardWindowsAuthToken="false"/>
  </system.webServer>
</configuration>`

What is supposed to happen?  Do I take MVC components from this and insert into my project?

then Dependencies - not installed: 

npm - not installed, and in that folder: gulp, gulp-concat, gulp-cssmin, gulp-uglify, rimraf

ok... 'gulp' is new.  had never heard of it before.

**Comment by rogersbrad** [comment]
Solved the problem:
1.  I reloaded the source again, renamed it with 'zzz' on the name to spot it faster
2.  went into Windows Firewall and made an exception for port 44337
3.  in Startup.cs modified line 38/39 to comment out line 38

//[assembly: OwinStartup(typeof(StartupWithLocalhostSecurity))]
[assembly: OwinStartup(typeof(StartupWithHostCookiesSecurity))]

4.  When the browser appears and has the error: forbidden 403  just add the /idm  to the root path, and it works.

**Comment by nelegatti** [comment]
joaomello commented on 14 Jun 2016
thanks !!

**Comment by kishoretvk** [comment]
For visual studio 2015, with adk 1.03 we still ge this, howeve vs2015 comes with different sdk. and
will the global json fix the issue ? can thre be a proper fix ?

any of the dotnet coer sdk's have this folder installed

preview
1.0.1
1.0.3 seems this a prvailig issue from last 2 releases of dotnet core.
however i was able to fix it when i added global.json and did dotnet restore.
Note: dotnet restore at soltion level folder was not fixing the issue. i when into the folder for project level and had to dotnet restoe.
at solution level

it throws another error, saying dotnet props not found , file exists on disk !!

**Comment by leastprivilege** [comment]
VS2015 is not supported anymore. Get VS2017 (e.g. the community edition)
