### ISSUE TITLE
JWT "aud" value coming from where?

### ISSUE THREAD

**Issue by obosha** [IdentityServer/IdentityServer4.Samples#33]
Using out-of-the-box sample, I see the "aud" value in my JWT (using client credential flow for a test client I registered) is set to "http://localhost:5000/resources" and I can't for the life of me figure out, or even guess where that value is coming from.

That base address is the IdentityServer address in the sample itself, and I couldn't tell you where "resources" is coming from.

My understanding is that "aud" should be set to the address of the "resource" that you're trying to access in the OAuth world.

Am I missing something?

**Comment by obosha** [comment]
I found the code, and I'm questioning it's validity.  In "DefaultTokenService.cs" (of IdentityServer4), it has a CreateAccessTokenAsync method.

It assigns to the audience value:

Audience = string.Format(Constants.AccessTokenAudience, **issuer**.EnsureTrailingSlash())

But the issuer shouldn't be assigned to a token's audience value as far as I'm aware.

Just a heads up.

**Comment by obosha** [comment]
I went ahead and re-posted this comment on the IdentityServer4 Issues list since it really applies there, and not to the samples themselves.

Thanks.

**Comment by brockallen** [comment]
The "/resources" is hard coded as it implies the token is valid at resources protected by IdentityServer. For more fine-grained scoping at a specific resource, then use the scope claim in the payload to ensure valid use.
