### ISSUE TITLE
JSOidc example failed for CORS.

### ISSUE THREAD

**Issue by alvachien** [IdentityServer/IdentityServer4.Samples#34]
Had met tons of error message saying "XMLHttpRequest cannot load http://localhost:1941/.well-known/openid-configuration. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:13550' is therefore not allowed access."

Server: Used the IdentityServer in MVC and API sample.
Client: Used the JSOidc.

I had followed the documentation (https://docs.asp.net/en/latest/security/cors.html) as following:

```
        public void ConfigureServices(IServiceCollection services)
        {
            services.AddCors();

        }

        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            app.UseCors(x => 
                x.AllowAnyOrigin()
                .AllowAnyHeader()
                .AllowAnyMethod()
                .AllowCredentials()
                );
        }
```

It still not working!

Any idea here?

Thanks, Alva

**Comment by alvachien** [comment]
Just figured it out:

```
           // UseCors() must be ahead of UseIdentityServer() !
            app.UseCors(x =>
                x.AllowAnyOrigin()
                .AllowAnyHeader()
                .AllowAnyMethod()
                .AllowCredentials()
                );


            app.UseIdentityServer();

```

Thanks for the great tool anyway.
Alva

**Comment by lamemmv** [comment]
Thank @alvachien , that solution work. It save me a lot of time.
