### ISSUE TITLE
Authentication problem

### ISSUE THREAD

**Issue by killermouse** [IdentityServer/IdentityServer4.Samples#35]
I have three applications, the IdentityServer, clientA and clientB, and i have this problem:
I authenticate me from clientA. Then in clientB the authentication is made automatically, but when is made, the clientA lose the authentication!
Then i authenticate automatically from clientA and lose the authentication from clientB!
What can be the problem?!

**Comment by sunilrav** [comment]
What do you mean by "I authenticate me from clientA". You request a token?

**Comment by brockallen** [comment]
Sorry -- this issue got lost in the mix. Any progress?
