### ISSUE TITLE
JsOidc client - How to renew a expired stored token on page load

### ISSUE THREAD

**Issue by Cybrosys** [IdentityServer/IdentityServer4.Samples#4]
Hi,

I was wondering how one could renew a stored expired token on page load. For example I open up the page the next day when I know the token is expired. I don't want the user to have to go to a log in page.

Would it be ok to check mgr.expired right after the mgr is instantiated and then calling renewTokenSilentAsync?

**Comment by brockallen** [comment]
Yep, that's a fine way, but assumes the user is still logged into the token service.
