### ISSUE TITLE
The dependency IdentityServer4 >= 1.0.0-beta4-update1 could not be resolved.

### ISSUE THREAD

**Issue by sunilrav** [IdentityServer/IdentityServer4.Samples#41]
When I open up the IdentityServer4.xproj, Package restore is failing on on IdentityServer4 1.0.0-beta4-update1. 

The error says "The dependency IdentityServer4 >= 1.0.0-beta4-update1 could not be resolved. 

Any tip on how i can get this project to build? Thanks!

**Comment by leastprivilege** [comment]
Mare sure the Nuget.org Package source is enabled.

**Comment by sunilrav** [comment]
That worked. For some reason I didn't have all the nuget sources enabled. Thank you.
