### ISSUE TITLE
 An unhandled exception was thrown by the application.

### ISSUE THREAD

**Issue by SeenYang** [IdentityServer/IdentityServer4.Samples#44]
Hi guys. When I try to mock up the sample API on ASP.NET Core I got an error that : 
`**warn: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
      Authorization failed for the request at filter 'Microsoft.AspNetCore.Mvc.Authorization.AuthorizeFilter'.**
info: Microsoft.AspNetCore.Mvc.ChallengeResult[1]
      Executing ChallengeResult with authentication schemes ().
**fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HKTANQ5ML0V2": An unhandled exception was thrown by the application.**
System.InvalidOperationException: No authentication handler is configured to handle the scheme: Automatic
   at Microsoft.AspNetCore.Http.Authentication.Internal.DefaultAuthenticationManager.<ChallengeAsync>d__12.MoveNext()`

It occurs when I call a method with [Authorize] tag in API Controller. 

Is there anyone have an idea where would cause this kind of problem?

**Comment by aligin** [comment]
The same error.
I'm using 

    public void ConfigureServices(IServiceCollection services)
        {
            services.AddAuthentication();

            services.AddAuthorization(options =>
            {
                options.AddPolicy("Authenticated", policy => policy.RequireAuthenticatedUser());
                options.AddPolicy(AppConstants.Policies.ManageSystems, policy => { policy.RequireClaim("resolution", AppConstants.Policies.ManageSystems); });
            });
            services.AddMvc();
        }
        public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            JwtSecurityTokenHandler.DefaultInboundClaimTypeMap.Clear();
            app.UseIdentityServerAuthentication(new IdentityServerAuthenticationOptions
            {
                AuthenticationScheme = "Bearer",
                Authority = Configuration[AppConstants.Authority],
                RequireHttpsMetadata = false,
                AutomaticChallenge = true,
                ScopeName = Configuration[AppConstants.ScopeName],
                ScopeSecret = Configuration[AppConstants.ScopeSecret],
                AutomaticAuthenticate = true,
                //EnableCaching = true,
                //CacheDuration = TimeSpan.FromMinutes(10)
            });
            app.UseMvc();
        }

**Comment by leastprivilege** [comment]
does it work now?

**Comment by leastprivilege** [comment]
can you reproduce with 

https://github.com/IdentityServer/IdentityServer4.Samples/tree/dev/MVC%20and%20API

**Comment by aligin** [comment]
Yep. Excellent reproduces. So what I did. 
I changed launch settings for "Api" project to launch in console (changed port the suggested by visual studio from 5000 to 1773). 
Started Identity in non debug mode and started "Api" in Debug mode. 
Then I call http://localhost:1773/claims and received the InvalidOperationException 	"No authentication handler is configured to handle the scheme: Automatic"

**Comment by aligin** [comment]
Yesterday I made simple middleware based on the IIS source files. And It Works.
In Startup.cs

    public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            app.UseMiddleware<KestrelAuthenticationMiddleware>();

            app.UseIdentityServerAuthentication(new IdentityServerAuthenticationOptions
            {
                Authority = Configuration[AppConstants.Authority],
                RequireHttpsMetadata = false,
                AutomaticChallenge = true,
                ScopeName = Configuration[AppConstants.ScopeName],
                ScopeSecret = Configuration[AppConstants.ScopeSecret],
                AutomaticAuthenticate = true,
                //EnableCaching = true,
                //CacheDuration = TimeSpan.FromMinutes(10)
            });
            app.UseMvc();
        }

    public class KestrelAuthenticationMiddleware
    {
        private readonly RequestDelegate _next;
        public KestrelAuthenticationMiddleware(RequestDelegate next)
        {
            _next = next;
        }
        public async Task Invoke(HttpContext context)
        {
            var existingPrincipal = context.Features.Get<IHttpAuthenticationFeature>()?.User;
            var handler = new KestrelAuthHandler(context, existingPrincipal);
            AttachAuthenticationHandler(handler);
            try
            {
                await _next(context);
            }
            finally
            {
                DetachAuthenticationhandler(handler);
            }
        }

        private void AttachAuthenticationHandler(KestrelAuthHandler handler)
        {
            var auth = handler.HttpContext.Features.Get<IHttpAuthenticationFeature>();
            if (auth == null)
            {
                auth = new HttpAuthenticationFeature();
                handler.HttpContext.Features.Set(auth);
            }
            handler.PriorHandler = auth.Handler;
            auth.Handler = handler;
        }

        private void DetachAuthenticationhandler(KestrelAuthHandler handler)
        {
            var auth = handler.HttpContext.Features.Get<IHttpAuthenticationFeature>();
            if (auth != null)
            {
                auth.Handler = handler.PriorHandler;
            }
        }
    }

    internal class KestrelAuthHandler : IAuthenticationHandler
    {
        internal KestrelAuthHandler(HttpContext httpContext, ClaimsPrincipal user)
        {
            HttpContext = httpContext;
            User = user;
        }

        internal HttpContext HttpContext { get; }

        internal ClaimsPrincipal User { get; }

        internal IAuthenticationHandler PriorHandler { get; set; }

        public Task AuthenticateAsync(AuthenticateContext context)
        {
            if (User != null)
            {
                context.Authenticated(User, properties: null, description: null);
            }
            else
            {
                context.NotAuthenticated();
            }


            if (PriorHandler != null)
            {
                return PriorHandler.AuthenticateAsync(context);
            }

            return Task.FromResult(0);
        }

        public Task ChallengeAsync(ChallengeContext context)
        {
            bool handled = false;
            switch (context.Behavior)
            {
                case ChallengeBehavior.Automatic:
                    // If there is a principal already, invoke the forbidden code path
                    if (User == null)
                    {
                        goto case ChallengeBehavior.Unauthorized;
                    }
                    else
                    {
                        goto case ChallengeBehavior.Forbidden;
                    }
                case ChallengeBehavior.Unauthorized:
                    HttpContext.Response.StatusCode = 401;
                    // We would normally set the www-authenticate header here, but IIS does that for us.
                    break;
                case ChallengeBehavior.Forbidden:
                    HttpContext.Response.StatusCode = 403;
                    handled = true; // No other handlers need to consider this challenge.
                    break;
            }
            context.Accept();


            if (!handled && PriorHandler != null)
            {
                return PriorHandler.ChallengeAsync(context);
            }

            return Task.FromResult(0);
        }

        public void GetDescriptions(DescribeSchemesContext context)
        {
            if (PriorHandler != null)
            {
                PriorHandler.GetDescriptions(context);
            }
        }

        public Task SignInAsync(SignInContext context)
        {
            // Not supported, fall through
            if (PriorHandler != null)
            {
                return PriorHandler.SignInAsync(context);
            }

            return Task.FromResult(0);
        }

        public Task SignOutAsync(SignOutContext context)
        {
            // Not supported, fall through
            if (PriorHandler != null)
            {
                return PriorHandler.SignOutAsync(context);
            }

            return Task.FromResult(0);
        }
    }

**Comment by leastprivilege** [comment]
Can you try the validation middleware from our CI feed? See if that fixes the problem?

http://identityserver4.readthedocs.io/en/dev/intro/packaging.html

**Comment by aligin** [comment]
@leastprivilege It seems to be working fine now. Thanks a lot.

**Comment by leastprivilege** [comment]
ok - will update the package on nuget.

**Comment by leastprivilege** [comment]
update published.
