### ISSUE TITLE
IdS4 with EF6 & BrockAllen.MembershipReboot

### ISSUE THREAD

**Issue by mafshin** [IdentityServer/IdentityServer4.Samples#48]
I have an EF6 model with [MembershipReboot](https://github.com/brockallen/BrockAllen.MembershipReboot) for user management.

How can I configure IdentityServer4 to get user data from EF6 and MembershipReboot?

**Comment by kwaxi** [comment]
Good question, in the IdSrv4 docs I only could find a sample using ASP.NET Core Identity as user service. But no mention of MembershipReboot.

Do the developers still see a future for MembershipReboot or should we already think of a migration?

**Comment by brockallen** [comment]
https://github.com/brockallen/BrockAllen.MembershipReboot/issues/568#issuecomment-222208300

Having said that, you could use MR in IdSvr4 -- there's not reason you can't use EF6 (assuming _net46_, et al.), or build a similar EF Core persistence layer if you want _netcoreapp1.0_. Also, I've been thinking of providing a migration tool -- but that's just an idea right now. I don't really know what would be involved, or if it's even 100% possible (of course the password being the biggest issue to migrate). 

I'd be curious to hear feedback from people here on the issue.

**Comment by kwaxi** [comment]
Hi Brock,

we already had to handle a migration from a custom legacy account store to MembershipReboot and did it by storing the old password a long with the new one that MR takes care of. Therefore we implemented our own AuthenticateLocalAsync which takes care of the password migration from the old (insecure) legacy password store to MR. AuthenticateLocalAsync is the only place were the password is available in plain text to be used for some migration.

I'm personally looking at this rather from a strategic point of view. What I don't want is to get our user accounts stuck in an user account store that isn't actively maintained anymore. So the main question is if the suggestion for IdSrv4 maintainers is to use MR - if no our datasource is already in place for local accounts -  (or some .Net Core version of it) or to plan a migration to ASP.Net Core Identity (how ever this might look).

Of course we will have a close look our functional requirements (and NFOs, too) ... security, multi-tenancy, claims-aware.

Were we see clear improvement potential is validation of usernames, email addresses and passwords. This is were MR lacks a clear interfaces or injection point, so if some major refactoring is done, this would be a suggestion of me make design improvements here.

**Comment by leastprivilege** [comment]
I don't want to speak for Brock - but it seems that MR is at a point where it becomes more community driven (taking responsibility vs suggesting & feature requests) - 

or we accept the fact that ASP.NET Identity has become decent enough that MR is not needed anymore.

**Comment by brockallen** [comment]
https://github.com/brockallen/BrockAllen.MembershipReboot/issues/568#issuecomment-222208300

https://github.com/brockallen/BrockAllen.MembershipReboot/commit/2c74d4b39145b8e0120945917509c0dd0a8bf83b
