### ISSUE TITLE
Getting Users from database

### ISSUE THREAD

**Issue by leo9223** [IdentityServer/IdentityServer4.Samples#5]
Hi, I am not figuring out if I get users from my DB table then how the below code will change.

I shall be very Thankful to you.

var builder = services.AddIdentityServer(options =>
            {
                options.SigningCertificate = cert;
            });
            builder.AddInMemoryClients(Clients.Get());
            builder.AddInMemoryScopes(Scopes.Get());
            builder.AddInMemoryUsers(Users.Get());

**Comment by brockallen** [comment]
Please read the docs or look at our samples. They explain how to do this.

**Comment by leo9223** [comment]
Sir, I am not finding "IdentityServerServiceFactory" in IdentityServer4. The samples I am seeing are using this factory to implement "IUserService" !!

**Comment by brockallen** [comment]
Yes, fair enough -- half of the info is in the docs, but the docs are all focused on v3 (not v4). So you need to implement the `IUserService` and then register that in the ASP.NET 5 DI system. So the docs that you need to read up on are here: https://identityserver.github.io/Documentation/docsv2/advanced/userService.html and even in there only the GetProfile API is the main one. The other APIs are a v3 comcept.

Again, we're still a work in progress porting v3 to v4, and that's why many of the APIs are lingering.

**Comment by leo9223** [comment]
Thank You, Sir I'll look into that : )

**Comment by alzdrak** [comment]
How would you go about registering the UserService in asp.net core?

This is what's being used in IdentityServer3:
```
var factory = new IdentityServerServiceFactory();

var userService = new UserService();
factory.UserService = new Registration<IUserService>(resolver => userService);
```

But how do you register this UserService in IdentityServer4?

`builder.AddInMemoryUsers(Users.Get());` is how you register static users in memory, but I would like to auth users from the DB ad hoc.

Thanks!

**Comment by alzdrak** [comment]
For those interested, this is how I've done it.

```
var builder = services.AddIdentityServer(options =>
{
    options.SigningCertificate = cert;
});

builder.AddInMemoryClients(Clients.Get());
builder.AddInMemoryScopes(Scopes.Get());

builder.Services.AddTransient<IUserService, UserService>();
```

Then just create your UserService. Please see [this stackoverflow](http://stackoverflow.com/questions/35304038/identityserver4-register-userservice-and-get-users-from-database-in-asp-net-core/) for further information.

**Comment by leo9223** [comment]
Thank You @alzdrak  :) :+1:

**Comment by kapoc** [comment]
I did as per alzdrak example but this is what I get then: 

```
An unhandled exception was thrown by the application.
      System.InvalidOperationException: Unable to resolve service for type 'System.Collections.Generic.List`1[IdentityServer4.Core.Services.InMemory.InMemoryUser]' while attempting to activate 'Asw.Yefforts.IdentityServer.Services.LoginService'.
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.Service.PopulateCallSites(ServiceProvider provider, ISet`1 callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
         at Microsoft.Extensions.DependencyInjection.ServiceLookup.Service.CreateCallSite(ServiceProvider provider, ISet`1 callSiteChain)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetResolveCallSite(IService service, ISet`1 callSiteChain)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetServiceCallSite(Type serviceType, ISet`1 callSiteChain)
         at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType, ServiceProvider serviceProvider)
         at System.Collections.Concurrent.ConcurrentDictionaryExtensions.GetOrAdd[TKey,TValue,TArg](ConcurrentDictionary`2 dictionary, TKey key, Func`3 valueFactory, TArg arg)
```

**Comment by alzdrak** [comment]
@kapoc What does your user service look like? I dont think you are initializing it properly with using InMemoryUser. Post your code and I will try to help.

**Comment by kapoc** [comment]
Nevermind, it was just a silly dependency injection bug in my code. Solved it and got it running together with AspNet Identity. Though I heard the rumours that IUserService is going to be changing soon, hopefully not to harshly.

**Comment by leastprivilege** [comment]
IUserService is gone already in the dev branch. But we will have something which will be conceptually compatible ;)
