### ISSUE TITLE
System.ObjectDisposedException: Safe handle has been closed

### ISSUE THREAD

**Issue by sheretovev** [IdentityServer/IdentityServer4.Samples#50]
Switch to "net461" framework, and RSA problems appear.

1 - Exception happens related to .SetTemporarySigningCredential(); 
ArgumentOutOfRangeException: IDX10630: The 'Microsoft.IdentityModel.Tokens.RsaSecurityKey' for signing cannot be smaller than '2048' bits. KeySize: '1024'.
Parameter name: key.KeySize

And Unfortunately, there are no ways to set appropriate keysize, 

2 - When using custom SetSigningCredential, f.e.
`var key = new RsaSecurityKey(new RSACryptoServiceProvider(2048))
                {
                    KeyId = CryptoRandom.CreateUniqueId(),
                    CryptoProviderFactory = CryptoProviderFactory.Default
                };
                var credential = new SigningCredentials(key, "RS256");
                return builder.SetSigningCredential(credential);`

Exception happens about:
System.ObjectDisposedException: Safe handle has been closed
   at System.Security.Cryptography.Utils._ExportKey(SafeKeyHandle hKey, Int32 blobType, Object cspObject)
   at System.Security.Cryptography.RSACryptoServiceProvider.ExportParameters(Boolean includePrivateParameters)
   at IdentityServer4.Endpoints.DiscoveryEndpoint.<ExecuteJwksAsync>d__10.MoveNext()

when using netcore1.0 framework, no problems in both cases.

Could you try that scenario, and propose possible soluions?

**Comment by sheretovev** [comment]
In Addition to second exception, How Rsa object looks when switching from core to net461 framework:
![image](https://cloud.githubusercontent.com/assets/4287554/18098051/d22e3e34-6ee0-11e6-9dbe-343eb6fd71c9.png)

and on second request of 
AspIdProfileService.GetProfileDataAsync(ProfileDataRequestContext context)
rsa object in RsaSecurityKey dissapears:
![image](https://cloud.githubusercontent.com/assets/4287554/18098124/17ec94fc-6ee1-11e6-9d65-6e68da51f6f1.png)

**Comment by leastprivilege** [comment]
Wrong repo - could you please open an issue on the main identityserver repo?

**Comment by leastprivilege** [comment]
fixed on the dev feed. give it a try.
