### ISSUE TITLE
Feature Request: Provide a configuration option to utilize Row Level Security features of SQL Server 2016 for multi-tenant scenarios

### ISSUE THREAD

**Issue by markchipman** [IdentityServer/IdentityServer4.Samples#52]
Using a new feature of SQL Server 2016, it now possible to provide excellent Row Level Security capabilities that allow leveraging SESSION_CONTEXT in conjunction with some related built in stored-procedures functions (i.e. two types of predicates--filter and block) to elegantly handle providing multi-tenant capabilities transparently to applications.  With SESSION_CONTEXT, you can inject user profile information (such as tenantId, userId, etc) in the ambient session which can be used by filter & block predicates to implement row level security, hence enabling 3-tiers architecture to leverage that feature.

It can be manipulated with the system stored procedure sp_set_session_context and can later be access with the SESSION_CONTEXT object:

EXEC sp_set_session_context 'user_department_id', 42;
SELECT SESSION_CONTEXT(N'user_department_id');

Adding this feature would be fairly benign, but would need to be configured by adding a call within IdentityServer4 internal wiring (for SQL served client/claims support) to create a SessionContextInterceptor within the SessionContextConfiguration (inherited from DbConfiguration) class.

For a better explanation of all this, please checkout the following link: [Tutorial: Web app with a multi-tenant database using Entity Framework and Row-Level Security](https://azure.microsoft.com/en-us/documentation/articles/web-sites-dotnet-entity-framework-row-level-security/).

I really hope you consider adding this since Identity Server wouldn't required extension alterations in order to accommodate multi-tenancy using RLS features of SQL Server 2016.

**Comment by brockallen** [comment]
What's an example of what you're ultimately trying to achieve with this?

**Comment by markchipman** [comment]
Setting the message.tenantid from the acr into the Session_context to pass into SQL Server 2016. Also it might be very handy to also include Always Encrypted functionality of 2016 to encrypt claim values :)

- Mark

**Comment by brockallen** [comment]
So then the net effect would be requests to the DB from certain tenants would be isolated in some way?

**Comment by markchipman** [comment]
That is correct 

- Mark

**Comment by brockallen** [comment]
I'm not a DB/SQLServer expert, but how does that provide additional security if the one connection string (the one being used from IdentityServer) has the power to switch to any tenant it wants? 

Or is this less of a security feature, and more of an implicit filtering mechanism? I guess it must be more of the latter given that the context of your above issue is multi-tenancy.

I'm just trying to get my head wrapped around what this is really doing.

**Comment by markchipman** [comment]
I think that the leveraging of some new 2016 features could help on both the filtering of content (ie multitenantcy) and on data at rest (security via Always Encrypted).  My primary interest though here is on multitenantcy and the desired to have built-in hooks to wire-up Session-Context data that can be accessed and automatically filtered via SQL Server 2016.  In essence this would required a hooking mechanism into the instantiation of the dbContext to make a call into a pluggable SessionContextInterceptor for the identity related tables and utilize a tenantId field on each of those tables.  Please check out this [link](http://craigpickles.com/row-level-security-in-azure-sql-with-entity-framework/) for some examples.

-Mark

**Comment by brockallen** [comment]
Given that this is a SQL Server specific feature, and all we're willing to support is EF, I'm inclined to close this issue. If you want to take the EF code and extend it so support this or build your own implementation, then we're happy to link to your repo. Thanks.
