### ISSUE TITLE
InvalidOperationException: Unable to resolve service for type 'IdentityServer4.Stores.IPersistedGrantStore' while attempting to activate 'IdentityServer4.Services.Default.DefaultPersistedGrantService'.

### ISSUE THREAD

**Issue by takazm** [IdentityServer/IdentityServer4.Samples#53]
I am getting the following error when running Id Server 4 with AspNetIdentity:
InvalidOperationException: Unable to resolve service for type 'IdentityServer4.Stores.IPersistedGrantStore' while attempting to activate 'IdentityServer4.Services.Default.DefaultPersistedGrantService'.
Any ideas

**Comment by leastprivilege** [comment]
Add `AddInMemoryStores()`
