### ISSUE TITLE
Missing include in publishOptions (project.json) - RC1

### ISSUE THREAD

**Issue by Eneuman** [IdentityServer/IdentityServer4.Samples#54]
Many of the sample projects are missing the "Views" tag in the "include" tag in the "publishOptions" section in project.json file.

This results in views not getting published when using Visual Studio publish command.

Publish options should look like this:
  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "web.config",
    ]
  }

**Comment by peterblazejewicz** [comment]
Actually this was changed for more generic approach in VS templates: 
https://github.com/aspnet/Templates/pull/659/files

**Comment by brockallen** [comment]
done
