### ISSUE TITLE
Sample for Active Directory

### ISSUE THREAD

**Issue by therealalbundy** [IdentityServer/IdentityServer4.Samples#56]
Any sample showing how to leverage Active Directory with IDSRV4?
Thanks in advance.

**Comment by leastprivilege** [comment]
not yet.

**Comment by therealalbundy** [comment]
Ok, so consider this a formal request for a such sample.
Also any indication by when you can make it available would be very appreciated.

**Comment by leastprivilege** [comment]
OK. noted.

Feel free to do your own investigations as well.

**Comment by evertefeuille** [comment]
I'm performing some tests with Azure Ad with Identity Server 4 and a MVC Client. I use OpenIdConnect to configure Ids with Azure. The only problem, I have frequently this error in Azure Login page : "Passed query string length exceeds supported limit." I noticed that the nonce parameter it's 2 times longer than directly by a direct login with Identity Server? Is it a issue or a normal behavior?

**Comment by brockallen** [comment]
@evertefeuille https://github.com/aspnet/Security/issues/978

**Comment by evertefeuille** [comment]
@brockallen  Thank you!

**Comment by mclark1129** [comment]
@brockallen @evertefeuille I've uploaded a sample project that shows how to configure Identity Server with Azure AD.  It also includes the custom StateDataFormat that I used to resolve aspnet/Security#978.

https://github.com/mclark1129/IdentityServer4.Samples/tree/master/AzureAd_CustomStateDataFormat

**Comment by therealalbundy** [comment]
@mclark1129 Thanks!!

**Comment by mrtaunus** [comment]
@mclark1129 Great effort! 

I seem to be having a little bit of problems getting your sample to work. I did get the clientId and the tenantId set to match those of our Azure AD, and got all the way to the requesting of the use of AD resources. 

Once I give the concent for the app to use data from the AD, the sign-in gives an error though:
AADSTS50012: Authentication failed. 

Do I need to set something else to get the sample to run? Sorry if this is a dumb question. I'm just starting to learn both IdentityServer as well as Azure AD.

Thanks in advance!

**Comment by brockallen** [comment]
@mclark1129 thanks for the sample!

@mrtaunus open an issue with @mclark1129's repo please.
