### ISSUE TITLE
Authorization Code Flow Client Sample

### ISSUE THREAD

**Issue by ericgreenmix** [IdentityServer/IdentityServer4.Samples#6]
Could you do a sample with the authorization code flow for a client?

**Comment by brockallen** [comment]
The ASP.NET 5 OIDC MW does all the code flow work for you, actually.

**Comment by ericgreenmix** [comment]
That would be fantastic. I have been trying to get it working with the ASP.NET OIDC MW but keep hitting a HTTP error on RedeemAuthorizationCodeAsync when the MW is processing the request. I assumed it was just a configuration error on my part and a sample could help me pinpoint what I am doing incorrectly.

Thanks!

**Comment by brockallen** [comment]
I'd argue that you should ping Microsoft for this (since it's their code). Also, though, not sure when we'll get to it.

**Comment by brockallen** [comment]
We have a hybrid sample, which is what's recommended (as opposed to just code flow). https://github.com/IdentityServer/IdentityServer4.Samples/tree/dev/Clients/src/MvcHybrid
