### ISSUE TITLE
Additional Secrets when using Reference Tokens?

### ISSUE THREAD

**Issue by xamlsharp** [IdentityServer/IdentityServer4.Samples#61]
var opt = new IdentityServerAuthenticationOptions();
opt.Authority = "http://localhost:5000";
opt.RequireHttpsMetadata = false;
opt.ScopeName = "api1";
opt.ScopeSecret = "secret";
**opt.AdditionalScopes = new[] { "api2" };**

app.UseIdentityServerAuthentication(opt);

When using reference tokens it is required that each scope have a secret and that this secret matches the “ScopeSecret” value supplied to “IdentityServerAuthenticationOptions”.

My question is how does one enable reference token semantics inside “IdentityServerAuthenticationOptions” for more than one scope? Adding additional scopes seems easy enough, yet in the above example the "api2" scope returns a 401 - ostensibly because there is no associated "ScopeSecret" with it. Is it possible to add additional “secrets” along with each additional “scope”?

**Comment by leastprivilege** [comment]
no - only the primary scope will be used for introspection.

**Comment by xamlsharp** [comment]
Thanks Dominick.

Consider this scenario: I have a two scopes that have ScopeSecrets, one called "read" and the other called "write". Now suppose that I want to protect access to an api  using reference tokens. If the "read" scope is my primary scope, how would I grant "write" access if the configuration middleware only permits a single secret?

**Comment by leastprivilege** [comment]
Yes - I know this is a limitation right now. Not sure yet how to solve this.

Other people worked around the fact that they always requests a certain scope from a service in addition to a "read" or "write".

**Comment by xamlsharp** [comment]
Thanks again.

Well, I guess it's good to know that having granular scopes with reference tokens is a real issue at the moment and it's not just my ignorance speaking. I'm thinking that another way might be to pass the claims retrieved from the introspection endpoint into each api service call. However, this seems far from ideal.

**Comment by brockallen** [comment]
Maybe we need an "application` concept? *ducks and runs*

**Comment by xamlsharp** [comment]
Well, now you’re going to get us all thinking... As the famed Cambridge researcher David Wheeler once remarked, “We can solve any problem by introducing an extra level of indirection.”

If what you're suggesting is at all feasible, then users could use clients, clients could use applications, and applications (or clients) could use scopes. I wonder if an application might “host” a series of scopes for the purpose of client access? If so, then an api would make a perfect candidate for just such an archetype. Moreover, I would think that allowing an application-based model would better enable a clearer conceptual model to be made concerning the placement of customised access-driven business logic.

Very interesting thoughts, Dominick. I appreciation your hard work.

**Comment by brockallen** [comment]
Yea, we've discussed this many times before, thus the "ducks and runs". This would be a significant programming model change.

**Comment by xamlsharp** [comment]
A big change, yes, but a fantastic idea nonetheless; and one that would definitely set IdentityServer even further apart from anything else out there in the sts space...

So, you're using a Microsoft style RC now?Isn't that the alpha you have when you're not having an alpha? ;) 

If that's the case, why not go the whole hog and rename the product itself... (drum roll, please)... Identity Server Core 1.0! :)

**Comment by brockallen** [comment]
This has now been addressed in the recent config reorg: https://github.com/IdentityServer/IdentityServer4/pull/509
