### ISSUE TITLE
SqlException when using entity framework with user consent

### ISSUE THREAD

**Issue by xamlsharp** [IdentityServer/IdentityServer4.Samples#62]
There appears to be an issue when using the quick start samples with EF. The below error message is displayed when using the following workflow with the MVC client:

1.	Log into MVC client
2.	Check remember consent
3.	Log out of MVC client
4.	Log out of Identity Server
5.	Allow redirect to MVC client
6.	Repeat steps 1 – 2 (not sure why it still asks to remember consent)

![image](https://cloud.githubusercontent.com/assets/22227916/18606941/429d78a0-7d01-11e6-935b-0925cd58b58c.png)

**Comment by brockallen** [comment]
Dup of https://github.com/IdentityServer/IdentityServer4/issues/280?

**Comment by xamlsharp** [comment]
Yes, it looks to be the same issue - although I have not tested this against the JavaScript client. I doubt there's much point in keeping this one open.
