### ISSUE TITLE
Shibboleth sample

### ISSUE THREAD

**Issue by miloush** [IdentityServer/IdentityServer4.Samples#63]
Hello, is there any sample or guide how to use IdentityServer to enable Shibboleth authentication?

**Comment by brockallen** [comment]
You should first find how to use Shibboleth from ASP.NET Core. Once you have that, then it'd be easy to use from IdentityServer.

**Comment by miloush** [comment]
I expected that the way to use Shibboleth from ASP.NET Core would be IdentityServer. I have probably misunderstood what IdentityServer provides and what it does not.

**Comment by leastprivilege** [comment]
probably. Here are the docs:

https://identityserver4.readthedocs.io/en/dev/
