### ISSUE TITLE
UI for configuration data and manage users

### ISSUE THREAD

**Issue by vdecristofaro** [IdentityServer/IdentityServer4.Samples#64]
Hi,
I have created a sample which is actually the merge of 
- 6_AspNetIdentity
- 8_EntityFrameworkStorage

I would like to create UI which are available to a logged admin to handle users and client/scope informations.

Could you please drive me on how to authorize a local user to log in to the standalone identity server application? Is this the right way to implement this feature or do I need to develop an external application that handle those configurations?

**Comment by Simply-Awesome** [comment]
1 - Register the initial user with required role and/or claims (possibly manually)
2 - After app.UseIdentityServer() (that should be after app.UseIdentity()) in your Startup class, add:
app.UseOpenIdConnectAuthentication(new OpenIdConnectOptions
            {
                // some config to make your Idsrv "a client to itself the server"
            });
3 - Login into secure areas

**Comment by brockallen** [comment]
https://github.com/IdentityManager/IdentityManager/issues/225#issuecomment-246199730

**Comment by vdecristofaro** [comment]
@brockallen thanks for the suggestion. I am going to explore that contribution and study a bit the code. I am already studying the Identity manager as well.

@Simply-Awesome thanks a lot. This makes sense to me. Do you have any code Sample or link that I can use as a starting point?
