### ISSUE TITLE
Help understaning logout/login and thier configuartion options please?

### ISSUE THREAD

**Issue by Simply-Awesome** [IdentityServer/IdentityServer4.Samples#65]
Issue in "IdentityServer4.Samples / Quickstarts / 6_AspNetIdentity":
-------------
When you register a new user (in menu).
Then logout (in menu).
The "cookie" does not get deleted (as seen in dev tools).
The user can still: 
- click on username (in menu)
- this would "activate" ManageController that the user can in turn perform tasks on its methods

Should this method in AccountController:

   [HttpPost]
   [ValidateAntiForgeryToken]
   public async Task<IActionResult> Logout(LogoutViewModel model)
{
 //...
}

have this statement:
    await _signInManager.SignOutAsync(); // this will delete the cookie (deleting the cookie is a requirement right?)

Or should the below statement in the method delete the cookie?
    await HttpContext.Authentication.SignOutAsync();

Or should one implement separate logouts (and maybe logins) depending on whether the UserManager<TUser> or IIdentityServerInteractionService logged in the user?

**Comment by brockallen** [comment]
Which cookie are you still seeing?

Admittedly, yes, this `await _signInManager.SignOutAsync();` is better than using `await HttpContext.Authentication.SignOutAsync();` because it will also delete the 2fa and external cookies, but both remove the primary authentication cookie.

**Comment by brockallen** [comment]
I'll update the same to use the `SignInManager`, but I just tested and the current version works correctly for me.

**Comment by Simply-Awesome** [comment]
It was an .AspNetCore.Identity.Application cookie

My Current Working Solution:
----------------------------

1. On AccountController leave the LogOff method unchanged from the default one MVC creates by default:

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> LogOff()
        {
            await _signInManager.SignOutAsync();
            _logger.LogInformation(4, "User logged out.");
            return RedirectToAction(nameof(HomeController.Index), "Home");
        }

2. On AccountController there is no logOff GET method (it isn't really needed for our use case)

3. Use the controllers (and views and models) in "IdentityServer4 / src / Host / Controllers" sample on GitHub (then customising it to not use the InMemory solution)

- AcountController (renamed to InternalAccountController); the methods have the following routes:
 - "/ui/login"
 - "/ui/logout"
 - "/ui/external/{provider}"
 - "/ui/external-callback"

- ConsentController; the methods have the following routes:
 - "/ui/consent"

- HomeController; the error method to the folowing route:
 - "ui/error"


4. On Startup ensure the UserInteractionOptions of IIdentityServerBuilder points to the InternalAccountController:

        public void ConfigureServices(IServiceCollection services)
        {
            string migrationsAssembly = typeof(Startup).GetTypeInfo().Assembly.GetName().Name; 

            services.AddDbContext<UserContext>(options1 => options1.UseSqlServer(GetSubjectConnectionString(), options2 => options2.MigrationsAssembly(migrationsAssembly)));

            services.AddIdentity<User, IdentityRole>()
                .AddEntityFrameworkStores<UserContext>()
                .AddDefaultTokenProviders();

            services.AddTransient<IEmailSender, AuthMessageSender>();
            services.AddTransient<ISmsSender, AuthMessageSender>();

            services.AddMvc();

            services.AddScoped<IUserContext, UserContext>();
	    Services.AddScoped<IClientStore, ClientStore>();
            services.AddScoped<IScopeStore, ScopeStore>();
            
            IIdentityServerBuilder identityServerBuilder = services
                .AddIdentityServer(options =>
                {
                    options.UserInteractionOptions.LoginUrl = "/ui/login";
                    options.UserInteractionOptions.LogoutUrl = "/ui/logout";
                    options.UserInteractionOptions.ConsentUrl = "/ui/consent";
                    options.UserInteractionOptions.ErrorUrl = "/ui/error";
                })
                .SetSigningCredential(GetX509Certificate2())
                .AddAspNetIdentity<User>();
        }

        public void Configure(IApplicationBuilder app, ILoggerFactory loggerFactory)
        {
            //...

            app.UseIdentity();

            app.UseIdentityServer(); // will use the cookie set by ASP.NET identity
            
            // ...

            app.UseMvcWithDefaultRoute();

            // ...
        }

        private string GetSubjectConnectionString()
        {
            // ...
        }

        private X509Certificate2 GetX509Certificate2()
        {
            // ...
        }


The end result is that I can:

- use "await _signInManager.SignOutAsync();" on users logged in via "await _signInManager.PasswordSignInAsyn(/* ... */);" (including 2fa users, and external users) via the MVC default AccountController
- use "await HttpContext.Authentication.SignOutAsync();" on users logged in via "await HttpContext.Authentication.SignInAsync(subject, username);" (including clients) via the InternalAccountController

Unless I am missing something... I believe this separation ensures correct login/logoff behaviour.

**Comment by Simply-Awesome** [comment]
> but both remove the primary authentication cookie..

When I click "log off" in the menu (and in turn call Logout method in the AccountController) with `await _signInManager.SignOutAsync(); ` the  .AspNetCore.Identity.Application cookie gets deleted; if it was  `await HttpContext.Authentication.SignOutAsync(); ` the .AspNetCore.Identity.Application cookie is still present.

Also 'HttpContext.User = new ClaimsPrincipal(new ClaimsIdentity());' is called in both cases.

The proof is that I can access ManageController via the menu, and this issue is without 2fa and is a normal login via the menu.

**Comment by Simply-Awesome** [comment]
> The proof is that I can access ManageController via the menu, and this issue is without 2fa and is a normal login via the menu.

I'm not sure exactly, but after I upgraded visual studio and Asp.Net.Core packages that was released a couple weeks or so ago, the issue went away :)
