### ISSUE TITLE
Sample Dockerfiles produce images that contain multiple copies of the application

### ISSUE THREAD

**Issue by MichaelSimons** [IdentityServer/IdentityServer4.Samples#66]
The Dockerfiles located at https://github.com/IdentityServer/IdentityServer4.Samples/tree/dev/Docker do not seem correct.  These Dockerfiles are based on the [microsoft/dotnet:onbuild](https://github.com/dotnet/dotnet-docker/blob/master/1.0.0-preview2/debian/onbuild/Dockerfile) images.  The `microsoft/dotnet:onbuild` image contains [ONBUILD](https://docs.docker.com/engine/reference/builder/#/onbuild) commands which copy the entire Docker build context into the image within a `dotnetapp` folder.  It then performs a dotnet restore on this content.  The sample Dockerfiles contain commands which create a separate `app` folder and copy a subset of the sample.

The use of the `microsoft/dotnet:onbuild` results in not only larger images in this case but it causes build optimization issues as described in https://github.com/dotnet/dotnet-docker/issues/109.

At a glance it seems that the sample Dockerfiles should simply be based on the 'microsoft/dotnet:1.0.0-preview2-sdk' images.

**Comment by leastprivilege** [comment]
@tugberkugurlu would answer that.

**Comment by tugberkugurlu** [comment]
@MichaelSimons thanks a lot for logging it as an issue here and sending a PR after the issue I submitted (https://github.com/dotnet/dotnet-docker/issues/109). This is exactly what I was looking for.
