### ISSUE TITLE
.net Core Web Api with Implicit Flow?

### ISSUE THREAD

**Issue by behrooz66** [IdentityServer/IdentityServer4.Samples#67]
I would ideally like to build a web api application that uses individual user accounts login with the following capabilities:
- generating access tokens
- generating refresh tokens
- using social logins (google, facebook, ...)
- local database for storing user's info
- facilitating roll-based authorization

Is implicit flow the best option? if yes, how would one set it up to generate refresh tokens, etc? Any specific sample?

**Comment by leastprivilege** [comment]
To improve discoverability of frequently asked and/or more general questions, we decided to move those questions to StackOverflow:

https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

We actively monitor SO as well but hope to create a community there so questions can get answered faster when we are not available.
