### ISSUE TITLE
AAD:: Signature validation failed. Unable to match 'kid'

### ISSUE THREAD

**Issue by svg3171** [IdentityServer/IdentityServer4.Samples#69]
I am using to UseOpenIdConnectAuthentication to add azure active directory as external provider, using IdentityServer4. However I receive **SecurityTokenSignatureKeyNotFoundException: IDX10501: Signature validation failed. Unable to match 'kid'** issue.

I tried manually implementing IssuerSigningKeyResolver (got clue from https://github.com/IdentityServer/IdentityServer3/issues/3040). 

Could you please help.

**Comment by svg3171** [comment]
Never mind. I was able to resolve the issue.

**Comment by patriksvensson** [comment]
@svg3171 Mind to share what the problem was?

**Comment by muziekklas** [comment]
@svg3171 Mind sharing the solution? 
Thanks in advance!
