### ISSUE TITLE
Client Sample for Android/Java ?

### ISSUE THREAD

**Issue by leo9223** [IdentityServer/IdentityServer4.Samples#7]
Can we have a client sample for Android/Java !

**Comment by leastprivilege** [comment]
not from me. but feel free to add one.

**Comment by leo9223** [comment]
Okay Sir, Ill look into that.

**Comment by leo9223** [comment]
I am trying different oauth2 client. And trying to port resource owner flow. Please anyone suggest me some good oauth2 client libraries for droid near to IdentityModel !

**Comment by leastprivilege** [comment]
Anything that can do a form post and parse a json response will do it.

**Comment by leo9223** [comment]
Can you please refer me how a client request look? that goes to authorization server. So that I can translate into android/java. 

where I can find such stuff? sorry I am novice !

**Comment by leastprivilege** [comment]
https://tools.ietf.org/html/rfc6749

**Comment by leo9223** [comment]
Thank you Sir

**Comment by leo9223** [comment]
In this section https://tools.ietf.org/html/rfc6749#section-4.3.2

it is not stated that you have to provide "client_id" and "client_secret", but in your resource owner flow client example you are specifying "client_id" and "client_secret" using "TokenClient".

I am thinking that where and when to put "client_id" and "client_secret", am I missing something?

**Comment by leo9223** [comment]
Sir I am getting "ConnectionRefused" I think now I just need to configure the request correctly.

Here is the code ! 

`URL reqURL = new URL("http://localhost:22530/"); //the URL we will send the request to
            HttpURLConnection request = (HttpURLConnection) (reqURL.openConnection());
            //String post = "this will be the post data that you will send";
            request.setDoOutput(true);
            //request.addRequestProperty("Content-Length", Integer.toString(post.length())); //add the content length of the post data
            request.addRequestProperty("Content-Type", "application/x-www-form-urlencoded"); //add the content type of the request, most post data is of this type
            request.setRequestMethod("POST");

            String charset = "UTF-8";
            String s = "grant_type=" + URLEncoder.encode("password", charset);
            s += "&client_id=" + URLEncoder.encode("roclient", charset);
            s += "&client_secret=" + URLEncoder.encode("secret", charset);
            s += "&username=" + URLEncoder.encode("bob", charset);
            s += "&password=" + URLEncoder.encode("bob", charset);
            s += "&scope=" + URLEncoder.encode("api1", charset);


            request.setFixedLengthStreamingMode(s.getBytes().length);


            request.connect();

            String resp = request.getOutputStream().toString();`

**Comment by brockallen** [comment]
You want the token endpoint for the URL.

**Comment by leo9223** [comment]
@brockallen 

oh! thank you sir  : O  

now trying...

**Comment by leo9223** [comment]
@leastprivilege @brockallen 

Good news ! Sir I got the access token in Android using resource owner flow

Ill share soon : )

**Comment by leo9223** [comment]
@leastprivilege @brockallen 

*AccessToken in Android Done

*RefreshToken in Android Done

*Calling service is throwing 500 internal server error I went through some articles it's probably about certificate issue I think !

for calling service I am adding this to request header and my request is of type GET 

Authorization: Bearer aiosdnlakdnfaosdlgnff....

**Comment by leo9223** [comment]
Here is the code to call service

`            URL obj = new URL(url);
            
            HttpURLConnection con = (HttpURLConnection) obj.openConnection();

            con.setRequestMethod("GET");
            
            con.setRequestProperty("Authorization", "Bearer " + access_token);
            
            int responseCode = con.getResponseCode();

            if (responseCode < 400) {
                BufferedReader in = new BufferedReader(
                        new InputStreamReader(con.getInputStream()));
                String inputLine;
                StringBuffer response = new StringBuffer();

                while ((inputLine = in.readLine()) != null) {
                    response.append(inputLine);
                }
                in.close();

                result = response.toString();`


int responseCode = con.getResponseCode(); // Always gives 500 : (

**Comment by brockallen** [comment]
To know why you should enable logging and see what the logs say.

**Comment by leo9223** [comment]
@leastprivilege @brockallen 

Thank you so much Sir :) I have done with it Ill share :)

**Comment by brockallen** [comment]
We also have these samples: https://github.com/IdentityModel/IdentityModel.OidcClient.Samples. They're not Java, tho...
