### ISSUE TITLE
Tokenvalidator ValidateAsync returning JosePCL.Jwt.Verify(): Invalid signature.

### ISSUE THREAD

**Issue by pottabathini** [IdentityServer/IdentityServer4.Samples#71]
we are trying identitymodel OpenID and OAuth in the desktop application. Using identitymodel oidcclient object loginasync method we able to open the webview and login successfully. 

After login, data got returned to the application and application able to decode the form data into string. When it is trying to validate the returned data application giving error like "JosePCL.Jwt.Verify(): Invalid signature.". 

We debug further and able to identity the root cause. Because of my STS provider not have the end point for  "connect/identitytokenvalidation", Identitymodel returning generic error.

As per the article [https://identityserver.github.io/Documentation/docsv2/endpoints/identityTokenValidation.html](Identity Token Validation) that endpoint is mandatory to get the claims. 

But same claims already coming in the response body of id_token(JWT token) parameter, can we return those claims instead of calling another endpoint API? 

Is there any option to make validation optional/ add custom validation?

**Comment by leastprivilege** [comment]
wrong repo

**Comment by pottabathini** [comment]
It means I am working on wrong repo? 
If so can you please give the correct one please?

**Comment by leastprivilege** [comment]
What's the name of the nuget package you are using for the OIDC client functionality?

**Comment by pottabathini** [comment]
Identitymodel oidc client as of I remember. I am outside now, I can give full name after few hours.

**Comment by pottabathini** [comment]
Sorry for late reply,  we used **IdentityModel.OidcClient.1.4.0** client library. And we are trying to run the sample which is published under samples **IdentityModel.OidcClient.Samples-master\WinFormsWebView** 

We modified your example and tried out. Please let me know If I am referring a wrong DLL.

Thank you.

**Comment by leastprivilege** [comment]
Then I would probably rather open issues in the repo it belongs to...e.g.

https://github.com/IdentityModel/**IdentityModel.OidcClient.Samples**

https://github.com/IdentityModel/**IdentityModel.OidcClient**

makes sense?

**Comment by pottabathini** [comment]
yes, it is. So you want me to open issue in the samples now? or if it is possible to move this issue inside samples please do.
BTW can you please let us know how can we make identitymodel ignore that endpoint(**connect/identitytokenvalidation**) while validating the token

**Comment by leastprivilege** [comment]
What I am saying is, that you need to open issue in the repos where these issues belong to. This repo here is clearly completely unrelated.

**Comment by pottabathini** [comment]
Done, I opened issue there. Here is the link https://github.com/IdentityModel/IdentityModel.OidcClient.Samples/issues/6
