### ISSUE TITLE
QuickStart UI Hybrid And Api Example Login UI configuration.

### ISSUE THREAD

**Issue by Shinjifei** [IdentityServer/IdentityServer4.Samples#72]
I have 2 simple questions.  How is the path to /account/login configured.  How does identityserver and/or asp core know to redirect to that action when navigating to a controller action with [Authorize] . I cannot find a configuration for that anywhere in this example or identityservers source code.

Also does HybridAndClientCredentials work as a auth code flow with oauth2 ?

**Comment by brockallen** [comment]
> How is the path to /account/login configured.

https://github.com/IdentityServer/IdentityServer4/blob/dev/src/IdentityServer4/Configuration/DependencyInjection/Options/UserInteractionOptions.cs#L20

> How does identityserver and/or asp core know to redirect to that action when navigating to a controller action with [Authorize]

IdentityServer redirects there explicitly when it needs to. Nothing in your ASP.NET Core app knows about it unless you configure it as the LoginPath on the cookie middleware.

**Comment by Shinjifei** [comment]
Thanks.
