### ISSUE TITLE
Protecting multiple API

### ISSUE THREAD

**Issue by vdecristofaro** [IdentityServer/IdentityServer4.Samples#73]
I have 4 API in my project.
For each API I have created a custom scope. 

In the documentation, [here](https://identityserver4.readthedocs.io/en/dev/configuration/apis.html), you explain how to protect a single API with a scope. How to do the same for each controller?

**Comment by brockallen** [comment]
You'd need to check for the scope claim in each controller.

**Comment by vdecristofaro** [comment]
Hi @brockallen 
Do you mean something like this?

In Startup.cs
 
```
services.AddAuthorization(options => {
    options.AddPolicy("api1", policy1 => {
        policy1.RequireClaim("scope", "api1");
    });
    options.AddPolicy("api2", policy2 => {
        policy2.RequireClaim("scope", "api2");
    });
});
```

And then in the Controller:

```
[Authorize]
[Route("api/[controller]")]
public class Api1Controller : Controller
{
    [Authorize("api1")]
    [HttpGet]
    public IActionResult Get() {
    }
}
```

**Comment by brockallen** [comment]
Yep
