### ISSUE TITLE
Readme of Quickstart #6

### ISSUE THREAD

**Issue by wijnsema** [IdentityServer/IdentityServer4.Samples#75]
The Readme of Quickstart #6 incorrectly states: "Quickstart #5: OpenID Connect Hybrid Flow Authentication and API Access Tokens"

This should be "Quickstart #6: Indentity server with ASP.NET Identity backend", or something like that.

Thank you for the new Identityserver4 documention and quickstarts, this is a huge improvement over the former documentation.

**Comment by brockallen** [comment]
fixed. thanks.
