### ISSUE TITLE
Quickstart documentation: Adding the UI

### ISSUE THREAD

**Issue by wijnsema** [IdentityServer/IdentityServer4.Samples#76]
In my opinion the Quickstarts are extremely valuable for new users. Starting from scratch and plugging every in one step at a time really helps you understand what's going on.

Just a small omission I found so far: When adding the UI [https://identityserver4.readthedocs.io/en/dev/quickstarts/3_interactive_login.html](https://identityserver4.readthedocs.io/en/dev/quickstarts/3_interactive_login.html)
it is not mentioned that MVC should be added to the project. This is mentioned when you open the github project, but to keep the Quickstart complete it should be mentioned there as well IMHO.

**Comment by brockallen** [comment]
we accept PRs on the docs.
