### ISSUE TITLE
Best Grant Type (or user flow) for JavaScript App (or Website) to access protected API?

### ISSUE THREAD

**Issue by Simply-Awesome** [IdentityServer/IdentityServer4.Samples#78]
Scenario:
Front End App (or Website) created with Angular, Ember, React, Knockout or some other JavaScript framework.

Task:
Access Data from API (at some other location) protected by Identity Server 4 to display to its users. e.g. Stock/Currency data that is non-user specific because it can apply to anyone. The data is protected because there is a cost associated with getting the info even though it is not user specific. 

Issue:
The App/Website is public facing and as such there are no registered users as such to speak of. (Hence, an Implicit Grant Type will not be an option right?)

Questions:
1. Could you kindly describe the best (and recommended) Grant Type to use please? It would also be great if you could expand on any option (if any) one could possibly consider.

Among many places I have looked at http://docs.identityserver.io/en/dev/topics/grant_types.html, but I would like to be sure.

I am currently thinking that a backend service that is on a client_credentials grant is non-negotiable.... but I have a feeling there must be a better option. 
1. If so, does that mean the JavaScript App/Website makes a POST request to the Backend service for the access_token, to be used in Front End XHR calls? 
2. Or does the Backend service make ALL XHR calls and return the content for the Front End?

**Comment by leastprivilege** [comment]
You are basically returning anonymous data...so either way you cannot really secure that API.

Requiring a token makes it a little harder for get to the data, but is of course no real protection from an ambitious attacker.

**Comment by Simply-Awesome** [comment]
Thanks for your response. I really appreciate your help on this and this is why I need to be very explicit; there are a few Clients I have to secure... and I need to be sure that I am getting this right.

> You are basically returning anonymous data...so either way you cannot really secure that API.

I was hoping you would confirm that it can be secured against the Client (irrespective of the Anonymous Users). In turn, I was then wondering how?

> Requiring a token makes it a little harder for get to the data, but is of course no real protection from an ambitious attacker.

Example:

The App is a .NET Core (or .NET 4.5) Web App, where the Front End bits is built with Angular.

Options Considered:

1. Front End App (via Angular/JQuery) makes a POST request to one of its MVC (or Web API) Controllers, that picks up the credentials from the .NET configuration file, then uses the client_credentials flow to get an access_token (with .NET HttpClient). The response (of an access_token) from the Controller is returned to the Front End App that then makes an XHR request (using the access_token with Angular/jQuery) to the API for the data it needs for the user.

2. Front End App (via Angular/JQuery) makes a POST request to one of its MVC (or Web API) Controllers, that picks up the credentials from the .NET configuration file, then uses the client_credentials flow to get an access_token, then uses the access_token to make a request to the API (all with .NET HttpClient) for the required API data. The response (of API data) from the Controller is returned to the Front End App that shows this data (using Angular/jQuery) to the user.

Are you saying that Option 1 is not secure, or that both Option 1 and Option 2 are not secure?

**Comment by leastprivilege** [comment]
In any case - any front end app can make the request and ultimately read the data - or am I missing something?

Or do you authenticate the user first?

**Comment by Simply-Awesome** [comment]
If I was to take Google as an example: you type some text, then search results appear. The users are anonymous. The data is NOT private. The users are happy for the convenience of a service that collates, filters and returns well sorted results data. 

Surely access to these search result data (provided via an API) can be restricted to www.google.com and not allow at www.Bing.com?

> Or do you authenticate the user first?

No; the data itself is not private or personal. Also, the users are not known at this point.

> In any case - any front end app can make the request and ultimately read the data - or am I missing something?

Honestly I'm probably the one missing something... but this is all I am trying to do: restrict Company A, from accessing an API service provided by Company B, even though Company B allows Company C to access it. 

Company B is considering ID4 to secure its API.

Company C is considering a user-captivating JS front end app on the .NET platform. 

Are you saying that Company B ultimately cannot stop Company A with any of Options 1 or 2, or some other, if Company C uses JavaScript?

**Comment by leastprivilege** [comment]
if JavaScript is all you care about - you could use an anti-forgery style approach to make sure the client is **your** JavaScript only.

But ultimately you are providing an anonymous service (or have to "hide" credentials in your JS) - this can be scraped from non-browser clients.

**Comment by Simply-Awesome** [comment]
> if JavaScript is all you care about - you could use an anti-forgery style approach to make sure the client is your JavaScript only.

Understood and Noted. (Ensure that I apply “ValidateAntiforgeryToken” and etcetera.)

> But ultimately you are providing an anonymous service (or have to "hide" credentials in your JS) - …

I see where you are going; if the credentials are in a .NET web config file that C# (via HttpClient) uses, and the JavaScript cannot access at all (because it is NOT hidden in JS), this will do.

Option 1 gets the access_token then gives it to JS to use, Option 2 gets the access_token, then uses it, then gives JS the data; together with the combination of the Anti-Forgery style approach, either is fine.

Cool.

> … this can be scraped from non-browser clients.

I will definitely keep this in mind. However, as the client in this scenario is trusted (And anti-forgery enforcing JS), this will not apply.

Your help is much appreciated. Many thanks.
