### ISSUE TITLE
GetLogoutContextAsync parameters

### ISSUE THREAD

**Issue by bill-newland-enta** [IdentityServer/IdentityServer4.Samples#79]
I feel like I'm being really dim but I cannot work-out what the logoutId parameter on the 
GetLogoutContextAsync(logoutId) method in IIdentityServerInteractionService  refers to. I've been looking at the Logout action in the IdentityServerWithAspNetIdentity sample but I can't see where the parameter is passed and without it I can't find the post login url etc.

Thanks

Bill

**Comment by brockallen** [comment]
it's when a client makes a single signout request

**Comment by jack4it** [comment]
But how? I mean what that logout id is really referring to? and how we can find it out and add it to the query string?
