### ISSUE TITLE
What's the way to define external identity providers (google, facebook, ...) in V4 ?

### ISSUE THREAD

**Issue by paulvanbladel** [IdentityServer/IdentityServer4.Samples#8]
What's the way to define external identity providers (google, facebook, ...) in V4 ?

**Comment by leastprivilege** [comment]
Just like you normally would do in asp.net core - via middleware and call it from your login page.

**Comment by paulvanbladel** [comment]
Thanks for the prompt feedback Dominick.
Maybe I'm completely missing the point, but I'm not seeing the IdentityProviders property in the AuthenticationsOptions:

Below is extract from V3 docs:
```
 AuthenticationOptions = new AuthenticationOptions 
    {
        IdentityProviders = ConfigureIdentityProviders
    }
```

**Comment by paulvanbladel** [comment]
I would expect that after Middleware setup the login screen would have additional Facebook button.

**Comment by leastprivilege** [comment]
it will work exactly like in a normal asp.net application (asp.net identity and the external providers are unrelated - but could be used together).

**Comment by federicocalzi** [comment]
Dominik, 

I don't know if this question might be redundant, but I have been trying to figure this out for a while without success.

My understanding is that in V3 I can configure the IdentityProviders through the Owin IAppBuilder 
        public static void ConfigureAdditionalIdentityProviders(IAppBuilder app, string signInAsType)
        {
            var microsoft = new MicrosoftAccountAuthenticationOptions()
            {
                AuthenticationType = "Microsoft",
                SignInAsAuthenticationType = signInAsType,
                ClientId = Commons.Configuration.Get("azureClientId"),
                ClientSecret = Commons.Configuration.Get("azureKey")
            };
            app.UseMicrosoftAccountAuthentication(microsoft);
        }

In V4 everything is desinged around IApplicationBuilder interface, which doesn't have the methods above.

Does this means that in V4 external providers authentication is not supported yet? 

Thanks

**Comment by federicocalzi** [comment]
No worries Dominik, I think I made some significant progresses.

The problem was that I was trying to add the OWIN reference instead of adopting the 

    "Microsoft.AspNet.Authentication.MicrosoftAccount": "1.0.0-rc1-final"

I found a solution at

http://go.microsoft.com/fwlink/?LinkID=532715

Thank you and great work.

**Comment by Sn3b** [comment]
@paulvanbladel and @federicocalzi have you guys managed? I'm trying to do the same thing, would you be able to describe the steps?

**Comment by alzdrak** [comment]
@leastprivilege in ASP.NET CORE Identity Server 4, how would I go about using external providers eg `app.UseFacebookAuthentication` from `Microsoft.AspNet.Authentication.Facebook` and include it in the startup:

```
var builder = services.AddIdentityServer(options =>
{
    options.AuthenticationOptions = new AuthenticationOptions
    {
        IdentityProviders = ConfigureIdentityProviders
    };
});
```

`IdentityProviders` doesn't exist in `AuthenticationOptions` anymore.

Also, when the token returns from Facebook, should it forward to IdentityServer or my SPA? I need to do some user account manipulation when registering a new account on an external provider.

For instance, when the user visits my SPA and clicks on an external provider and registers an account, he is redirected back to my specified return url with a token and some other info. I then need to register the user in my DB as well (link the oauth id to a specific account), and then ask them for some basic information (Name, company etc) with a page.

If I understand correctly by implementing the way in federicocalzi link above (the normal way thats in the asp.net core examples), I will skip these steps and have to do it in my SPA? Would it not be better to have identity server, handle external providers as well?

**Comment by Sn3b** [comment]
@aizdrak I've done the following which seems to work:

```csharp
// Starup.cs

            app.UseCookieAuthentication( options =>
            {
                options.AuthenticationScheme = "Cookies";
                options.LoginPath = new PathString( "/account/login" );
                options.AccessDeniedPath = new PathString( "/account/forbidden" );
                options.AutomaticAuthenticate = true;
                options.AutomaticChallenge = true;

                options.CookieName = ".AspNet.Cookies";
            } );

            app.UseFacebookAuthentication( options =>
            {
                options.AuthenticationScheme = "Facebook";
                options.SignInScheme = "Cookies";

                options.AppId = "xxx";
                options.AppSecret = "xxx";
            } );
```
```html
<!-- /UI/Login/Views/Index.cshtml -->
            @{
                var loginProviders = Context.Authentication.GetAuthenticationSchemes().ToList();
                <form asp-action="ExternalLogin" asp-route-returnurl="@ViewData["ReturnUrl"]" method="post" class="form-horizontal" role="form">
                    <div>
                        <p>
                            @foreach ( var provider in loginProviders )
                            {
                                <button type="submit" class="btn btn-default" name="provider" value="@provider.AuthenticationScheme" title="Log in using your @provider.DisplayName account">@provider.AuthenticationScheme</button>
                            }
                        </p>
                    </div>
                </form>
                }
            }
```
```csharp
        [ HttpPost ]
        [ AllowAnonymous ]
        [ ValidateAntiForgeryToken ]
        public IActionResult ExternalLogin( string provider, string returnUrl = null )
        {
            var props = new AuthenticationProperties
            {
                RedirectUri = "/"
            }; 

            return new ChallengeResult( provider, props );
        }

```
I get rdirected back to IdSrv, and I seem to be logged in and validated, but I don't know what to do next to be automatically redirected to my SPA, if you know, please let me know :)

**Comment by alzdrak** [comment]
Thanks for the example @Sn3b! What I'm doing now is creating a `ExternalLoginCallback` function in IdentityServer that basically receives the provider info and like standard MVC examples.

If the external provider userId is already matched to an internal account (your DB), then forward to the client application. 
However if the userId doesnt exists in our DB, then show a register page. Once registered, do the same and just redirect back to the client application.

I will post code as soon as I've got this working.

The only confusion I have is, is there a standardized way to move tokens between providers? Or Is it wrong? Because essentially its an external provider thats forwarding to the idsrv provider, which is like moving tokens between google and twitter and then to your application. Technically it makes sense to forward it directly to your SPA, but I'm not sure if there are security holes. Perhaps @leastprivilege or @brockallen could share their wisdom.

**Comment by pikoscielniak** [comment]
I think the solution in this repository can be helpful. https://github.com/pikoscielniak/idsrv-demo I'll publish a post about this solution in a week or two.

**Comment by ChristianRiedl** [comment]
Gentlemen, I am now at the same point. I get redirected and logged in to IdSrv, but I don't know how to redirect to my SPA. What are your latest findings. Shall I try to move **@pikoscielniak** demo to current idsrv4 version ?

**Comment by mandarincreative** [comment]
Has anyone successfully gotten External Login with either Google or Facebook working in the context of an Angular 2 SPA w/ IdentityServer4?

**Comment by brockallen** [comment]
It works with our SPA sample, which would be equivalent to an angular app. 

If you're having issues then you should ask on StackOverflow for that. This has the advantage that questions and answers can be easily found by search engines, and that there are more people answering questions than just us.

For IdentityServer3
https://stackoverflow.com/questions/tagged/?tagnames=identityserver3&sort=newest

For IdentityServer4
https://stackoverflow.com/questions/tagged/?tagnames=identityserver4&sort=newest

For commercial support
https://identityserver.io/

**Comment by waqaskhan540** [comment]
@Sn3b have a look at  https://github.com/waqaskhan540/IdentityServerExternalAuth
