### ISSUE TITLE
Move docker samples to rc3

### ISSUE THREAD

**Issue by tugberkugurlu** [IdentityServer/IdentityServer4.Samples#81]
Based on https://twitter.com/leastprivilege/status/795231128617709572, I will try to do it today.

**Comment by brockallen** [comment]
btw, rc4 will be out this week

**Comment by tugberkugurlu** [comment]
@brockallen which reminded me that I was supposed to do this 😢 should I wait for rc4 and skip rc3 then?

**Comment by brockallen** [comment]
yes

**Comment by brockallen** [comment]
rc4-update1 was released today

**Comment by brockallen** [comment]
rc5 was released today :)

**Comment by Boggin** [comment]
I think this issue is closed by #118.
