### ISSUE TITLE
Windows Externallogin Provider

### ISSUE THREAD

**Issue by Meerownymous** [IdentityServer/IdentityServer4.Samples#82]
Hi!

I want to use Windows Authentication and therefore I tried the samples:

- IdentityServer4 is started via IIS integration in VS
- Started IdentityServer4.Samples MVC.Implicit 

![image](https://cloud.githubusercontent.com/assets/11885968/20303285/0036883c-ab2b-11e6-813d-5f83c7e7c5b1.png)

When I click on the Button i get a 403 response. All other external providers seem to work fine. Here are my request and response details:
![image](https://cloud.githubusercontent.com/assets/11885968/20303366/539c48cc-ab2b-11e6-8b93-f4ed6f83341b.png)

I checked that windows Authentication is activated:
![image](https://cloud.githubusercontent.com/assets/11885968/20303411/8c01d272-ab2b-11e6-8831-e452acad76c5.png)

Also, when deactivating anonymous access, I can see my windows username in the IdentityServer top NavBar.

Any suggestions? What am I doing wrong?

**Comment by leastprivilege** [comment]
Making this scenario work is still on our todo list. We are aware of the issues you are seeing.

**Comment by Meerownymous** [comment]
Thanks for the fast reply.

**Comment by brockallen** [comment]
tracking here: https://github.com/IdentityServer/IdentityServer4/issues/178
