### ISSUE TITLE
Amazing WORK. possible to get an Ionic 2 sample?

### ISSUE THREAD

**Issue by nigel-dewar** [IdentityServer/IdentityServer4.Samples#83]
Hi There, IdSVR4 is Amazing!!! Thank you so much for building this, so much hard work must have gone into this!

This is a question.  Angular 2 is come to fruition (finally). And with it lots of goodies like Ionic 2 and Electron.

Any chance anyone can knock out a sample using either Ionic 2 or Electron for IdSVR4?

I realize you guys are really , REALLY busy. But if possible it would be grand and certainly appreciated by not just myself but quite a few I imagine.

I will keep investigating myself, but asking in advance in case somebody has the time.

Cheers, keep up the amazing work. Such an epic product! :-)

**Comment by brockallen** [comment]
The best we have is the OIDC JS sample that uses the oidc-client JS library (which is written in ES6), so it should not be that hard to map that into angular 2.

**Comment by nigel-dewar** [comment]
Cheers Brock, ill give that a crack.


Sent from Samsung Mobile


-------- Original message --------
From: Brock Allen
Date:18/11/2016 23:23 (GMT+10:00)
To: "IdentityServer/IdentityServer4.Samples"
Cc: nigel-dewar , Author
Subject: Re: [IdentityServer/IdentityServer4.Samples] Amazing WORK. possible to get an Ionic 2 sample? (#83)


Closed #83<https://github.com/IdentityServer/IdentityServer4.Samples/issues/83>.
