### ISSUE TITLE
Is there any example to secure WCF

### ISSUE THREAD

**Issue by mabouchalkha** [IdentityServer/IdentityServer4.Samples#84]
is there any example how to secure a webservice (wcf) with IDS 4

my need is i call a webservice from (in) my api.
the flow is JavaScript call web api and in the api consume the webservice

thank you

**Comment by leastprivilege** [comment]
Here's a sample for WCF

https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Clients/WcfClient
https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Clients/WcfService

**Comment by mabouchalkha** [comment]
Is the same think for identityserver 4? Thanks a lot

**Comment by leastprivilege** [comment]
similar. yes.
