### ISSUE TITLE
'System.Net.Http.HttpRequestException' when running quickstart2

### ISSUE THREAD

**Issue by ricksecretin** [IdentityServer/IdentityServer4.Samples#85]
I opened the Quickstart2_ResourceOwnerPasswords project.

When I run both the projects Api and Client at the same time I get this exception: 'System.Net.Http.HttpRequestException' occurred in System.Private.CoreLib.ni.dll

I only changed the version in global.json to "1.0.0-preview2-003131".

Is there any way to fix this?

**Comment by leastprivilege** [comment]
Is that the new tooling that comes with 1.1 ?

Lots of problems with that...we stay on 1.0 for the time being.

**Comment by ricksecretin** [comment]
I just installed the latest tools of .net core so I guess yes.
I don't have "1.0.0-preview2-003121" installed. Where can I download this one? I can't really find a solution on google.

**Comment by leastprivilege** [comment]
When you go to 

https://www.microsoft.com/net/download/core

Choose the LTS download (== long time support).

I am not sure which SDK version this installs - but you can set the SDK version to whatever comes with that.

**Comment by ricksecretin** [comment]
Thanks but I installed the latest LTS version just now and this is 1.0.0-preview2-003133. It still throws the same error.

**Comment by leastprivilege** [comment]
sorry - then I don't know.

**Comment by brockallen** [comment]
The 1.0.0 SDK is here: https://go.microsoft.com/fwlink/?LinkID=809122.

**Comment by ricksecretin** [comment]
Thank you but even with this sdk my problem stays the same. 
I just redownloaded the samples and try to run them without changing anything. 
But it keeps throwing this error.

**Comment by leastprivilege** [comment]
So then you need to open an issue with Microsoft - maybe this is a known problem.

**Comment by ricksecretin** [comment]
Thank you but even with this sdk my problem stays the same. 
I just redownloaded the samples and try to run them without changing anything. 
But it keeps throwing this error.

**Comment by ricksecretin** [comment]
Ok I will do that, Thanks anyway!
