### ISSUE TITLE
asp.net web form client

### ISSUE THREAD

**Issue by asif37** [IdentityServer/IdentityServer4.Samples#86]
Hi:

I see that asp.net web form client is missing in samples. I have identity server setup with asp.net identity and clients and scopes being saved in database with entity framework. i have api in asp.net core and an mvc application in core which gets token from identity server. it works with these configurations:

```
       var oidcOptions = new OpenIdConnectOptions()
            {
                AuthenticationScheme = "oidc",
                SignInScheme = "Cookies",

                Authority = "http://localhost:5000",
                RequireHttpsMetadata = false,

                ClientId = "mvcClient",
                ClientSecret = "secret",
               
                //GetClaimsFromUserInfoEndpoint = true,
                ResponseType = "code id_token", // hybrid flow
                //RemoteSignOutPath = "/Account/LogOff"
                //Scope = { "NamfusAPI", "offline_access" },
                 SaveTokens = true
            };


            oidcOptions.Scope.Clear();
            oidcOptions.Scope.Add("openid");
            oidcOptions.Scope.Add("profile");
            oidcOptions.Scope.Add("NamfusAPI");
            oidcOptions.Scope.Add("offline_access");


            app.UseOpenIdConnectAuthentication(oidcOptions);
```
but when i try asp.net web form (developed in .net 4.6.1) with this configuration:

 JwtSecurityTokenHandler.InboundClaimTypeMap = new Dictionary<string, string>();

            app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationType = "Cookies",
                //LoginPath = new PathString(ConstansValues.BaseAddress + @"permissions/")
            });

            app.UseOpenIdConnectAuthentication(new OpenIdConnectAuthenticationOptions
            {
                ClientId = "mvcClient",
                ClientSecret = "secret",
                Authority = "http://localhost:5000",
                RedirectUri = "http://localhost:5969",
                PostLogoutRedirectUri = "http://localhost:5969",
                ResponseType = "code id_token",              
                Scope = "openid profile NamfusAPI offline_access",

                SignInAsAuthenticationType = "Cookies",
                Notifications = new OpenIdConnectAuthenticationNotifications
                {
                    SecurityTokenValidated = async n =>
                    {

                        var token = n.ProtocolMessage.AccessToken;
                        // persist access token in cookie
                        if (!string.IsNullOrEmpty(token))
                        {
                            n.AuthenticationTicket.Identity.AddClaim(
                                new Claim("access_token", token));
                        }
                        var nid = new ClaimsIdentity();
                        nid.AddClaim(new Claim(@"id_token", n.ProtocolMessage.IdToken));
                    },
                    RedirectToIdentityProvider = n =>
                    {
                        // if signing out, add the id_token_hint
                        if (n.ProtocolMessage.RequestType == OpenIdConnectRequestType.LogoutRequest)
                        {
                            var idTokenHint = n.OwinContext.Authentication.User.FindFirst("id_token");
                            if (idTokenHint != null)
                                n.ProtocolMessage.IdTokenHint = idTokenHint.Value;
                        }
                        return Task.FromResult(0);
                    }
                },
            });
        }

and this page load:

   protected void Page_Load(object sender, EventArgs e)
        {
            if (!Request.IsAuthenticated)
            {
                HttpContext.Current.GetOwinContext().Authentication.Challenge(
                    new AuthenticationProperties
                    {                   
                        RedirectUri = "http://localhost:5000"
                    },
                    OpenIdConnectAuthenticationDefaults.AuthenticationType);
            }
        }

it always say request not authenticated.

Client in IS is like this:

  new Client()
                {
                    ClientId = "mvcClient",
                    ClientName = "MVC Client",
                    //AllowedGrantTypes = GrantTypes.Implicit,
                    AllowedGrantTypes = GrantTypes.HybridAndClientCredentials,

                    ClientSecrets = new List<Secret>()
                    {
                        new Secret("secret".Sha256())
                    },

                   // RequireConsent = false,

                    // where to redirect to after login
                    RedirectUris = { "http://localhost:5002/signin-oidc" },
                    // where to redirect to after logout
                    PostLogoutRedirectUris = { "http://localhost:5002" },

                    AllowedScopes =
                    {
                        StandardScopes.OpenId.Name,
                        StandardScopes.Profile.Name,
                        StandardScopes.OfflineAccess.Name,
                        StandardScopes.Roles.Name,
                        "NamfusAPI"
                    }

and scope like this:

  return new List<Scope>()
            {
                StandardScopes.OpenId, // subject id
                StandardScopes.Profile, // first name, last name
                StandardScopes.OfflineAccess,  // requesting refresh tokens for long lived API access
                new Scope()
                {
                    Name = "NamfusAPI",
                    Description = "Namfus API",
                    Type = ScopeType.Resource,
                    IncludeAllClaimsForUser = true,
                    Claims = new List<ScopeClaim>()
                    {
                        new ScopeClaim(ClaimTypes.Name),
                        new ScopeClaim(ClaimTypes.Role)
                    }
                }
            };

Please suggest how to do this. Thanks

**Comment by brockallen** [comment]
> I see that asp.net web form client is missing in samples. 

we have a sample here: https://github.com/IdentityServer/IdentityServer3.Samples/tree/master/source/Clients/WebFormsClient
