### ISSUE TITLE
Logout in samples

### ISSUE THREAD

**Issue by ducalai** [IdentityServer/IdentityServer4.Samples#87]
I'm playing around with your rc4 updated samples. After updating to Core 1.1, when I run your Quickstart6_AspNetIdentity and test MVC client, I'am not able to logout correctly.

If I look at the logs, I get following error:
````
IdentityServer4.Validation.EndSessionRequestValidator:Information: End session request validation failure: Invalid post logout URI
{
  "ClientId": "mvc",
  "ClientName": "MVC Client",
  "SubjectId": "8838b85b-97f2-45d0-885a-e3d3db6d28c7",
  "Raw": {
    "post_logout_redirect_uri": "http://localhost:5002/signout-callback-oidc",
    "id_token_hint": "eyJhbGciOiJSUzI1NiIsImtpZCI6IjhmOTlhNWEyZDZjNTRjZDY0YWVkZTU4MDhhY2UzYTBlNzNmYTFhMTllNjk1OTE0MjY4MjRmMDNlMDcxM2YwZGYiLCJ0eXAiOiJKV1QifQ.eyJuYmYiOjE0ODA1MjEyNTIsImV4cCI6MTQ4MDUyMTU1MiwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIiwiYXVkIjoibXZjIiwibm9uY2UiOiI2MzYxNjExODAzMTAxNTI4MTMuT0RVeE9HSXdPRE10WlROa05pMDBZakJoTFdFeVltSXRaRFZrWkdVd1lUVmtPV1ZpTVdReVpUZGlNR1F0T1dKaU1DMDBZelptTFdKaVl6TXRaamMwWmpaa1lqTmtOV0ZpIiwiaWF0IjoxNDgwNTIxMjUxLCJzaWQiOiIxZDZhNWQzY2M4ZDZlZmYxZDU2NzdlNWY4Mzc3YmY3OGRiMmViMGU5MTE4Y2Y3ZjkzMDYwYjMxODA5ZjEzMzZjIiwic3ViIjoiODgzOGI4NWItOTdmMi00NWQwLTg4NWEtZTNkM2RiNmQyOGM3IiwiYXV0aF90aW1lIjoxNDgwNTIxMjQ1LCJpZHAiOiJsb2NhbCIsImFtciI6WyJwd2QiXX0.peVqZgfhMYNVMNB99FbKnp9s_y9S6ywIo0myEl9o5tVLTNoiTyXyBUFqwYLaRnF3LrYeDAGn_hUpQm7gbbPbYIdpVl_m3zIdETOI_SAOpyq_bXMomYrGUQZcOuwj0bgN1tsDpj-X_AowrE9kEeMHwNHA0EZjmW2HBTprA6hT1-LauBf-31Yno0uYicLVpvRt0KXrHrEa9cupf94B9l9AYj6tpLI8WUQsiFdnAGTFH_SeJaWHxhLN3XVlwq3y061TfSfnIdMlXmu4co7kWXf4q4LLXoMMSTvctP_TyKI8iopZfNVKtOz7IK9ZwDzH6lomienf0DKO3JOvg8BQpRT9fg",
    "state": "CfDJ8KrcJ9yAwhZDoCktmh5fe-N73w0_5493b7zj6ysS8p57_FoSGY_S2j667D_5E1xbIiuvHeq3lpAb4EA6pdmmhFFL6nd3DdUlNkOVo0anMgC47MZcXsmkQLnOL4tDWmU3gXRksdme6qcyxoUElq2JDbYQxJw8UVdlZ_LwGCbKNp_2"
  }
}
IdentityServer4.Endpoints.EndSessionEndpoint:Error: Error processing end session request Invalid request
````

Then, logoutId parameter in Logout action in AccountController is null.

In Config.cs, MVC Client PostLogoutRedirectUris property is defined with:
````
PostLogoutRedirectUris = { "http:/localhost:5002"}
````

In Startup.cs in MvcClient application, I've also tried to add in UseOpenIdConnectAuthentication middleware:
````
PostLogoutRedirectUri = "http:/localhost:5002"
````
with no effect

I do not understand from where does this http://localhost:5002/signout-callback-oidc come from

Thanks for your help

**Comment by brockallen** [comment]
We're not supporting 1.1 right now -- it's too unstable.

**Comment by YZahringer** [comment]
@ducalai the http://localhost:5002/signout-callback-oidc come from `SignedOutCallbackPath` in `OpenIdConnectOptions`. But I also have the problem with Core 1.1 and the logoutId parameter null.

**Comment by brockallen** [comment]
I'm closing this for now. Tracking here: https://github.com/IdentityServer/IdentityServer4/issues/529

**Comment by brockallen** [comment]
@ducalai see this commit: https://github.com/IdentityServer/IdentityServer4/commit/cda7c80cbaa7dab7d39b9072b1289dfebda9fb76

**Comment by heinecorp** [comment]
I changed the "PostLogoutRedirectUris" to "https://localhost:5002/signout-callback-oidc" on the identity server side not mvc client, instead of just https://localhost:5002, then logout worked fine.
