### ISSUE TITLE
login not happening after adding external login provider

### ISSUE THREAD

**Issue by neerajyadav** [IdentityServer/IdentityServer4.Samples#88]
Adding external login provider (facebook/google) cause issue with login process. I've added external login from QuickStart4_ExternalAuthentication sample.

 ```
app.UseCookieAuthentication(new CookieAuthenticationOptions
            {
                AuthenticationScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme,

                AutomaticAuthenticate = false,
                AutomaticChallenge = false
            });
            //configure google authentication. http://docs.identityserver.io/en/release/quickstarts/4_external_authentication.html#adding-google-support
            app.UseGoogleAuthentication(new GoogleOptions
            {
                AuthenticationScheme = "Google",
                DisplayName = "Google",
                SignInScheme = IdentityServerConstants.ExternalCookieAuthenticationScheme,

                ClientId = "434483408261-55tc8n0cs4ff1fe21ea8df2o443v2iuc.apps.googleusercontent.com",
                ClientSecret = "3gcoTrEDPPJ0ukn_aYYT6PWo"
            });
``` 

After logging with Google account, user is redirected again to login page for the very first time. Clicking on Google button again, redirects to AccessDenied page.

**Comment by leastprivilege** [comment]
Here's the reference sample:
https://github.com/IdentityServer/IdentityServer4.Samples/tree/dev/Quickstarts/4_ImplicitFlowAuthenticationWithExternal

does this work for you?

**Comment by neerajyadav** [comment]
@leastprivilege Yes that sample alone works for me. However I need aspnet identity with external providers. So I get the code form that sample and configure the aspnet identity sample with google login. Local login is working fine. Issue is with Google login. 

System initiate the login process redirects to Google auth page, Ask for user permission. After allowing the permissions, it again redirects back to login page.

**Comment by neerajyadav** [comment]
I think is the issue is related to https://github.com/aspnet/Templates/issues/686

**Comment by neerajyadav** [comment]
I'm not sure if it optimal solution, however [this](http://stackoverflow.com/a/40837219/3944072) thing helps me out. @leastprivilege is this a good way to go?

**Comment by brockallen** [comment]
If you're using ASP.NET Identity, then yes you need to use their constants for their cookies.

**Comment by neerajyadav** [comment]
Do I need to use their constants in both, _CookieAuthenticationOptions_ and _GoogleOptions_ ? Or only with _GoogleOptions_ ?

**Comment by brockallen** [comment]
If you're using ASP.NET Identity, then you're using all of their cookies (and IdentityServer does too). So in short, use all of theirs.

**Comment by neerajyadav** [comment]
Thanks @brockallen and @leastprivilege . I think there should be a note in `startup.cs` class, saying if you want to use external providers, use `AuthenticationScheme` used by aspnet identity itself. It will save a lot of efforts and time for those who want to use this template as base and write external provider mixed with it.

**Comment by brockallen** [comment]
I added google to the ASP.NET Identity quickstart sample.

**Comment by eduardoluizm** [comment]
My guess, the problem is not about cookie name.

Try to login (with user and password), after this, manage account and add Facebook or Google external Account... Then remove it.. and after this try to add again.. Will be redirect to access denied.  I think the problem is the cookie "external" that was not removed at the first login or link. It is just removed if you do logoff..

The problem, is that you may not accept facebook authentication or else give some error, and the cookie will stay there. If the "Identity.External" cookie is there, probably every time when you try to authenticated externally, it will be redirected to Access Denied.

**Comment by phuongtran84** [comment]
I work with Google Authentication but after sign-in google account it call back link: 
http://localhost:5000/signin-google?state=xxxxx and throw error
I just follow the link: 
https://identityserver4.readthedocs.io/en/release/quickstarts/4_external_authentication.html#refexternalauthenticationquickstart
How can I fix it...?
