### ISSUE TITLE
Logout loses logoutId after upgrade to ASP.NET Core 1.1

### ISSUE THREAD

**Issue by virshu** [IdentityServer/IdentityServer4.Samples#89]
I am having a problem that I verified with 6th quickstart (6_AspNetIdentity). After I upgraded ASP.NET Core libraries from 1.0.* to 1.1.0, `AccountController.Logout` in IdentityServer project no longer gets `logoutId`. As result, after logout, `logout.PostLogoutRedirectUri` is `null` and user doesn't get a link to return to application.

The problem doesn't exist with ASP.NET Core 1.0

**Comment by virshu** [comment]
Not sure why a similar question was closed - this ended up being a duplicate. Sorry

**Comment by brockallen** [comment]
I just tested it, and I see the logoutid being passed correctly.

**Comment by virshu** [comment]
Not sure what the difference is. I only updated the packages (see my package.json renamed to *.txt
[project.txt](https://github.com/IdentityServer/IdentityServer4.Samples/files/629702/project.txt)
 from IdentityServer project; similar changes in MVCClient project). No other changes
![logout](https://cloud.githubusercontent.com/assets/4563719/20868084/9a6f43ae-ba07-11e6-85be-71deb005cbca.jpg)

**Comment by brockallen** [comment]
enable logging in idenittyserver then to see it if shows anything

**Comment by virshu** [comment]
Thank you for such immediate response. Here is the log. Logout is at the line 697

[stdout_16232_2016124175934.txt](https://github.com/IdentityServer/IdentityServer4.Samples/files/629706/stdout_16232_2016124175934.txt)

**Comment by brockallen** [comment]
I suggested that *you* look at the log and see what the problem is.

**Comment by virshu** [comment]
I _did_ (frankly, I would appreciate if you didn't assume that I didn't; but whatever. IdentityServer is an awesome product; so I guess, I have to accept some level of condescension).
Anyway - there is nothing that catches the attention of application programmer; but then again - this application programmer ran the sample in order to confirm the problem found in his own code. There is an error ("End session request validation failure: Invalid post logout URI") - but this looks like consequence of the problem; not the root cause.
In any event, I am sure it will be fixed at some point; for now I am happy to wait

**Comment by brockallen** [comment]
Your error is on line: 748: End session request validation failure: Invalid post logout URI

**Comment by brockallen** [comment]
>  I would appreciate if you didn't assume that I didn't

I only assumed because 1) the log clearly stated there was an error, 2) far too often people don't bother to look at the logs, and 3) people expect us to be free support here for something they never paid for, despite their commercial/corporate use. Perhaps this isn't you specifically, so my apologies for lashing out on your thread. Perhaps others will see this and do more of their own debugging first.

**Comment by virshu** [comment]
Brock - you are an author of amazing package; so I don't want to be rude, but did you read my email? 

> There is an error ("End session request validation failure: Invalid post logout URI") - but this looks like consequence of the problem; not the root cause.

 Do you disagree? In any event, the logout URI is from the sample: `PostLogoutRedirectUris = { "http://localhost:5002" }` (I tried with and without trailing slash).

Again - I don't ask you to troubleshoot _my_ code. This is straight sample from the repository (although my code behaves exactly the same way), and you keep insisting that it is *my* problem. So, pardon my frustration!

**Comment by brockallen** [comment]
If the post logout redirect uri is invalid that would explain why there's no logout id passed to the logout page. The ~/signout-callback-oidc is new in 1.1 in the OIDC client middleware.

**Comment by virshu** [comment]
Hi Brock,
By changing `PostLogoutRedirectUris = { "http://localhost:5002/signout-callback-oidc" }` everything is working again. Frankly, I have no idea what you meant by "The ~/signout-callback-oidc is new in 1.1 in the OIDC client middleware" and googling signout-callback-oidc wasn't very helpful, either. So, some writeup I am sure will be appreciated by everybody upgrading to 1.1 and running into this problem! :)
Thank you

**Comment by brockallen** [comment]
Well, Microsoft should do that since they're the ones that made that breaking change in 1.1.

**Comment by Tratcher** [comment]
This change maybe? https://github.com/aspnet/Security/pull/925
