### ISSUE TITLE
AuthorizationManager Not Needed Anymore?

### ISSUE THREAD

**Issue by farzad99** [IdentityServer/IdentityServer4.Samples#9]
I don't see AuthorizationManager class and the authorization attributes like:

`[ResourceAuthorize("Read", "ContactDetails")]`

in the samples. Is there no need for that? And if there's no need for it how can I achieve that functionality in IdSvr4?

**Comment by brockallen** [comment]
The style from our resource based authorization was adopted by the ASP.NET team in their new authorization policy framework: https://docs.asp.net/en/latest/security/authorization/index.html

**Comment by farzad99** [comment]
OK, thank you.
