### ISSUE TITLE
Update SDK version in global.json

### ISSUE THREAD

**Issue by SamJost** [IdentityServer/IdentityServer4.Samples#91]
I might be wrong, but I think global.json should point to the new preview version for the sdk:
"version": "1.0.0-preview2-003131"
instead of
"version": "1.0.0-preview2-003121"

Fresh installations of Visual Studio otherwise will get an error message.

**Comment by damienbod** [comment]
ASP.NET Core 1.1 should be  "version": "1.0.0-preview2-1-003177" (VS2015)

**Comment by damienbod** [comment]
@brockallen should I fix?

**Comment by damienbod** [comment]
fixed here if you want to use it
https://github.com/IdentityServer/IdentityServer4.Samples/pull/93

**Comment by brockallen** [comment]
Thanks!
