### ISSUE TITLE
Sample 5 bug?

### ISSUE THREAD

**Issue by Eneuman** [IdentityServer/IdentityServer4.Samples#94]
Hi
Am i missing something or is this a copy error?

Looking at the source code for sample 5, file : 
[Startup.cs](https://github.com/IdentityServer/IdentityServer4.Samples/blob/dev/Quickstarts/5_HybridFlowAuthenticationWithApiAccess/src/MvcClient/Startup.cs). on line 65

`GetClaimsFromUserInfoEndpoint = true,`

But the return type is "code id_token". Isn't the claims suppose to come in the id token using the hybrid flow, so is the above code line necessary?

(I found this when I was trying to debug why my MVC Hybrid flow was not returning a name claim)

Regards
Per

**Comment by leastprivilege** [comment]
see here https://github.com/IdentityServer/IdentityServer4/issues/528

**Comment by Eneuman** [comment]
Okey, thanks for the info :)
