### ISSUE TITLE
'IdentityServerAuthenticationOptions' does not contain a definition for 'AllowedScopes'

### ISSUE THREAD

**Issue by ry8806** [IdentityServer/IdentityServer4.Samples#95]
In the sample **Quickstart6_AspNetIdentity**, in the "Api" project, in the Startup.cs [here](https://github.com/IdentityServer/IdentityServer4.Samples/blob/dev/Quickstarts/6_AspNetIdentity/src/Api/Startup.cs#L42)

The object IdentityServerAuthenticationOptions doesn't have a definition for "AllowedScopes"...has this been replaced by "AdditionalScopes"?

if so I could raise a PR and carry out this small task..

Thanks

**Comment by leastprivilege** [comment]
thanks! yes please. on dev.

**Comment by brockallen** [comment]
Ah, ok. Yes. I just didn't update this one correctly. Sorry. I'll get it done.
