### ISSUE TITLE
AddInMemoryPersistedGrants seems not needed in Samples

### ISSUE THREAD

**Issue by freerider7777** [IdentityServer/IdentityServer4.Samples#99]
like here:
IdentityServer4.Samples/Quickstarts/7_JavaScriptClient/src/QuickstartIdentityServer/Startup.cs

**Comment by brockallen** [comment]
correct. PR?

**Comment by freerider7777** [comment]
I'm not sure I've done all rigth but it's here:
https://github.com/IdentityServer/IdentityServer4.Samples/pull/100
